import {readFileSync,statSync} from 'node:fs';
import {validateLongitudeV2} from './longitude-v2-integrity';
import {longitudeFileHash} from './longitude-integrity';
import {masterApprovalDecisionSchema,applyMasterVisualApproval} from './master-approval';
import {productionPlanSchema,validateProductionPlanReferences} from './schema';
import {knowledgePackageSchema} from '../knowledge/schema';
import {contentAssetSchema} from '../content-assets/schema';
import {sha256Json} from '../content-intelligence/run-schema';
import decisionData from '../../content-intelligence/reviews/longitude-clock-master-lock-v1/owner-decision.json';
import reviewed from '../../content-intelligence/reviews/longitude-clock-master-lock-v1/production-plan.reviewed.json';
import locked from '../../content-intelligence/reviews/longitude-clock-master-lock-v1/production-plan.locked.json';
import bindings from '../../content-intelligence/reviews/longitude-clock-master-lock-v1/reviewed-bindings.json';
import direction from '../../content-intelligence/reviews/longitude-clock-production-v2/creative-direction.revision-3.json';
import pkgData from '../../content-intelligence/reviews/longitude-clock-approved-v3/knowledge-package.approved.json';
import assetData from '../../content-intelligence/reviews/longitude-clock-approved-v3/content-asset.approved.json';
export const longitudeLockedPlan=productionPlanSchema.parse(locked);
export const longitudeMasterDecision=masterApprovalDecisionSchema.parse(decisionData);
export const validateLongitudeLockedMaster=()=>{
 validateLongitudeV2();const d=longitudeMasterDecision;
 const candidateReceipt=JSON.parse(readFileSync(bindings.reviewedCandidateReceipt.path,'utf8'));
 if(sha256Json(candidateReceipt.master)!==sha256Json(d.artifact)||d.candidateArtifactId!=='longitude-clock.candidate-v2.0'||d.masterArtifactId!=='longitude-clock.locked-master.v2')throw new Error('Approval must target the exact reviewed Candidate V2 receipt, never a different candidate or encode');
 const replay=applyMasterVisualApproval(d,productionPlanSchema.parse(reviewed),bindings,'Exact Longitude Clock master approved; platform presentation review or explicit owner risk acceptance remains separate.');
 if(sha256Json(replay)!==sha256Json(longitudeLockedPlan))throw new Error('Locked plan differs from exact approval replay');
 validateProductionPlanReferences(longitudeLockedPlan,knowledgePackageSchema.parse(pkgData),contentAssetSchema.parse(assetData),direction);
 if(longitudeFileHash(d.artifact.path)!==d.artifact.sha256||statSync(d.artifact.path).size!==d.artifact.bytes||sha256Json(bindings)!==d.candidateBindings.sha256)throw new Error('Locked master/evidence identity drift');
 for(const r of [...bindings.sources,...bindings.qaArtifacts,bindings.reviewedCandidateReceipt])if(longitudeFileHash(r.path)!==r.sha256)throw new Error('Locked production dependency drift: '+r.path);
 if(sha256Json(JSON.parse(readFileSync(d.candidateBindings.path,'utf8')))!==d.candidateBindings.sha256||d.platformApprovalGranted||d.publicationApprovalGranted)throw new Error('Master approval scope drift');
 return {passed:true,ownerMasterApproved:true,artifact:d.artifact,masterArtifactId:d.masterArtifactId,decisionEnteredAt:d.enteredAt,productionPlanRevision:longitudeLockedPlan.revision,captionPlan:d.captionPlan,platformApproved:false,publicationAuthorized:false};
};
