import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {z} from 'zod';
import {knowledgePackageSchema} from '../knowledge/schema';
import {contentAssetSchema} from '../content-assets/schema';
import {creativeDirectionSchema,creativeReferenceSchema} from '../content-assets/creative-direction';
import {validateCreativeDirection} from '../content-assets/creative-direction-integrity';
import {validateProductionPlanReferences} from './schema';
import {validateAdaptiveCaptionPlan} from '../captions/adaptive-plan';
import {sha256Json,stableJson} from '../content-intelligence/run-schema';
import {eastLongitudeDegrees,eastLongitudePoint} from './longitude-geometry';
import metadata from './narration/longitude-clock.json';
import {longitudeClock} from '../content/videos/longitude-clock';
const digest=z.string().regex(/^[a-f0-9]{64}$/);
export const longitudeProductionDecisionSchema=z.object({schemaVersion:z.literal(1),id:z.literal('owner-decision.longitude-clock.creative-production.v1'),revision:z.literal(1),owner:z.literal('Ahmet Nishefci'),authority:z.literal('explicit-owner-message'),enteredAt:z.iso.datetime(),timeBasis:z.literal('decision-entry'),ownerSuppliedReviewTimestamp:z.null(),approvedSourceCommit:z.literal('4c4c967f968972108f53221f6921f721246cf0db'),creativeDirection:creativeReferenceSchema,knowledgePackage:creativeReferenceSchema,contentAsset:creativeReferenceSchema,approvedScriptSha256:digest,visualPlanSha256:digest,comprehensionContractSha256:digest,ownerInstruction:z.string().min(1),creativeDirectionApproved:z.literal(true),productionCandidateAuthorized:z.literal(true),voiceAuditionAuthorized:z.literal(true),ownerMasterApproval:z.literal(false),platformApprovalGranted:z.literal(false),deliveryApprovalGranted:z.literal(false),uploadAuthorized:z.literal(false),publicationApprovalGranted:z.literal(false)}).strict();
export const longitudeFileHash=(path:string)=>createHash('sha256').update(readFileSync(path)).digest('hex');
const read=(path:string):unknown=>JSON.parse(readFileSync(path,'utf8'));
export const validateLongitudeProduction = () => {
 const folder='content-intelligence/creative-directions/longitude-clock-time-to-position-approved-v2';
 const pkg=knowledgePackageSchema.parse(read('content-intelligence/reviews/longitude-clock-approved-v3/knowledge-package.approved.json'));
 const asset=contentAssetSchema.parse(read('content-intelligence/reviews/longitude-clock-approved-v3/content-asset.approved.json'));
 const proposal=creativeDirectionSchema.parse(read('content-intelligence/creative-directions/longitude-clock-time-to-position/direction-v1.json'));
 const decision=longitudeProductionDecisionSchema.parse(read(folder+'/owner-decision.json'));
 const direction=creativeDirectionSchema.parse(read(folder+'/direction.json'));
 const ref=(v:{id:string;revision:number})=>({id:v.id,revision:v.revision,sha256:sha256Json(v)});
 const same=(a:unknown,b:unknown,label:string)=>{if(stableJson(a)!==stableJson(b))throw new Error(label);};
 same(decision.creativeDirection,ref(proposal),'Owner direction approval is stale');
 same(decision.knowledgePackage,ref(pkg),'Owner package approval is stale');same(decision.contentAsset,ref(asset),'Owner asset approval is stale');
 if(decision.approvedScriptSha256!==sha256Json(asset.script)||decision.visualPlanSha256!==sha256Json(asset.visualPlan)||decision.comprehensionContractSha256!==sha256Json(read('content-intelligence/reviews/longitude-clock-finalization-v2/visual-comprehension-contract.json')))throw new Error('Owner factual/comprehension binding drift');
 same(direction,{...proposal,revision:2,state:'ready-for-production-planning',ownerReview:{...proposal.ownerReview,decision:ref(decision)}},'Approved direction changed beyond owner promotion');
 validateCreativeDirection(direction,pkg,asset);
 const plan=validateProductionPlanReferences(read('src/production/plans/longitude-clock.json'),pkg,asset,direction);
 same(plan.ownerDecision,ref(decision),'Production owner authority drift');
 if(plan.visualApproval||plan.status==='owner-visual-approved')throw new Error('Candidate cannot invent master approval');
 const caption=validateAdaptiveCaptionPlan(read('src/captions/plans/longitude-clock.json'),metadata.cues,{width:1080,height:1920},direction,asset);
 if(caption.status!=='review-required'||plan.captions.captionPlanSha256!==sha256Json(caption))throw new Error('Candidate CaptionPlan state/hash drift');
 same(metadata.cues.map(c=>c.transcript).join(' '),asset.script.segments.map(s=>s.text).join(' '),'Narration changed');
 if(metadata.provenance.voiceId==='af_heart'||metadata.provenance.approvedScriptSha256!==sha256Json(asset.script))throw new Error('Voice/script convenience regression');
 for(const c of metadata.cues){const hash=metadata.provenance.cueArtifacts.find(a=>a.id===c.id)?.sha256;if(longitudeFileHash(`public/${c.file}`)!==hash)throw new Error(`Changed exact narration: ${c.id}`);}
 const font=z.object({files:z.array(z.object({path:z.string(),sha256:digest,license:z.literal('OFL-1.1')}).passthrough())}).passthrough().parse(read('public/fonts/longitude-clock/provenance.json'));
 for(const f of font.files)if(longitudeFileHash(f.path)!==f.sha256)throw new Error(`Changed font/license bytes: ${f.path}`);
 const sound=z.object({path:z.string(),sha256:digest}).passthrough().parse(read('src/production/narration/longitude-clock-soundscape.json'));if(longitudeFileHash(sound.path)!==sound.sha256)throw new Error('Changed sound bytes');
 for(const a of plan.assets)if(!a.path||!a.provenance.evidence)throw new Error('Missing production asset provenance');
 const geometry=eastLongitudePoint(eastLongitudeDegrees(14,12),155);
 if(eastLongitudeDegrees(14,12)!==30||geometry.x>=360||geometry.y>=340)throw new Error('North-pole east geometry reversed');
 if(longitudeClock.audio.narrationCues.map(c=>c.transcript).join(' ')!==asset.script.segments.map(s=>s.text).join(' ')||longitudeClock.production?.outputReviewState!=='visual-review-required'||longitudeClock.platformVariantId||longitudeClock.publication)throw new Error('VideoSpec narration/review boundary changed');
 return {passed:true,productionPlan:ref(plan),captionPlan:ref(caption),creativeDirection:ref(direction),ownerDecision:ref(decision),knowledgePackage:ref(pkg),contentAsset:ref(asset),verifiedClaims:8,captionCues:caption.cues.length,measuredNarrationSeconds:metadata.measuredNarrationSeconds,timelineSeconds:metadata.format.durationSeconds,ownerMasterApproved:false,platformApproved:false,publicationAuthorized:false};
};
