import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {z} from 'zod';
import {validateLongitudeProduction,longitudeFileHash} from './longitude-integrity';
import {validateProductionPlanReferences} from './schema';
import {knowledgePackageSchema} from '../knowledge/schema';
import {contentAssetSchema} from '../content-assets/schema';
import {creativeDirectionSchema,creativeReferenceSchema} from '../content-assets/creative-direction';
import {validateAdaptiveCaptionPlan} from '../captions/adaptive-plan';
import {sha256Json,stableJson} from '../content-intelligence/run-schema';
import metadata from './narration/longitude-clock-v2.json';
import {longitudeClockV2} from '../content/videos/longitude-clock-v2';
const read=(p:string):unknown=>JSON.parse(readFileSync(p,'utf8'));
const folder='content-intelligence/reviews/longitude-clock-production-v2';
export const narratorRevisionDecisionSchema=z.object({schemaVersion:z.literal(1),id:z.literal('owner-decision.longitude-clock.narrator-v2'),revision:z.literal(1),owner:z.literal('Ahmet Nishefci'),authority:z.literal('explicit-owner-message'),enteredAt:z.iso.datetime(),timeBasis:z.literal('decision-entry'),ownerSuppliedReviewTimestamp:z.null(),reviewedCandidate:z.object({path:z.literal('artifacts/masters/longitude-clock-candidate-v1.mp4'),sha256:z.literal('71dba2d65c2e86fe00cc11683c8aeaf668a9acd10e877e744be3380bde53b981')}).strict(),parentCreativeDirection:creativeReferenceSchema,contentAsset:creativeReferenceSchema,approvedScriptSha256:z.string(),directionApprovedInPrinciple:z.literal(true),masterApproved:z.literal(false),narrator:z.literal('af_heart'),productionRevisionAuthorized:z.literal(true),materialVisualRedesignAuthorized:z.literal(false),platformApproved:z.literal(false),uploadAuthorized:z.literal(false),publicationAuthorized:z.literal(false),policyDecision:z.string().min(1)}).strict();
export const validateLongitudeV2=()=>{
 validateLongitudeProduction();
 const pkg=knowledgePackageSchema.parse(read('content-intelligence/reviews/longitude-clock-approved-v3/knowledge-package.approved.json'));
 const asset=contentAssetSchema.parse(read('content-intelligence/reviews/longitude-clock-approved-v3/content-asset.approved.json'));
 const parent=creativeDirectionSchema.parse(read('content-intelligence/creative-directions/longitude-clock-time-to-position-approved-v2/direction.json'));
 const direction=creativeDirectionSchema.parse(read(folder+'/creative-direction.revision-3.json'));
 const owner=narratorRevisionDecisionSchema.parse(read(folder+'/owner-decision.json'));
 const ref=(v:{id:string;revision:number})=>({id:v.id,revision:v.revision,sha256:sha256Json(v)});
 const same=(a:unknown,b:unknown)=>{if(stableJson(a)!==stableJson(b))throw new Error('V2 binding or approved visual design drift');};
 same(owner.parentCreativeDirection,ref(parent));same(owner.contentAsset,ref(asset));
 if(owner.approvedScriptSha256!==sha256Json(asset.script)||longitudeFileHash(owner.reviewedCandidate.path)!==owner.reviewedCandidate.sha256)throw new Error('Reviewed V1/editorial identity drift');
 same(direction.decisions.filter(d=>d.dimension!=='narration'),parent.decisions.filter(d=>d.dimension!=='narration'));
 same({...direction,revision:parent.revision,decisions:parent.decisions,ownerReview:parent.ownerReview},parent);
 same(direction.ownerReview.decision,ref(owner));
 const plan=validateProductionPlanReferences(read('src/production/plans/longitude-clock-v2.json'),pkg,asset,direction);
 same(plan.ownerDecision,ref(owner));
 if(plan.visualApproval||plan.status==='owner-visual-approved'||plan.executionPolicy?.narrator.voiceId!=='af_heart')throw new Error('V2 inferred approval or narrator drift');
 const caption=validateAdaptiveCaptionPlan(read('src/captions/plans/longitude-clock-v2.json'),metadata.cues,plan.format,direction,asset);
 const oldCaption=read('src/captions/plans/longitude-clock.json') as typeof caption;
 same(caption.visualTreatment,oldCaption.visualTreatment);same(caption.cues.map(c=>({lines:c.lines,bounds:c.bounds})),oldCaption.cues.map(c=>({lines:c.lines,bounds:c.bounds})));
 if(caption.status!=='review-required'||plan.captions.captionPlanSha256!==sha256Json(caption))throw new Error('V2 caption review/hash drift');
 same(metadata.cues.map(c=>c.transcript).join(' '),asset.script.segments.map(s=>s.text).join(' '));
 if(metadata.provenance.voiceId!=='af_heart'||metadata.provenance.approvedScriptSha256!==sha256Json(asset.script)||metadata.provenance.speed!==0.92)throw new Error('V2 exact narrator provenance drift');
 for(const c of metadata.cues)if(longitudeFileHash('public/'+c.file)!==metadata.provenance.cueArtifacts.find(a=>a.id===c.id)?.sha256)throw new Error('V2 audio changed');
 const sound=read('src/production/narration/longitude-clock-v2-soundscape.json') as {path:string;sha256:string;method:string};if(longitudeFileHash(sound.path)!==sound.sha256||!sound.method.includes('No music'))throw new Error('V2 soundscape drift');
 const oldPlan=read('src/production/plans/longitude-clock.json') as typeof plan;
 same(plan.beats.map(b=>({...b,frames:null})),oldPlan.beats.map(b=>({...b,frames:null})));
 for(const p of ['src/components/LongitudeObjects.tsx','src/components/ObjectTheatreCaptions.tsx','src/design/longitude-fonts.ts'])if(!readFileSync(p).equals(execFileSync('git',['show',`919d18ce20e39209d3279893781669b5d5eeccbd:${p}`])))throw new Error('Material visual change');
 if(longitudeClockV2.platformVariantId||longitudeClockV2.publication||longitudeClockV2.production?.outputReviewState!=='visual-review-required')throw new Error('V2 production boundary drift');
 return {passed:true,productionPlan:ref(plan),captionPlan:ref(caption),creativeDirection:ref(direction),ownerDecision:ref(owner),verifiedClaims:8,narrator:metadata.provenance.voiceId,speed:metadata.provenance.speed,narrationSeconds:metadata.measuredNarrationSeconds,timelineSeconds:metadata.format.durationSeconds,v1Preserved:true,materialVisualChange:false,masterApproved:false,publicationAuthorized:false};
};
