import {millenniumBridgeClaimIds as c} from '../../knowledge/packages/millennium-bridge';
import type {CriticalRegion} from '../millennium-bridge/frames';

const disclosure: CriticalRegion = {id: 'disclosure', x: 108, y: 1492, width: 680, height: 82, meaning: 'Subordinate two-line model disclosure, separate from captions.'};
export const explorationBThesis = 'A human physical contradiction, tactile mechanism, crowd-scale reveal, overhead phase study and satisfying hardware payoff: cinematic shot variety with rich original assets and exact restrained compositing.';
export const explorationBShots = [
  {id: '01-opening', assetId: 'asset.millennium-bridge.exploration-b.01', title: 'The ground shifts beneath a person', beatSuffixes: ['balance-paradox', 'opening-day'], claimIds: [c.lateral, c.footPlacement], shotScale: 'Human-scale low 35 mm', cameraPlan: 'Gentle push toward the planted shoe; lateral deck movement must precede corrective body/step action.', transitionPlan: 'Match cut from searching shoe to near-deck close-up.', improvement: 'Readable corrective lean, bent legs and searching foot, original textured coat, luminous metal deck and London depth replace the flat mannequin scene.', criticalRegions: [disclosure, {id: 'human-balance', x: 195, y: 310, width: 635, height: 1020, meaning: 'Weight-bearing body, arm and corrective contact points.'}]},
  {id: '02-corrective-step', assetId: 'asset.millennium-bridge.exploration-b.02', title: 'Weight transfers through a corrective step', beatSuffixes: ['corrective-steps'], claimIds: [c.footPlacement], shotScale: 'Near-ground shoe/detail macro', cameraPlan: 'Deck slides beneath a controlled planted sole; seeking foot lands laterally. Background remains secondary.', transitionPlan: 'Contact/steel texture match cut expands to crowd.', improvement: 'Tactile soles, compressed stance and leg geometry communicate contact without rings, panels or large force arrows.', criticalRegions: [disclosure, {id: 'shoe-contact', x: 125, y: 700, width: 720, height: 570, meaning: 'Primary planted sole and seeking forefoot/deck contact; outer heel is contextual.'}]},
  {id: '03-crowd-feedback', assetId: 'asset.millennium-bridge.exploration-b.03', title: 'One correction becomes a crowd response', beatSuffixes: ['crowd-feedback'], claimIds: [c.negativeDamping, c.growth, c.withoutSynchrony], shotScale: 'Wide elevated long-lens scale reveal', cameraPlan: 'Reveal bridge depth; independent walkers/contact phases accumulate into lateral deck response, never uniform marching.', transitionPlan: 'Rise and rotate into overhead spatial study.', improvement: 'Many naturally varied people and a long physical bridge over the river establish a scale increase; bounded edge exposures suggest aggregate motion.', criticalRegions: [disclosure, {id: 'crowd-scale', x: 240, y: 690, width: 570, height: 765, meaning: 'Core receding crowd and bridge response.'}]},
  {id: '04-local-coherence', assetId: 'asset.millennium-bridge.exploration-b.04', title: 'Local relationships within varied motion', beatSuffixes: ['coherence-qualification'], claimIds: [c.withoutSynchrony, c.laterCoherence, c.dayUncertainty], shotScale: 'Elevated overhead diagonal', cameraPlan: 'Selective sparse temporal witnesses mark two illustrative local phases while surrounding walkers vary; no inferred historical fraction.', transitionPlan: 'Follow a structural edge into damper detail.', improvement: 'Diagonal deck, river texture and spatial clusters replace another frontal crowd view. Sparse trails suggest local relationships without a universal synchronization claim.', criticalRegions: [disclosure, {id: 'phase-study', x: 240, y: 780, width: 580, height: 665, meaning: 'Illustrative local trajectories among varied central walkers.'}]},
  {id: '05-damping', assetId: 'asset.millennium-bridge.exploration-b.05', title: 'Motion is absorbed by the structure', beatSuffixes: ['energy-out'], claimIds: [c.dampingRetrofit, c.damperSystems], shotScale: 'Integrated hardware macro with bridge continuity', cameraPlan: 'Piston/anchors carry relative structural motion; exposure envelope decays from large to small but nonzero response.', transitionPlan: 'Resolve promptly on the controlled structure; no outro.', improvement: 'A prominent tactile damper is physically pinned to supports; shrinking exposure witnesses make the response change more visible than A’s tiny hardware.', criticalRegions: [disclosure, {id: 'damper-payoff', x: 160, y: 485, width: 640, height: 980, meaning: 'Cylinder, piston, anchor and long-to-tight illustrative response.'}]},
] as const;

// These are uncalibrated temporal witnesses, not scientific plots or force arrows.
export const explorationBWitnesses = (id: string) => {
  if (id === '01-opening') return '<path d="M94 1410Q82 1110 305 720" fill="none" stroke="#e4edf1" stroke-width="4" opacity=".32"/><path d="M113 1403Q100 1100 314 720" fill="none" stroke="#d9b48c" stroke-width="2" opacity=".24"/>';
  if (id === '02-corrective-step') return '<path d="M155 1282L614 1120" stroke="#e8eef0" stroke-width="2" opacity=".18"/>';
  if (id === '03-crowd-feedback') return '<path d="M212 1550Q326 1108 501 720 M180 1550Q302 1094 493 720" fill="none" stroke="#e5f0f2" stroke-width="4" opacity=".38"/>';
  if (id === '04-local-coherence') return '<g fill="none" stroke-linecap="round"><path d="M500 995q-12 24-20 44 M520 1008q-12 24-20 44" stroke="#f0d2a9" stroke-width="3" opacity=".7"/><path d="M593 917q7 25 2 40 M445 1105q-21 8-26 31 M558 1100q4 18-8 31" stroke="#d7e7ee" stroke-width="2" opacity=".5"/></g>';
  return '<g fill="none" stroke-linecap="round"><path d="M650 716C767 738 594 789 670 840S697 943 688 978S706 1042 705 1070Q708 1100 705 1130T706 1195" stroke="#f3cc9b" stroke-width="4" opacity=".52"/><path d="M669 717C757 744 626 796 681 842S706 939 700 978S714 1044 713 1070Q716 1100 713 1130T714 1195" stroke="#ebeff0" stroke-width="2" opacity=".3"/></g>';
};
