import {knowledgePackageSchema} from '../schema';

export const woodFrogFreezeSourceIds = {
  alaskaTolerance: 'source.jeb.wood-frog-hibernation-2013',
  subarcticCryoprotectants: 'source.plos.wood-frog-cryoprotectants-2015',
  glucoseLoading: 'source.pubmed.wood-frog-glucose-1991',
  glucoseTolerance: 'source.jeb.wood-frog-glucose-1993',
  ureaCryoprotection: 'source.jeb.wood-frog-urea-2005',
  cardiacFreezing: 'source.ajp.wood-frog-heart-rate-1989',
  thawRecovery: 'source.ajp.wood-frog-recovery-1991',
  ventilation: 'source.jeb.wood-frog-metabolic-rate-2013',
  freezePhysiologyReview: 'source.physiological-reviews.freeze-tolerance-2017',
  denaliOverview: 'source.nps.denali-wood-frog-2022',
} as const;

export const woodFrogFreezeClaimIds = {
  freezeSurvival: 'wood-frog-freeze-tolerance.claim.freeze-survival',
  cardiacArrest: 'wood-frog-freeze-tolerance.claim.cardiac-arrest',
  ventilationCessation: 'wood-frog-freeze-tolerance.claim.ventilation-cessation',
  thawRecovery: 'wood-frog-freeze-tolerance.claim.thaw-recovery-order',
  circulationCessation: 'wood-frog-freeze-tolerance.claim.circulation-cessation',
  glucoseCryoprotectant: 'wood-frog-freeze-tolerance.claim.glucose-cryoprotectant',
  ureaAndGlucose: 'wood-frog-freeze-tolerance.claim.urea-and-glucose',
  iceRedistribution: 'wood-frog-freeze-tolerance.claim.ice-redistribution',
  alaskaTemperature: 'wood-frog-freeze-tolerance.claim.alaska-temperature',
  alaskaEightWeeks: 'wood-frog-freeze-tolerance.claim.alaska-eight-weeks',
  alaskaTwelveWeeks: 'wood-frog-freeze-tolerance.claim.alaska-twelve-weeks',
} as const;

export const woodFrogFreezeHookIds = {
  stoppedHeart: 'wood-frog-freeze-tolerance.hook.stopped-heart',
  iceWithoutDeath: 'wood-frog-freeze-tolerance.hook.ice-without-death',
  chemicalShield: 'wood-frog-freeze-tolerance.hook.chemical-shield',
  alaskaLaboratory: 'wood-frog-freeze-tolerance.hook.alaska-laboratory',
} as const;

export const woodFrogFreezeKnowledgePackage = knowledgePackageSchema.parse({
  id: 'wood-frog-freeze-tolerance',
  revision: 2,
  topic: 'Wood frog freeze tolerance',
  centralQuestion: 'How can a wood frog survive freezing that stops its heartbeat and pulmonary ventilation?',
  taxonomy: {
    pillar: 'earth-nature',
    domains: ['zoology', 'physiology', 'cryobiology'],
    topics: ['wood-frog', 'freeze-tolerance', 'cryoprotectants'],
  },
  timeliness: 'evergreen',
  thesis: 'Wood frogs survive nonlethal whole-body freezing by keeping ice mainly outside cells, redistributing water, and using glucose and urea as complementary cryoprotectants.',
  viewerPayoff: 'The frog does not become uniformly frozen inside every cell: it survives by managing extracellular ice, cellular dehydration, and the order in which protective chemistry and physiology change.',
  sources: [
    {
      id: woodFrogFreezeSourceIds.alaskaTolerance,
      organization: 'The Company of Biologists — Journal of Experimental Biology',
      title: 'Hibernation physiology, freezing adaptation and extreme freeze tolerance in a northern population of the wood frog',
      sourceType: 'peer-reviewed',
      url: 'https://journals.biologists.com/jeb/article/216/18/3461/11609/Hibernation-physiology-freezing-adaptation-and',
      retrieved: '2026-09-27',
      published: '2013-09-15',
      authors: ['Jon P. Costanzo', 'M. Clara F. do Amaral', 'Andrew J. Rosendale', 'Richard E. Lee Jr.'],
      identifiers: [{scheme: 'DOI', value: '10.1242/jeb.089342'}],
      notes: 'Primary laboratory study of Interior Alaskan and Ohio populations. Exact sample history and partial survival in the endurance trial are material limitations.',
    },
    {
      id: woodFrogFreezeSourceIds.subarcticCryoprotectants,
      organization: 'PLOS ONE',
      title: 'Cryoprotectants and Extreme Freeze Tolerance in a Subarctic Population of the Wood Frog',
      sourceType: 'peer-reviewed',
      url: 'https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0117234',
      retrieved: '2026-09-27',
      published: '2015-02-17',
      authors: ['Jon P. Costanzo', 'Alice M. Reynolds', 'M. Clara F. do Amaral', 'Andrew J. Rosendale', 'Richard E. Lee Jr.'],
      identifiers: [{scheme: 'DOI', value: '10.1371/journal.pone.0117234'}, {scheme: 'PMID', value: '25688861'}],
      notes: 'Open-access primary study. Its 2015 correction restores omitted Table 5 footnotes and does not overturn the claims used here.',
    },
    {
      id: woodFrogFreezeSourceIds.glucoseLoading,
      organization: 'American Physiological Society — American Journal of Physiology',
      title: 'Glucose loading prevents freezing injury in rapidly cooled wood frogs',
      sourceType: 'peer-reviewed',
      url: 'https://pubmed.ncbi.nlm.nih.gov/1750578/',
      retrieved: '2026-09-27',
      publicationLabel: 'December 1991',
      authors: ['Jon P. Costanzo', 'Richard E. Lee Jr.', 'Michael F. Wright'],
      identifiers: [{scheme: 'DOI', value: '10.1152/ajpregu.1991.261.6.R1549'}, {scheme: 'PMID', value: '1750578'}],
      notes: 'Primary controlled experiment available as a PubMed abstract; exogenous glucose reduced erythrocyte and neuromuscular freezing injury.',
    },
    {
      id: woodFrogFreezeSourceIds.glucoseTolerance,
      organization: 'The Company of Biologists — Journal of Experimental Biology',
      title: 'Glucose Concentration Regulates Freeze Tolerance In the Wood Frog Rana Sylvatica',
      sourceType: 'peer-reviewed',
      url: 'https://journals.biologists.com/jeb/article-abstract/181/1/245/6632/Glucose-Concentration-Regulates-Freeze-Tolerance',
      retrieved: '2026-09-27',
      published: '1993-08-01',
      authors: ['Jon P. Costanzo', 'Richard E. Lee Jr.', 'Peter H. Lortz'],
      identifiers: [{scheme: 'DOI', value: '10.1242/jeb.181.1.245'}, {scheme: 'PMID', value: '8409827'}],
      notes: 'Primary experiment. The accessible abstract reports dose-dependent glucose loading, reduced body ice and erythrocyte injury, and improved survival at lower temperatures.',
    },
    {
      id: woodFrogFreezeSourceIds.ureaCryoprotection,
      organization: 'The Company of Biologists — Journal of Experimental Biology',
      title: 'Cryoprotection by urea in a terrestrially hibernating frog',
      sourceType: 'peer-reviewed',
      url: 'https://pubmed.ncbi.nlm.nih.gov/16244167/',
      retrieved: '2026-09-27',
      publicationLabel: 'November 2005',
      authors: ['Jon P. Costanzo', 'Richard E. Lee Jr.'],
      identifiers: [{scheme: 'DOI', value: '10.1242/jeb.01859'}, {scheme: 'PMID', value: '16244167'}],
      notes: 'Primary experiments available as a PubMed abstract. Urea accumulated before freezing and protected frozen/thawed cells and tissues in vitro.',
    },
    {
      id: woodFrogFreezeSourceIds.cardiacFreezing,
      organization: 'American Physiological Society — American Journal of Physiology',
      title: 'Freezing-induced changes in the heart rate of wood frogs (Rana sylvatica)',
      sourceType: 'peer-reviewed',
      url: 'https://journals.physiology.org/doi/10.1152/ajpregu.1989.257.5.R1046',
      retrieved: '2026-09-27',
      published: '1989-11-01',
      authors: ['J. R. Layne Jr.', 'R. E. Lee Jr.', 'T. L. Heil'],
      identifiers: [{scheme: 'DOI', value: '10.1152/ajpregu.1989.257.5.R1046'}, {scheme: 'PMID', value: '2589531'}],
      notes: 'Primary ECG study of nonlethal laboratory freezing. Post-thaw heartbeat timing was recorded in one frog and must not be generalized as a precise universal recovery time.',
    },
    {
      id: woodFrogFreezeSourceIds.thawRecovery,
      organization: 'American Physiological Society — American Journal of Physiology',
      title: 'Resumption of physiological functions in the wood frog (Rana sylvatica) after freezing',
      sourceType: 'peer-reviewed',
      url: 'https://pubmed.ncbi.nlm.nih.gov/1858939/',
      retrieved: '2026-09-27',
      publicationLabel: 'July 1991',
      authors: ['J. R. Layne Jr.', 'M. C. First'],
      identifiers: [{scheme: 'DOI', value: '10.1152/ajpregu.1991.261.1.R134'}, {scheme: 'PMID', value: '1858939'}],
      notes: 'Primary thawing study. Cardiac function returned first; spontaneous breathing and hindleg reflexes followed, but not in every frog during the 3–4 hour observation period.',
    },
    {
      id: woodFrogFreezeSourceIds.ventilation,
      organization: 'The Company of Biologists — Journal of Experimental Biology',
      title: 'Real-time measurement of metabolic rate during freezing and thawing of the wood frog, Rana sylvatica: implications for overwinter energy use',
      sourceType: 'peer-reviewed',
      url: 'https://pubmed.ncbi.nlm.nih.gov/23255194/',
      retrieved: '2026-09-27',
      published: '2013-01-15',
      authors: ['Brent J. Sinclair', 'Joseph R. Stinziano', 'Caroline M. Williams', 'Heath A. MacMillan', 'Katie E. Marshall', 'Kenneth B. Storey'],
      identifiers: [{scheme: 'DOI', value: '10.1242/jeb.076331'}, {scheme: 'PMID', value: '23255194'}],
      notes: 'Primary flow-through respirometry study. Visible pulmonary ventilation and carbon-dioxide output are distinct measurements; neither is a direct measurement of circulation.',
    },
    {
      id: woodFrogFreezeSourceIds.freezePhysiologyReview,
      organization: 'American Physiological Society — Physiological Reviews',
      title: 'Molecular Physiology of Freeze Tolerance in Vertebrates',
      sourceType: 'peer-reviewed',
      url: 'https://journals.physiology.org/doi/10.1152/physrev.00016.2016',
      retrieved: '2026-09-27',
      publicationLabel: 'April 2017',
      authors: ['Kenneth B. Storey', 'Janet M. Storey'],
      identifiers: [{scheme: 'DOI', value: '10.1152/physrev.00016.2016'}, {scheme: 'PMID', value: '28179395'}],
      notes: 'Peer-reviewed synthesis used to contextualize extracellular ice, cellular dehydration and the approximate fraction of body water that freezes.',
    },
    {
      id: woodFrogFreezeSourceIds.denaliOverview,
      organization: 'U.S. National Park Service — Denali National Park and Preserve',
      title: 'Amphibians',
      sourceType: 'government',
      url: 'https://www.nps.gov/dena/learn/nature/amphibians.htm',
      retrieved: '2026-09-27',
      published: '2022-05-05',
      notes: 'Authoritative public-facing context only. Its “freeze solid” shorthand and −12°C summary are not used as primary evidence for the final script.',
    },
  ],
  claims: [
    {
      id: woodFrogFreezeClaimIds.freezeSurvival,
      type: 'quantitative',
      statement: 'Wood frogs can survive nonlethal freezing in which up to about two-thirds of total body water becomes extracellular ice.',
      quantity: {kind: 'scalar', value: 67, unit: '% of total body water', precision: 'approximate'},
      basis: 'estimated',
      display: 'up to about two-thirds of body water',
      evidence: [
        {sourceId: woodFrogFreezeSourceIds.alaskaTolerance, locator: 'Introduction, paragraph 2; Discussion, Freeze tolerance, paragraphs 3–5', notes: 'The article describes survival with up to two-thirds of body water frozen and treats 67% body ice as an approximate lethal threshold, while emphasizing population variation.'},
        {sourceId: woodFrogFreezeSourceIds.freezePhysiologyReview, locator: 'Section II.B, freeze-tolerant frogs; discussion of extracellular ice and 65–70% total-body-water conversion', notes: 'The review synthesizes experimental literature describing 65–70% of total body water as extracellular ice in freeze-tolerant frogs.'},
      ],
      verificationStatus: 'supported',
      caveats: ['This is an approximate upper range, not a universal fraction reached by every frog or every freeze.'],
    },
    {
      id: woodFrogFreezeClaimIds.cardiacArrest,
      type: 'qualitative',
      statement: 'During controlled nonlethal freezing, cardiac activity in wood frogs can cease near the completion of ice formation.',
      evidence: [{sourceId: woodFrogFreezeSourceIds.cardiacFreezing, locator: 'Abstract; Methods and Results, pp. R1046–R1048, ECG time course and cardiac-arrest observations', notes: 'ECG monitoring showed a rapid initial increase, subsequent slowing, and cardiac arrest in monitored frogs as ice formation approached completion.'}],
      verificationStatus: 'supported',
      caveats: ['The study documents a reversible physiological arrest during controlled nonlethal freezing; it does not mean the frog died.'],
    },
    {
      id: woodFrogFreezeClaimIds.ventilationCessation,
      type: 'qualitative',
      statement: 'Visible pulmonary ventilation ceases during freezing in wood frogs.',
      evidence: [{sourceId: woodFrogFreezeSourceIds.ventilation, locator: 'Results, “Metabolic rate during freezing”, Fig. 1 and Table 1', notes: 'In 12 frogs, visible ventilation ceased 76.9±8.8 minutes after the freezing exotherm began; CO2 emission continued longer and is a separate measure.'}],
      verificationStatus: 'supported',
      caveats: ['Pulmonary ventilation is not identical to all gas exchange or cellular respiration; say breathing or pulmonary ventilation, not that all metabolism stops.'],
    },
    {
      id: woodFrogFreezeClaimIds.thawRecovery,
      type: 'qualitative',
      statement: 'After nonlethal freezing, cardiac function returns before spontaneous breathing and hindleg reflexes during thawing.',
      evidence: [
        {sourceId: woodFrogFreezeSourceIds.thawRecovery, locator: 'Abstract', notes: 'Cardiac function was the first measured function to return; spontaneous breathing and hindleg reflexes resumed later, but not in every frog during the 3–4 hour observation period.'},
        {sourceId: woodFrogFreezeSourceIds.cardiacFreezing, locator: 'Abstract and Results, single-frog thaw recording', notes: 'One monitored frog resumed heartbeat within one hour after thawing began and approached its prior rate within hours.'},
      ],
      verificationStatus: 'supported',
      caveats: ['The order is supported; a universal exact recovery time is not. The one-hour cardiac result came from one frog.'],
    },
    {
      id: woodFrogFreezeClaimIds.circulationCessation,
      type: 'qualitative',
      statement: 'Blood circulation ceases as whole-body freezing advances.',
      evidence: [
        {sourceId: woodFrogFreezeSourceIds.subarcticCryoprotectants, locator: 'Discussion, Glycemic Response, paragraph 1', notes: 'The authors state that glucose must be distributed before freezing progresses to the point that circulation ceases.'},
        {sourceId: woodFrogFreezeSourceIds.freezePhysiologyReview, locator: 'Section II.B, physiological consequences of whole-body freezing', notes: 'The review treats heartbeat and circulation cessation as consequences of extensive extracellular freezing.'},
      ],
      verificationStatus: 'uncertain',
      caveats: ['The inspected sources state or infer cessation, but this review did not locate a primary experiment directly measuring blood flow to zero. Exclude this claim from the script and approved hook unless stronger evidence is reviewed.'],
    },
    {
      id: woodFrogFreezeClaimIds.glucoseCryoprotectant,
      type: 'qualitative',
      statement: 'After freezing begins, liver glycogen is rapidly converted to glucose and distributed as a cryoprotectant that reduces body ice and cellular injury.',
      evidence: [
        {sourceId: woodFrogFreezeSourceIds.subarcticCryoprotectants, locator: 'Introduction, paragraphs 2–4; Results, Figs 2–3; Discussion, Glycemic Response', notes: 'The study measures hepatic glycogen loss and large tissue-glucose increases after experimental freezing.'},
        {sourceId: woodFrogFreezeSourceIds.glucoseTolerance, locator: 'Abstract', notes: 'Dose-dependent glucose loading reduced body ice and erythrocyte injury and improved survival at lower temperatures.'},
        {sourceId: woodFrogFreezeSourceIds.glucoseLoading, locator: 'Abstract', notes: 'Glucose-loaded frogs showed less erythrocyte and neuromuscular injury after rapid cooling and freezing.'},
      ],
      verificationStatus: 'supported',
      caveats: ['Glucose is one component of a broader freeze-tolerance system and must be circulated before advanced freezing impedes transport.'],
    },
    {
      id: woodFrogFreezeClaimIds.ureaAndGlucose,
      type: 'qualitative',
      statement: 'Urea accumulates during winter conditioning before freezing, while glucose is mobilized after freezing begins; both contribute to cryoprotection through partly different mechanisms.',
      evidence: [
        {sourceId: woodFrogFreezeSourceIds.subarcticCryoprotectants, locator: 'Abstract; Introduction, paragraphs 2–4; Discussion, Ureic Response', notes: 'The study distinguishes pre-freeze urea accrual from freeze-triggered glucose mobilization and reports tissue-specific differences.'},
        {sourceId: woodFrogFreezeSourceIds.ureaCryoprotection, locator: 'Abstract', notes: 'Physiological urea concentrations reduced freeze/thaw damage in erythrocytes and improved post-thaw viability of intact tissues in vitro.'},
      ],
      verificationStatus: 'supported',
      caveats: ['Do not depict urea as a simultaneous liver-to-tissue surge equivalent to glucose; timing and tissue distribution differ.'],
    },
    {
      id: woodFrogFreezeClaimIds.iceRedistribution,
      type: 'qualitative',
      statement: 'As extracellular ice forms, water leaves cells and organs; much of it freezes in coelomic, subdermal and lymphatic spaces, limiting ice within tissues and dangerous intracellular ice.',
      evidence: [
        {sourceId: woodFrogFreezeSourceIds.alaskaTolerance, locator: 'Introduction, paragraph 7; Discussion, Dynamics of water and ice, paragraphs 1–3', notes: 'The paper describes reversible organ dehydration and extra-organ ice sequestration as protection against intra-organ damage.'},
        {sourceId: woodFrogFreezeSourceIds.subarcticCryoprotectants, locator: 'Results, Responses to Freezing and Fig. 1; Discussion, Organ Dehydration', notes: 'Frozen organs lost substantial water; translocated water freezes in lymph sacs, subdermal spaces and the coelom.'},
      ],
      verificationStatus: 'supported',
      caveats: ['“Frozen solid” is misleading if it implies uniform intracellular freezing. Visuals must show extracellular ice and cellular dehydration, not cells filled with ice.'],
    },
    {
      id: woodFrogFreezeClaimIds.alaskaTemperature,
      type: 'quantitative',
      statement: 'In one laboratory trial, four winter-acclimatized Interior Alaskan wood frogs were slowly cooled to a minimum of −16°C, held there for six hours, and all met the study’s righting-response survival criterion after thawing.',
      quantity: {kind: 'scalar', value: -16, unit: '°C minimum cooling temperature', precision: 'exact'},
      basis: 'measured',
      display: '4 of 4 recovered after cooling to −16°C',
      evidence: [{sourceId: woodFrogFreezeSourceIds.alaskaTolerance, locator: 'Materials and Methods, Freeze tolerance trials, paragraphs 1–3; Results, Freeze tolerance trials, paragraphs 1–2', notes: 'The four frogs had already survived an earlier −8°C trial, were cooled at 0.05°C/h, held at −16°C for 6 h, spent 326 h frozen by the study definition, and showed normal posture/righting by 2 days post-thaw.'}],
      verificationStatus: 'supported',
      caveats: ['This was a small, population-specific, staged laboratory trial and does not establish a universal wood-frog temperature limit.'],
    },
    {
      id: woodFrogFreezeClaimIds.alaskaEightWeeks,
      type: 'quantitative',
      statement: 'In the same staged laboratory program, two of four Interior Alaskan frogs held at −4°C for eight weeks met the study’s seven-day righting-response survival criterion.',
      quantity: {kind: 'scalar', value: 8, unit: 'weeks at −4°C', precision: 'exact'},
      basis: 'measured',
      display: '2 of 4 survived 8 weeks at −4°C',
      evidence: [{sourceId: woodFrogFreezeSourceIds.alaskaTolerance, locator: 'Materials and Methods, Freeze tolerance trials, paragraph 3; Results, Freeze tolerance trials, final paragraph', notes: 'Three of four initially appeared viable, but only two met the formal survival criterion. All had undergone earlier −8°C and −12°C/−16°C trials.'}],
      verificationStatus: 'supported',
      caveats: ['The original “frogs endured two months” wording concealed 50% survival and prior severe-freeze exposure; do not use it.'],
    },
    {
      id: woodFrogFreezeClaimIds.alaskaTwelveWeeks,
      type: 'quantitative',
      statement: 'None of four Interior Alaskan frogs held at −4°C for twelve weeks in that staged laboratory program survived by the study’s criterion.',
      quantity: {kind: 'scalar', value: 12, unit: 'weeks at −4°C', precision: 'exact'},
      basis: 'measured',
      display: '0 of 4 survived 12 weeks at −4°C',
      evidence: [{sourceId: woodFrogFreezeSourceIds.alaskaTolerance, locator: 'Materials and Methods, Freeze tolerance trials, paragraph 3; Results, Freeze tolerance trials, final paragraph', notes: 'All four were inanimate following thaw and scored as mortalities; the authors note that earlier severe-freeze trials may have stressed the subjects.'}],
      verificationStatus: 'supported',
      caveats: ['This experimental outcome does not contradict separate field observations of longer winter freezing under different natural conditions.'],
    },
  ],
  caveats: [
    {id: 'wood-frog-freeze-tolerance.caveat.population', statement: 'Freeze tolerance varies among populations and protocols; Alaska-specific laboratory results are not universal species limits.', claimIds: [woodFrogFreezeClaimIds.alaskaTemperature, woodFrogFreezeClaimIds.alaskaEightWeeks, woodFrogFreezeClaimIds.alaskaTwelveWeeks]},
    {id: 'wood-frog-freeze-tolerance.caveat.frozen-solid', statement: 'Do not use “frozen solid” without qualification: survivable freezing is dominated by extracellular and extra-organ ice, while intracellular ice is dangerous.', claimIds: [woodFrogFreezeClaimIds.freezeSurvival, woodFrogFreezeClaimIds.iceRedistribution]},
    {id: 'wood-frog-freeze-tolerance.caveat.vital-functions', statement: 'Heartbeat, pulmonary ventilation and circulation are separate claims. The reviewed evidence directly measures cardiac activity and ventilation; direct zero-flow evidence was not located.', claimIds: [woodFrogFreezeClaimIds.cardiacArrest, woodFrogFreezeClaimIds.ventilationCessation, woodFrogFreezeClaimIds.circulationCessation]},
  ],
  hooks: [
    {id: woodFrogFreezeHookIds.stoppedHeart, archetype: 'impossible-sounding-fact', text: 'A wood frog can survive a freeze that stops its heartbeat—then thaw and recover.', viewerPromise: 'Explain how extracellular ice and cryoprotectants make reversible physiological arrest survivable.', claimIds: [woodFrogFreezeClaimIds.freezeSurvival, woodFrogFreezeClaimIds.cardiacArrest, woodFrogFreezeClaimIds.thawRecovery]},
    {id: woodFrogFreezeHookIds.iceWithoutDeath, archetype: 'contradiction', text: 'Much of a wood frog’s body water can freeze—but the ice forms mainly outside its cells.', viewerPromise: 'Replace the misleading “frozen solid” image with the real water-and-ice mechanism.', claimIds: [woodFrogFreezeClaimIds.freezeSurvival, woodFrogFreezeClaimIds.iceRedistribution]},
    {id: woodFrogFreezeHookIds.chemicalShield, archetype: 'question', text: 'How does a frog protect its cells when much of its body water turns to ice?', viewerPromise: 'Reveal how extracellular ice, glucose and urea work together without implying that cells freeze internally.', claimIds: [woodFrogFreezeClaimIds.freezeSurvival, woodFrogFreezeClaimIds.glucoseCryoprotectant, woodFrogFreezeClaimIds.ureaAndGlucose, woodFrogFreezeClaimIds.iceRedistribution]},
    {id: woodFrogFreezeHookIds.alaskaLaboratory, archetype: 'surprising-statement', text: 'In one lab trial, four Interior Alaskan wood frogs recovered after a slow freeze to −16°C.', viewerPromise: 'Explain a precisely scoped cold-tolerance experiment without turning it into a universal species record.', claimIds: [woodFrogFreezeClaimIds.alaskaTemperature]},
  ],
  narrativeOpportunities: [
    {id: 'wood-frog-freeze-tolerance.narrative.reversible-arrest', title: 'Reversible physiological arrest', description: 'Open on a heartbeat stopping during a survivable freeze, then explain the spatial and chemical protection that permits recovery.', claimIds: [woodFrogFreezeClaimIds.cardiacArrest, woodFrogFreezeClaimIds.thawRecovery, woodFrogFreezeClaimIds.glucoseCryoprotectant, woodFrogFreezeClaimIds.iceRedistribution]},
    {id: 'wood-frog-freeze-tolerance.narrative.population-spectrum', title: 'A carefully bounded Alaskan experiment', description: 'Use the −16°C trial and partial endurance results to show why sample, prior exposure and survival criterion matter.', claimIds: [woodFrogFreezeClaimIds.alaskaTemperature, woodFrogFreezeClaimIds.alaskaEightWeeks, woodFrogFreezeClaimIds.alaskaTwelveWeeks]},
  ],
  visualOpportunities: [
    {id: 'wood-frog-freeze-tolerance.visual.cardiac-freeze-thaw', title: 'Freeze, cardiac arrest, staged recovery', description: 'Track a labeled laboratory-style cardiac trace through freezing and show heart activity returning before breathing and hindleg reflexes.', claimIds: [woodFrogFreezeClaimIds.cardiacArrest, woodFrogFreezeClaimIds.thawRecovery]},
    {id: 'wood-frog-freeze-tolerance.visual.extracellular-ice', title: 'Extracellular ice and a dehydrating cell', description: 'Show water leaving a cell as ice grows outside it, with glucose and urea remaining in the unfrozen fluid; never place ice crystals inside the surviving cell.', claimIds: [woodFrogFreezeClaimIds.glucoseCryoprotectant, woodFrogFreezeClaimIds.ureaAndGlucose, woodFrogFreezeClaimIds.iceRedistribution]},
  ],
  relatedQuestions: ['Why is intracellular ice especially damaging?', 'How do Alaskan and temperate wood-frog populations differ?', 'What returns first when a frozen wood frog thaws?'],
  followUpOpportunities: ['A study-design short explaining what the −16°C trial actually measured', 'A comparison of freeze tolerance and freeze avoidance in animals'],
  editorialStatus: 'review',
});
