import {Img,staticFile} from 'remotion';
import earlyReport from '../../content-intelligence/cycles/cycle-10/research/singular-escape-inspected.png';
import recaptureReport from '../../content-intelligence/cycles/cycle-10/research/slave-hunters-inspected.png';
export const craftInk='#17232A',craftPaper='#EFE9DD',craftAccent='#E6B482';
const clamp=(v:number)=>Math.max(0,Math.min(1,v));
const enter=(t:number,start=0,length=.45)=>{const x=clamp((t-start)/length);return 1-(1-x)**3;};
const Portrait=({person,width=290,height=380,disguise=false}:{person:'ellen'|'william';width?:number;height?:number;disguise?:boolean})=><div style={{width,height,overflow:'hidden',position:'relative',background:craftPaper}}><Img src={staticFile(`visuals/craft-escape/${disguise?'ellen-frontispiece.jpg':'craft-portraits.jpg'}`)} style={{position:'absolute',width:width*(disguise?1.5:2.3),maxWidth:'none',left:-width*(disguise?.26:.54),top:disguise?-height*.18:person==='william'?-height*.4:-height*1.45,filter:'grayscale(1)',mixBlendMode:'multiply'}}/></div>;
const Register=({sign=false,t=0}:{sign?:boolean;t?:number})=><div style={{position:'absolute',left:30,top:55,width:660,height:470,background:'#FBF7EE',color:craftInk,padding:38,boxSizing:'border-box',transform:`translateY(${(1-enter(t))*50}px) rotate(${-2+enter(t)*2}deg)`,boxShadow:'0 18px 50px #0003'}}><div style={{fontSize:25,letterSpacing:2,color:'#765B47'}}>EXPLANATORY RECONSTRUCTION</div><div style={{fontSize:43,fontWeight:600,marginTop:35}}>PASSENGER REGISTER</div><div style={{height:2,background:'#9F978A',marginTop:25}}/><div style={{fontSize:27,marginTop:28}}>NAME</div><div style={{fontSize:27,marginTop:45}}>SIGNATURE</div><div style={{height:2,background:sign?'#9F4A39':'#9F978A',marginTop:28,width:520,transformOrigin:'left',transform:`scaleX(${enter(t,.3,.8)})`}}/>{sign&&<div style={{fontSize:34,color:'#93402D',marginTop:22,opacity:enter(t,1)}}>She could not write.</div>}</div>;
const Hand=({t}:{t:number})=><svg width="700" height="530" viewBox="0 0 730 530" style={{position:'absolute',left:15,top:80,transform:`translateX(${(1-enter(t))*180}px)`}}><path d="M70 440L240 290 Q244 224 291 176 L342 138 Q370 124 376 154 L359 181 Q414 137 448 149 Q469 162 455 183 Q492 165 510 184 Q530 205 510 230 Q545 221 552 251 Q557 278 530 304 L421 388 Q378 420 315 419 L190 512" fill={craftPaper} stroke={craftInk} strokeWidth="5"/><path d="M215 324L336 438L433 357L302 222Z" fill="#FFFAEF" stroke="#8D8374" strokeWidth="4" opacity={enter(t,.4,.6)}/>{[0,1,2,3].map(n=><path key={n} d={`M${229+n*20} ${311-n*17}L${355+n*20} ${421-n*17}`} stroke="#B9AE9F" strokeWidth="3" pathLength="1" strokeDasharray="1" strokeDashoffset={1-enter(t,.6+n*.18,.4)}/>)}</svg>;
const cities=[{name:'Macon',x:100,y:495},{name:'Savannah',x:255,y:475},{name:'Charleston',x:380,y:400},{name:'Wilmington',x:420,y:320},{name:'Richmond',x:300,y:235},{name:'Fredericksburg',x:375,y:180},{name:'Washington',x:445,y:130},{name:'Baltimore',x:480,y:80},{name:'Philadelphia',x:540,y:25}];
const Route=({progress,stop=false}:{progress:number;stop?:boolean})=>{
 const max=stop?7:8,amount=clamp(progress)*max,points=cities.map(c=>`${c.x},${c.y}`).join(' ');
 return <svg viewBox="0 -25 730 620" width="730" height="620"><path d="M40 530 Q190 510 290 475 Q435 405 445 300 Q480 205 515 165 Q555 115 590 25L665 -20" fill="none" stroke="#596872" strokeWidth="2" opacity=".6"/><text x="485" y="435" fontSize="24" fill="#8EAAA9" transform="rotate(-55 485 435)">SCHEMATIC • NOT A MAP</text><polyline points={points} stroke="#53626A" strokeWidth="3" fill="none"/>{cities.slice(0,max).map((c,i)=>{const b=cities[i+1]!;return <path key={c.name} d={`M${c.x} ${c.y}L${b.x} ${b.y}`} fill="none" stroke={craftAccent} strokeWidth="5" pathLength="1" strokeDasharray="1" strokeDashoffset={1-clamp(amount-i)}/>;})}{cities.map((c,i)=><g key={c.name} opacity={i<=amount+.15?1:.35}><circle cx={c.x} cy={c.y} r={c.name==='Baltimore'?9:6} fill={i<=amount?craftAccent:'#53626A'}/><text x={c.x-15} y={c.y-20} textAnchor="end" fontSize="27" fill={craftPaper}>{c.name}</text></g>)}{stop&&amount>=7&&<circle cx="480" cy="80" r="24" fill="none" stroke={craftAccent} strokeWidth="3"/>}</svg>;
};
const StageHeading=({children,dark=true}:{children:React.ReactNode;dark?:boolean})=><div data-critical="title" style={{position:'absolute',left:125,top:340,width:730,color:dark?craftPaper:craftInk,fontSize:58,fontWeight:600,lineHeight:1.1,whiteSpace:'pre-line'}}>{children}</div>;
export const CraftDocumentTheatre=({index,t,duration}:{index:number;t:number;duration:number})=>{
 const dark=[0,1,5,6,7,8,9].includes(index),ink=dark?craftPaper:craftInk,p=clamp(t/duration);
 const disclosure=['Later portraits • 1860 / 1872','Route sequence is schematic • not a map','Injury graphic / register are explanatory','Their 1860 account • portrait omits facial bandage','Later portraits • William helped sustain the disguise','Baltimore: later 1860 participant account','Ownership question: paraphrase of their account','Release: William’s later 1860 account','Arrival ≠ lasting safety • 1850 recapture report','Later portraits • Ellen and William Craft'][index]!;
 return <>
 <div style={{position:'absolute',top:300,left:0,width:1080,height:1015,background:dark?craftInk:craftPaper}}/>
 <StageHeading dark={dark}>{['Escape as\nthe slaveholder.','Open travel.\nA new vulnerability.','An excuse\nnot to sign.','Illness was part\nof the strategy.','A disguise sustained\nby two people.','Baltimore.\nA different test.','Appearance\nwas not proof.','Discretionary passage.\nNot a guarantee.','Four days to arrive.\nMore danger ahead.','Their roles were false.\nTheir ingenuity was real.'][index]}</StageHeading>
 <div data-critical="scene" style={{position:'absolute',left:125,top:530,width:730,height:660,color:ink,overflow:'hidden'}}>
 {index===0&&<><div style={{position:'absolute',left:45,top:25,transform:`translateX(${(1-enter(t))*(-30)}px)`}}><Portrait person="ellen" disguise width={320} height={420}/><div style={{fontSize:29,marginTop:18}}>ELLEN CRAFT</div><div style={{fontSize:34,color:craftAccent,marginTop:12}}>Apparent master</div></div><div style={{position:'absolute',left:390,top:90,transform:`translateX(${(1-enter(t,2.7))*30}px)`,opacity:.35+.65*enter(t,2.7)}}><Portrait person="william" width={280} height={350}/><div style={{fontSize:29,marginTop:18}}>WILLIAM CRAFT</div><div style={{fontSize:32,color:craftAccent,marginTop:12}}>Apparent servant</div></div><svg style={{position:'absolute',top:570,left:40}} width="620" height="65"><path d="M0 28H620" stroke={craftAccent} strokeWidth="2"/><text x="310" y="61" textAnchor="middle" fill={craftPaper} fontSize="28">Their imposed relationship, inverted</text></svg></>}
 {index===1&&(t<4.08?<div style={{transform:`translateY(${35*p}px)`}}><Route progress={clamp(t/3.6)} stop/><div style={{position:'absolute',left:35,top:585,fontSize:31,color:craftAccent}}>1848 • train and steamer</div></div>:<div style={{position:'absolute',width:730,height:660}}><Register sign t={t-4.08}/><div style={{position:'absolute',left:70,top:585,fontSize:38,color:craftAccent}}>What if she had to sign?</div></div>)}
 {index===2&&<><div style={{opacity:.15}}><Register t={1}/></div><Hand t={t}/><div style={{position:"absolute",left:430,top:525,fontSize:28}}>RIGHT HAND</div>{t>3.3&&<div style={{position:'absolute',top:10,left:405,width:275,height:305,overflow:'hidden',transform:`translateY(${(1-enter(t,3.3))*50}px) rotate(4deg)`,border:'5px solid #C7B59D',boxSizing:'border-box'}}><Img src={earlyReport} style={{width:285,position:'absolute',top:-10,left:-6}}/></div>}<div style={{position:'absolute',left:35,top:580,fontSize:30}}>Strategy reported in January 1849</div></>}
 {index===3&&<><div style={{position:'absolute',left:-10+enter(t)*20,top:15,transform:`scale(${1.02+p*.04})`,transformOrigin:'left top'}}><Portrait person="ellen" disguise width={330} height={540}/></div><div style={{position:'absolute',left:355,top:30,width:350}}>{[['Bandage','Concealed beardless chin',2.4],['Spectacles','Obscured her face',4.4],['Apparent illness','Excused conversation',6.8]].map(([a,b,start])=><div key={a} style={{opacity:enter(t,Number(start)),transform:`translateX(${(1-enter(t,Number(start)))*35}px)`,marginBottom:44}}><div style={{fontSize:35,fontWeight:600}}>{a}</div><div style={{fontSize:27,lineHeight:1.3,marginTop:12}}>{b}</div><div style={{height:2,background:'#A99177',marginTop:22,width:280*enter(t,Number(start),.7)}}/></div>)}</div></>}
 {index===4&&<><div style={{position:'absolute',left:25,top:15,transform:`translateX(${(1-enter(t))*-50}px)`}}><Portrait person="william" width={330} height={425}/><div style={{fontSize:32,marginTop:20}}>WILLIAM CRAFT</div></div><div style={{position:'absolute',left:425,top:80,transform:`translateX(${(1-enter(t))*(50)}px)`}}><Portrait person="ellen" disguise width={230} height={370}/></div><svg width="700" height="120" style={{position:'absolute',top:525}}><path d="M70 30H630" stroke="#9C6C49" strokeWidth="3" pathLength="1" strokeDasharray="1" strokeDashoffset={1-enter(t,.4,1)}/><text x="350" y="86" textAnchor="middle" fill={craftInk} fontSize="34">Active partners in the plan</text></svg></>}
 {index===5&&(t<3?<Route progress={1} stop/>:<div style={{background:craftPaper,color:craftInk,padding:'40px 45px',marginTop:35,transform:`translateY(${(1-enter(t,3))*170}px)`,boxSizing:'border-box'}}><div style={{fontSize:26,color:'#87513B'}}>EXPLANATORY CHECKPOINT • PARAPHRASE</div><div style={{fontSize:45,fontWeight:600,lineHeight:1.22,marginTop:45}}>Did the supposed master<br/>have the right to take<br/>William onward?</div><div style={{height:2,background:'#AC947B',marginTop:40,transformOrigin:'left',transform:`scaleX(${enter(t,5,1)})`}}/><div style={{fontSize:29,marginTop:36}}>Their account reports<br/>a demand for ownership assurance.</div></div>)}
 {index===6&&<><div style={{position:'absolute',left:25,top:45,transform:`translateX(${-40*(1-enter(t))}px)`}}><Portrait person="ellen" disguise width={255} height={375}/><div style={{fontSize:30,marginTop:20,color:craftAccent}}>Appearance</div></div><div style={{position:'absolute',left:365,top:115,width:330,height:330,border:'2px solid #8B99A0',padding:30,boxSizing:'border-box',transform:`translateX(${40*(1-enter(t))}px)`}}><div style={{fontSize:28}}>OWNERSHIP</div><div style={{fontSize:45,marginTop:50}}>PROOF?</div><div style={{height:2,background:craftAccent,marginTop:38}}/></div><div style={{position:'absolute',left:305,top:195,fontSize:80,color:craftAccent,opacity:enter(t,.3)}}>≠</div><div style={{position:'absolute',left:30,top:540,fontSize:32}}>The disguise could not supply it.</div></>}
 {index===7&&<><div style={{position:'absolute',left:40,top:30,width:640}}>{[['Prior train journey','Conductor’s confirmation',1.2],['Departure approaching','Prior travel ≠ ownership proof',4.5],['Passage allowed','Apparent illness cited',6]].map(([a,b,start],i)=><div key={a} style={{opacity:enter(t,Number(start)),transform:`translateY(${(1-enter(t,Number(start)))*25}px)`,padding:'20px 25px',marginBottom:12,borderLeft:`3px solid ${craftAccent}`,background:i===2?'#253941':'transparent'}}><div style={{fontSize:36,fontWeight:600}}>{a}</div><div style={{fontSize:27,color:'#C1CDCD',marginTop:12}}>{b}</div></div>)}</div><svg width="670" height="70" style={{position:'absolute',left:25,top:570}}><path d="M20 30H640" stroke={craftAccent} strokeWidth="5" pathLength="1" strokeDasharray="1" strokeDashoffset={1-enter(t,6,1.5)}/><path d="M620 15L640 30L620 45" fill="none" stroke={craftAccent} strokeWidth="5" opacity={enter(t,6,1.5)}/></svg></>}
 {index===8&&(t<3.7?<><Route progress={1}/><div style={{position:'absolute',left:35,top:570,fontSize:35,color:craftAccent}}>Philadelphia • four days</div></>:<><div style={{position:'absolute',left:30,top:25,width:280,height:410,overflow:'hidden',transform:`rotate(${-3+p*2}deg)`}}><Img src={recaptureReport} style={{width:300,position:'absolute',top:0,left:-10}}/></div><div style={{position:'absolute',left:370,top:55,width:330}}><div style={{fontSize:43,fontWeight:600}}>BOSTON</div><div style={{fontSize:30,color:craftAccent,marginTop:18}}>1850 • recapture threat</div><svg width="300" height="125" style={{marginTop:20}}><path d="M40 0V100L30 85M40 100L50 85" fill="none" stroke={craftAccent} strokeWidth="3" pathLength="1" strokeDasharray="1" strokeDashoffset={1-enter(t,7,1)}/></svg><div style={{fontSize:43,fontWeight:600,opacity:enter(t,9.54)}}>ENGLAND</div><div style={{fontSize:28,marginTop:18,opacity:enter(t,9.54)}}>They left for England.</div></div><div style={{position:'absolute',left:30,top:530,fontSize:28,color:'#C1CDCD'}}>The Liberator • November 1850</div></>)}
 {index===9&&<><div style={{position:'absolute',left:30,top:30,transform:`translateX(${(1-enter(t))*(-30)}px)`}}><Portrait person="ellen" width={305} height={400}/><div style={{fontSize:32,marginTop:22}}>ELLEN CRAFT</div></div><div style={{position:'absolute',left:395,top:30,transform:`translateX(${(1-enter(t))*30}px)`}}><Portrait person="william" width={305} height={400}/><div style={{fontSize:32,marginTop:22}}>WILLIAM CRAFT</div></div><div style={{position:'absolute',left:30,top:530,width:665,fontSize:43,fontWeight:600,color:craftAccent,textAlign:'center',opacity:enter(t,2)}}>They escaped together.</div><svg width="660" height="50" style={{position:'absolute',left:30,top:475}}><path d="M0 25H660" stroke={craftAccent} strokeWidth="2" pathLength="1" strokeDasharray="1" strokeDashoffset={1-enter(t,2,1)}/></svg></>}
 </div>
 <div data-disclosure data-critical="disclosure" style={{position:'absolute',left:125,top:1225,width:730,fontSize:27,lineHeight:1.35,color:dark?'#C1CDCD':craftInk}}>{disclosure}</div>
 </>;
};
