import {Img,staticFile} from 'remotion';
const ink='#262725',red='#833B39',paper='#F3F1EA';
const PairPortrait=({person,width=290,height=360}:{person:'ellen'|'william';width?:number;height?:number})=> <div style={{width,height,overflow:'hidden',position:'relative'}}><Img src={staticFile('visuals/craft-escape/craft-portraits.jpg')} style={{position:'absolute',width:width*2.3,maxWidth:'none',left:-width*.54,top:person==='william'?-height*.4:-height*1.45,filter:'grayscale(1)',mixBlendMode:'multiply'}}/></div>;
const EllenDisguise=({width=350,height=650}:{width?:number;height?:number})=><div style={{width,height,overflow:'hidden',position:'relative'}}><Img src={staticFile('visuals/craft-escape/ellen-frontispiece.jpg')} style={{position:'absolute',width:width*1.5,maxWidth:'none',left:-width*.26,top:-height*.18,filter:'grayscale(1)',mixBlendMode:'multiply'}}/></div>;
const Name=({children}:{children:React.ReactNode})=><div style={{fontSize:30,fontWeight:600,letterSpacing:1,marginTop:18}}>{children}</div>;
const Label=({children}:{children:React.ReactNode})=><div style={{fontSize:28,lineHeight:1.4,color:red,marginTop:14}}>{children}</div>;
const fade=(p:number)=>Math.min(1,p*7);
export const CraftDocumentary=({index,p,localSeconds}:{index:number;p:number;localSeconds:number})=>{
 const title=['An escape\nin plain sight','The roles\nthey assumed','A name\non a register','An apparent\ninjury','Illness had\na purpose','A plan\nsustained together','Appearance\nwas not enough','Baltimore:\nthe ownership test','Appearance\n≠ proof','Allowed\nto continue','Arrival\nwas not safety','The danger\nfollowed them','A system’s\nassumptions','Ellen and\nWilliam Craft'][index]!;
 const source=index===3?'Signature strategy reported in January 1849':index===4?'Disguise explained in their 1860 account':index>=6&&index<=9?'Baltimore sequence: their later 1860 account':index===11?'Recapture attempt reported in November 1850':index===0||index===13?'Later portraits • published in 1872':index===1?'Later disguise portrait • published in 1860':'Original explanatory graphics + later portraits';
 return <>
 <div data-critical="title" style={{position:'absolute',left:125,top:345,width:730,fontSize:62,lineHeight:1.13,fontWeight:600,letterSpacing:-2,whiteSpace:'pre-line'}}>{title}</div>
 <div data-critical="scene" style={{position:'absolute',left:125,top:540,width:730,height:655,color:ink}}>
 {(index===0||index===13)&&<div style={{display:'flex',gap:60,alignItems:'flex-start',paddingTop:20,transform:`translateY(${(1-fade(p))*12}px)`}}>{(['ellen','william'] as const).map(person=><div key={person}><PairPortrait person={person} width={310} height={420}/><Name>{person==='ellen'?'ELLEN':'WILLIAM'}</Name><Label>{index===0?'Enslaved in Georgia':'Self-emancipated'}</Label></div>)}</div>}
 {index===1&&<div style={{display:'flex',gap:30}}><div><EllenDisguise width={380} height={490}/><Name>ELLEN</Name><Label>Posing as a slaveholder</Label></div><div style={{paddingTop:90,opacity:localSeconds>=3?1:.18}}><PairPortrait person="william" width={265} height={320}/><Name>WILLIAM</Name><Label>Posing as her servant</Label></div></div>}
 {(index===2||index===3)&&<><svg viewBox="0 0 730 530" width="730" height="530" style={{position:'absolute',top:35,opacity:index===3?.17:1}}><rect x="20" y="10" width="640" height="440" fill="#FAF9F5" stroke="#B0ABA0" strokeWidth="2"/><text x="65" y="88" fontSize="25" fill="#76756D">EXPLANATORY REGISTER</text><path d="M60 120H620 M360 120V425" stroke="#C9C5BB" strokeWidth="2"/><text x="66" y="170" fontSize="31" fill={ink}>NAME</text><text x="395" y="170" fontSize="31" fill={ink}>SIGNATURE</text>{[225,300,375].map(y=><path key={y} d={`M60 ${y}H620`} stroke="#C9C5BB" strokeWidth="2"/>)}</svg>{index===2&&localSeconds>=5.68&&<div style={{position:'absolute',left:58,top:330,color:red,fontSize:42,fontWeight:600}}>She could not write.</div>}{index===3&&<><svg viewBox="0 0 730 530" width="730" height="530" style={{position:'absolute',top:40}}><path d="M70 440L240 290 Q244 224 291 176 L342 138 Q370 124 376 154 L359 181 Q414 137 448 149 Q469 162 455 183 Q492 165 510 184 Q530 205 510 230 Q545 221 552 251 Q557 278 530 304 L421 388 Q378 420 315 419 L190 512" fill={paper} stroke={ink} strokeWidth="5"/><path d="M215 324L336 438L433 357L302 222Z" fill="#FAF9F5" stroke="#96958D" strokeWidth="4"/>{[0,1,2,3].map(n=><path key={n} d={`M${229+n*20} ${311-n*17}L${355+n*20} ${421-n*17}`} stroke="#C7C3B9" strokeWidth="3"/>)}<path d="M480 202L424 246 M505 238L447 282 M518 279L469 321" stroke={ink} strokeWidth="3"/><text x="445" y="464" fill={red} fontSize="29">RIGHT HAND</text></svg><div style={{position:'absolute',top:555,left:24,fontSize:32,color:red}}>Apparent injury → excuse not to sign</div></>}</>}
 {index===4&&<div style={{display:'flex',gap:35}}><div><EllenDisguise width={320} height={540}/></div><div style={{width:350,paddingTop:30}}><Label>THEIR LATER ACCOUNT</Label><div style={{fontSize:35,lineHeight:1.35,marginTop:45}}>{localSeconds>=2.4&&<>Bandage<br/><span style={{fontSize:26,color:'#6B6C65'}}>concealed beardless chin</span><br/><br/></>}{localSeconds>=4.64&&<>Spectacles<br/><span style={{fontSize:26,color:'#6B6C65'}}>obscured her face</span><br/><br/></>}{localSeconds>=6.68&&<>Apparent illness<br/><span style={{fontSize:26,color:'#6B6C65'}}>excused conversation</span></>}</div></div></div>}
 {index===5&&<div style={{display:'flex',gap:55,paddingTop:20}}><div><PairPortrait person="william" width={300} height={405}/><Name>WILLIAM</Name><Label>Active partner in the plan</Label></div><div style={{paddingTop:80,width:330}}><EllenDisguise width={290} height={430}/></div></div>}
 {(index===6||index===10||index===11)&&<><div style={{position:'absolute',left:85,top:30,borderLeft:'2px solid #A19E94',height:560}}/>{(index===11?['BOSTON','ENGLAND']:['GEORGIA','BALTIMORE','PHILADELPHIA']).map((s,i)=><div key={s} style={{position:'absolute',left:60,top:45+i*(index===11?260:210),display:'flex',alignItems:'center',gap:38}}><div style={{width:52,height:52,borderRadius:'50%',background:s==='BALTIMORE'&&index===6?red:ink,border:`8px solid ${paper}`,boxSizing:'border-box'}}/><div><div style={{fontSize:38,fontWeight:600}}>{s}</div><Label>{index===11?(i===0?'1850 • threatened with recapture':'They left for England'):i===0?'Enslaved and seeking escape':i===1?(index===6?'Ownership assurance demanded':'Before Philadelphia'):index===10?'Arrived after four days':'Their destination'}</Label></div></div>)}<div style={{position:'absolute',left:130,top:602,fontSize:26,color:'#6B6C65'}}>Route sequence • distances not to scale</div></>}
 {(index===7||index===8)&&<><div style={{padding:'45px 35px',borderTop:`2px solid ${ink}`,borderBottom:`2px solid ${ink}`,marginTop:40}}><div style={{fontSize:26,letterSpacing:2,color:red,marginBottom:36}}>THE QUESTION OFFICIALS ASKED</div><div style={{fontSize:49,lineHeight:1.3}}>Did the supposed master<br/>have the right to take<br/>William onward?</div><div style={{fontSize:28,color:'#6B6C65',marginTop:40}}>Paraphrase of their later account</div></div>{index===8&&<div style={{fontSize:36,marginTop:50,color:red}}>An assumed identity<br/>could not supply that proof.</div>}</>}
 {index===9&&<div style={{paddingTop:25}}><div style={{fontSize:28,color:red}}>WILLIAM’S 1860 ACCOUNT</div>{['Conductor confirms prior travel','Departure approaches','Officer allows passage'].map((s,i)=><div key={s} style={{borderBottom:'1px solid #C5C0B5',padding:'35px 0',opacity:localSeconds>=[0,4.5,6.7][i]!?1:.18}}><div style={{fontSize:36,fontWeight:600}}>{s}</div>{i===2&&<Label>The apparent master’s illness is cited.</Label>}</div>)}<div style={{fontSize:28,color:'#6B6C65',marginTop:42}}>Discretionary passage.<br/>No proof of ownership supplied.</div></div>}
 {index===12&&<div style={{display:'flex',gap:34,paddingTop:20}}><EllenDisguise width={320} height={510}/><div style={{paddingTop:60,width:370}}><div style={{fontSize:28,color:red}}>A SUPPOSED WHITE GENTLEMAN</div><div style={{fontSize:37,lineHeight:1.35,marginTop:40}}>The presentation<br/>shaped how others<br/>treated them.</div><div style={{fontSize:32,lineHeight:1.4,marginTop:70}}>Their real relationship<br/>remained hidden.</div></div></div>}
 </div>
 <div data-disclosure data-critical="disclosure" style={{position:'absolute',left:125,top:1225,width:730,fontSize:27,lineHeight:1.35,color:'#62655E'}}>{source}{index===4&&<><br/>Portrait omits the facial bandage.</>}{index===1&&<><br/>Portraits are not images of the escape itself.</>}</div>
 </>;
};
