import {Img,staticFile} from 'remotion';
import earlyReport from '../../content-intelligence/cycles/cycle-10/research/singular-escape-inspected.png';
import recaptureReport from '../../content-intelligence/cycles/cycle-10/research/slave-hunters-inspected.png';
export const craftInk='#17232A',craftPaper='#EFE9DD',craftAccent='#E6B482';
const clamp=(v:number)=>Math.max(0,Math.min(1,v));
const enter=(t:number,start=0,length=.45)=>{const x=clamp((t-start)/length);return 1-(1-x)**3;};
const Portrait=({person,width=290,height=380,disguise=false}:{person:'ellen'|'william';width?:number;height?:number;disguise?:boolean})=><div style={{width,height,overflow:'hidden',position:'relative',background:craftPaper}}><Img src={staticFile(`visuals/craft-escape/${disguise?'ellen-frontispiece.jpg':'craft-portraits.jpg'}`)} style={{position:'absolute',width:width*(disguise?1.5:2.3),maxWidth:'none',left:-width*(disguise?.26:.54),top:disguise?-height*.18:person==='william'?-height*.4:-height*1.45,filter:'grayscale(1)',mixBlendMode:'multiply'}}/></div>;
const Hand=({t}:{t:number})=><svg width="700" height="530" viewBox="0 0 730 530" style={{position:'absolute',left:15,top:80,transform:`translateX(${(1-enter(t))*180}px)`}}><path d="M70 440L240 290 Q244 224 291 176 L342 138 Q370 124 376 154 L359 181 Q414 137 448 149 Q469 162 455 183 Q492 165 510 184 Q530 205 510 230 Q545 221 552 251 Q557 278 530 304 L421 388 Q378 420 315 419 L190 512" fill={craftPaper} stroke={craftInk} strokeWidth="5"/><path d="M215 324L336 438L433 357L302 222Z" fill="#FFFAEF" stroke="#8D8374" strokeWidth="4" opacity={enter(t,.4,.6)}/>{[0,1,2,3].map(n=><path key={n} d={`M${229+n*20} ${311-n*17}L${355+n*20} ${421-n*17}`} stroke="#B9AE9F" strokeWidth="3" pathLength="1" strokeDasharray="1" strokeDashoffset={1-enter(t,.6+n*.18,.4)}/>)}</svg>;
const Signature=({index,t}:{index:number;t:number})=>{
 const second=index===2,u=index===1?t:t+227/30,change=enter(u,3.85,.65),hand=second?enter(t,0,.65):0;
 return <>
 <div style={{opacity:1-change,transform:`scale(${1-.12*change})`,transformOrigin:'center',position:'absolute',width:730}}><Route progress={clamp(u/3.6)} stop/></div>
 <div style={{position:'absolute',left:20,top:45,width:680,height:480,background:'#FBF7EE',color:craftInk,padding:38,boxSizing:'border-box',opacity:change,transform:`translateX(${(1-change)*170}px)`,boxShadow:'0 15px 45px #0002'}}>
 <div style={{fontSize:25,color:'#765B47'}}>EXPLANATORY RECONSTRUCTION</div>
 <div style={{fontSize:43,fontWeight:600,marginTop:30}}>PASSENGER REGISTER</div>
 <div style={{height:2,background:'#9F978A',marginTop:20}}/>
 <div style={{fontSize:42,marginTop:45,opacity:1-hand*.75}}>SIGNATURE</div>
 <svg width="590" height="85" style={{marginTop:10}}><path d="M0 50H590" fill="none" stroke="#A04D3B" strokeWidth="5" pathLength="1" strokeDasharray="1" strokeDashoffset={1-enter(u,4.15,1.1)}/></svg>
 <div style={{fontSize:46,fontWeight:600,opacity:1-hand,marginTop:12}}>She could not write.</div>
 </div>
 {second&&<><div style={{position:'absolute',left:15,top:-35,opacity:hand,transform:`translateY(${(1-hand)*45}px)`}}><Hand t={t}/></div><div style={{position:'absolute',left:30,top:545,fontSize:44,fontWeight:600,color:craftInk,opacity:enter(t,.8)}}>An excuse not to sign.</div>
 <div style={{position:'absolute',left:465,top:15,width:230,height:260,overflow:'hidden',opacity:enter(t,3.3),transform:`translateY(${(1-enter(t,3.3))*50}px) rotate(3deg)`,border:'4px solid #C7B59D',boxSizing:'border-box'}}><Img src={earlyReport} style={{width:235,position:'absolute',left:-3,top:-8}}/></div><div style={{position:'absolute',left:480,top:295,fontSize:26,color:craftInk,opacity:enter(t,3.3)}}>January 1849 report</div></>}
 {!second&&<div style={{position:'absolute',left:30,top:565,fontSize:43,fontWeight:600,color:craftAccent,opacity:enter(u,5.5)}}>What if she had to sign?</div>}
 </>;
};
const Checkpoint=({index,t}:{index:number;t:number})=>{
 const u=t+(index===5?0:index===6?332/30:417/30),identity=enter(u,2.5,.8),release=enter(u,19.9,1.3),demand=enter(u,3.1,.9),proof=enter(u,332/30,.45),confirmation=enter(u,417/30+1.2,.55),departure=enter(u,417/30+4.38,.55);
 return <>
 <div style={{opacity:1-identity,transform:`scale(${1-identity*.08})`,transformOrigin:'65% 10%',position:'absolute'}}><Route progress={1} stop/></div>
 <div style={{position:'absolute',left:25,top:0,width:680,opacity:identity,transform:`translateY(${(1-identity)*30}px)`}}>
 <div style={{position:'absolute',left:20,top:10,width:280}}><Portrait person="ellen" disguise width={180} height={220}/><div style={{fontSize:32,marginTop:8}}>ELLEN CRAFT</div><div style={{fontSize:32,color:craftAccent,marginTop:5}}>Apparent master</div></div>
 <div style={{position:'absolute',left:425,top:10,width:280}}><Portrait person="william" width={180} height={220}/><div style={{fontSize:32,marginTop:8}}>WILLIAM CRAFT</div><div style={{fontSize:32,color:craftAccent,marginTop:5}}>Apparent servant</div></div>
 <div style={{position:'absolute',left:245,top:70,width:170,fontSize:27,lineHeight:1.3,color:'#C1CDCD',textAlign:'center'}}>EXPLANATORY<br/>DIAGRAM</div>
 <div style={{position:'absolute',left:20,top:365,fontSize:42,fontWeight:600,opacity:enter(u,7,.7)*(1-enter(u,19.65,.25))}}>Right to take William onward?</div>
 <svg style={{position:'absolute',left:10,top:415}} width="650" height="85"><path d="M10 45H620" stroke="#596872" fill="none" strokeWidth="4"/><path d="M10 45H300" fill="none" stroke={craftAccent} strokeWidth="6" pathLength="1" strokeDasharray="1" strokeDashoffset={1-enter(u,3.1,3.5)}/><path d="M320 10V80" fill="none" stroke="#E1AD84" strokeWidth="6" opacity={enter(u,5.8,.65)*(1-release)}/><path d="M300 45H620L600 30M620 45L600 60" fill="none" stroke={craftAccent} strokeWidth="6" pathLength="1" strokeDasharray="1" strokeDashoffset={1-release}/></svg>
 <div style={{position:'absolute',left:20,top:510,width:635,fontSize:46,fontWeight:600,lineHeight:1.2,opacity:demand*(1-enter(u,14.8,.25))}}>{proof>.5?'Appearance ≠ proof':'Ownership assurance?'}</div>
 <div style={{position:'absolute',left:20,top:505,width:635,opacity:confirmation*(1-enter(u,19.65,.25))}}><div style={{fontSize:42,fontWeight:600}}>Prior journey confirmed</div><div style={{fontSize:34,color:'#C1CDCD',marginTop:15}}>{departure>.5?'Departure approaching':'Prior travel ≠ ownership proof'}</div></div>
 <div style={{position:'absolute',left:20,top:365,width:635,opacity:release,fontSize:48,fontWeight:600,color:craftAccent}}>Passage allowed</div>
 <div style={{position:'absolute',left:20,top:510,width:635,opacity:release}}><div style={{fontSize:42,fontWeight:600}}>Apparent illness cited</div><div style={{fontSize:34,color:'#C1CDCD',marginTop:15}}>Discretion, not ownership proof</div></div>
 </div>
 </>;
};
const cities=[{name:'Macon',x:100,y:495},{name:'Savannah',x:255,y:475},{name:'Charleston',x:380,y:400},{name:'Wilmington',x:420,y:320},{name:'Richmond',x:300,y:235},{name:'Fredericksburg',x:375,y:180},{name:'Washington',x:445,y:130},{name:'Baltimore',x:480,y:80},{name:'Philadelphia',x:540,y:25}];
const Route=({progress,stop=false}:{progress:number;stop?:boolean})=>{
 const max=stop?7:8,amount=clamp(progress)*max,points=cities.map(c=>`${c.x},${c.y}`).join(' ');
 return <svg viewBox="0 -25 730 620" width="730" height="620"><path d="M40 530 Q190 510 290 475 Q435 405 445 300 Q480 205 515 165 Q555 115 590 25L665 -20" fill="none" stroke="#596872" strokeWidth="2" opacity=".6"/><text x="485" y="435" fontSize="24" fill="#8EAAA9" transform="rotate(-55 485 435)">SCHEMATIC • NOT A MAP</text><polyline points={points} stroke="#53626A" strokeWidth="3" fill="none"/>{cities.slice(0,max).map((c,i)=>{const b=cities[i+1]!;return <path key={c.name} d={`M${c.x} ${c.y}L${b.x} ${b.y}`} fill="none" stroke={craftAccent} strokeWidth="5" pathLength="1" strokeDasharray="1" strokeDashoffset={1-clamp(amount-i)}/>;})}{cities.map((c,i)=><g key={c.name} opacity={i<=amount+.15?1:.35}><circle cx={c.x} cy={c.y} r={c.name==='Baltimore'?9:6} fill={i<=amount?craftAccent:'#53626A'}/><text x={c.x-15} y={c.y-20} textAnchor="end" fontSize="27" fill={craftPaper}>{c.name}</text></g>)}{stop&&amount>=7&&<circle cx="480" cy="80" r="24" fill="none" stroke={craftAccent} strokeWidth="3"/>}</svg>;
};
const StageHeading=({children,dark=true}:{children:React.ReactNode;dark?:boolean})=><div data-critical="title" style={{position:'absolute',left:125,top:340,width:730,color:dark?craftPaper:craftInk,fontSize:58,fontWeight:600,lineHeight:1.1,whiteSpace:'pre-line'}}>{children}</div>;
export const CraftDocumentTheatreV3=({index,t,duration}:{index:number;t:number;duration:number})=>{
 const dark=[0,1,5,6,7,8,9].includes(index),ink=dark?craftPaper:craftInk,p=clamp(t/duration);
 const disclosure=['Later portraits • 1860 / 1872','Route sequence is schematic • not a map','Injury graphic / register are explanatory','Their 1860 account • portrait omits facial bandage','Later portraits • William helped sustain the disguise','Baltimore: later 1860 participant account','Ownership question: paraphrase of their account','Release: William’s later 1860 account','Arrival ≠ lasting safety • 1850 recapture report','Later portraits • Ellen and William Craft'][index]!;
 return <>
 <div style={{position:'absolute',top:300,left:0,width:1080,height:1015,background:dark?craftInk:craftPaper}}/>
 <StageHeading dark={dark}>{['Escape as\nthe slaveholder.','Open travel.\nA new vulnerability.','An excuse\nnot to sign.','Illness was part\nof the strategy.','A disguise sustained\nby two people.','Baltimore.\nCould they go onward?','Appearance\nwas not proof.','Passage allowed.\nNot guaranteed.','Four days to arrive.\nMore danger ahead.','Their roles were false.\nTheir ingenuity was real.'][index]}</StageHeading>
 <div data-critical="scene" style={{position:'absolute',left:125,top:530,width:730,height:660,color:ink,overflow:'hidden'}}>
 {index===0&&<><div style={{position:'absolute',left:45,top:25,transform:`translateX(${(1-enter(t))*(-30)}px)`}}><Portrait person="ellen" disguise width={320} height={420}/><div style={{fontSize:36,marginTop:18}}>ELLEN CRAFT</div><div style={{fontSize:40,color:craftAccent,marginTop:12}}>Apparent master</div></div><div style={{position:'absolute',left:390,top:90,transform:`translateX(${(1-enter(t,2.7))*30}px)`,opacity:.35+.65*enter(t,2.7)}}><Portrait person="william" width={280} height={350}/><div style={{fontSize:36,marginTop:18}}>WILLIAM CRAFT</div><div style={{fontSize:38,color:craftAccent,marginTop:12}}>Apparent servant</div></div><svg style={{position:'absolute',top:570,left:40}} width="620" height="65"><path d="M0 28H620" stroke={craftAccent} strokeWidth="2"/><text x="310" y="61" textAnchor="middle" fill={craftPaper} fontSize="28">Their imposed relationship, inverted</text></svg></>}
 {(index===1||index===2)&&<Signature index={index} t={t}/>}
 {index===3&&<><div style={{position:'absolute',left:-10+enter(t)*20,top:15,transform:`scale(${1.02+p*.04})`,transformOrigin:'left top'}}><Portrait person="ellen" disguise width={330} height={540}/></div><div style={{position:'absolute',left:355,top:30,width:350}}>{[['Bandage','Concealed beardless chin',2.4],['Spectacles','Obscured her face',4.4],['Apparent illness','Excused conversation',6.8]].map(([a,b,start])=><div key={a} style={{opacity:enter(t,Number(start)),transform:`translateX(${(1-enter(t,Number(start)))*20}px)`,marginBottom:30}}><div style={{fontSize:42,fontWeight:600}}>{a}</div><div style={{fontSize:36,lineHeight:1.3,marginTop:12}}>{b}</div><div style={{height:2,background:'#A99177',marginTop:22,width:280*enter(t,Number(start),.7)}}/></div>)}</div></>}
 {index===4&&<><div style={{position:'absolute',left:25,top:15,transform:`translateX(${(1-enter(t))*-50}px)`}}><Portrait person="william" width={330} height={425}/><div style={{fontSize:38,marginTop:20}}>WILLIAM CRAFT</div></div><div style={{position:'absolute',left:425,top:80,transform:`translateX(${(1-enter(t))*(50)}px)`}}><Portrait person="ellen" disguise width={230} height={370}/></div><svg width="700" height="120" style={{position:'absolute',top:525}}><path d="M70 30H630" stroke="#9C6C49" strokeWidth="3" pathLength="1" strokeDasharray="1" strokeDashoffset={1-enter(t,.4,1)}/><text x="350" y="86" textAnchor="middle" fill={craftInk} fontSize="34">Active partners in the plan</text></svg></>}
 {[5,6,7].includes(index)&&<Checkpoint index={index} t={t}/>}
 {index===8&&(t<3.7?<><Route progress={1}/><div style={{position:'absolute',left:35,top:570,fontSize:35,color:craftAccent}}>Philadelphia • four days</div></>:<><div style={{position:'absolute',left:30,top:25,width:280,height:410,overflow:'hidden',transform:`rotate(${-3+p*2}deg)`}}><Img src={recaptureReport} style={{width:300,position:'absolute',top:0,left:-10}}/></div><div style={{position:'absolute',left:370,top:55,width:330}}><div style={{fontSize:43,fontWeight:600}}>BOSTON</div><div style={{fontSize:36,color:craftAccent,marginTop:18}}>1850 • recapture threat</div><svg width="300" height="125" style={{marginTop:20}}><path d="M40 0V100L30 85M40 100L50 85" fill="none" stroke={craftAccent} strokeWidth="3" pathLength="1" strokeDasharray="1" strokeDashoffset={1-enter(t,7,1)}/></svg><div style={{fontSize:43,fontWeight:600,opacity:enter(t,9.54)}}>ENGLAND</div><div style={{fontSize:28,marginTop:18,opacity:enter(t,9.54)}}>They left for England.</div></div><div style={{position:'absolute',left:30,top:530,fontSize:28,color:'#C1CDCD'}}>The Liberator • November 1850</div></>)}
 {index===9&&<><div style={{position:'absolute',left:30,top:30,transform:`translateX(${(1-enter(t))*(-30)}px)`}}><Portrait person="ellen" width={305} height={400}/><div style={{fontSize:38,marginTop:22}}>ELLEN CRAFT</div></div><div style={{position:'absolute',left:395,top:30,transform:`translateX(${(1-enter(t))*30}px)`}}><Portrait person="william" width={305} height={400}/><div style={{fontSize:38,marginTop:22}}>WILLIAM CRAFT</div></div><div style={{position:'absolute',left:30,top:530,width:665,fontSize:43,fontWeight:600,color:craftAccent,textAlign:'center',opacity:enter(t,2)}}>They escaped together.</div><svg width="660" height="50" style={{position:'absolute',left:30,top:475}}><path d="M0 25H660" stroke={craftAccent} strokeWidth="2" pathLength="1" strokeDasharray="1" strokeDashoffset={1-enter(t,2,1)}/></svg></>}
 </div>
 <div data-disclosure data-critical="disclosure" style={{position:'absolute',left:125,top:1225,width:730,fontSize:36,lineHeight:1.35,color:dark?'#C1CDCD':craftInk}}>{disclosure}</div>
 </>;
};
