import {Img,staticFile} from 'remotion';
import {PaintLayerModel,clampProgress,reveal} from './PaintLayerModel';
export const investigationInk='#222325',investigationPaper='#F1EBDF',investigationAccent='#DBA079';
const headings=['Prove it is fake.','A supposed Vermeer.\nA Nazi buyer.','A confession.\nBut was it true?','The masterpiece\nexperts expected.','Make new paint\nlook old.','Test the materials.','Look beneath\nthe surface.','Old canvas.\nNew painting.','A different crime.\nStill guilty.','The painting remained.\nThe attribution did not.'];
const disclosures=['Archival photo • court appearance, 29 Oct 1947','Modern explanatory summary • intermediary sale','Defense claim distinguished from independent proof','Emmaus, 1937 • not the painting sold to Göring','Original explanatory model • not historic footage','Court-examiner report, 1949 • schematic comparison','Original explanatory model • not an actual X-ray','Original explanatory model • not a measured section','1947 court photograph • conviction 12 Nov 1947','Emmaus • Han van Meegeren • archival reproduction'];
const Art=({t,width=700,height=510}:{t:number;width?:number;height?:number})=><div style={{width,height,overflow:'hidden',border:'2px solid #8D7D66',boxSizing:'border-box',position:'relative'}}><Img src={staticFile('visuals/vermeer-forgery/emmaus.jpg')} style={{width:'100%',height:'100%',objectFit:'cover',transform:`scale(${1+clampProgress(t/14)*.045})`}}/></div>;
const Label=({children,y=0,color=investigationPaper,size=36}:{children:React.ReactNode;y?:number;color?:string;size?:number})=><div style={{position:'absolute',left:35,top:y,fontSize:size,lineHeight:1.2,color}}>{children}</div>;
export const VermeerInvestigation=({index,t,duration}:{index:number;t:number;duration:number})=>{
 const p=clampProgress(t/duration);
 return <>
 <div data-critical="title" style={{position:'absolute',left:125,top:335,width:730,fontSize:58,fontWeight:600,lineHeight:1.1,whiteSpace:'pre-line'}}>{headings[index]}</div>
 <div data-critical="scene" style={{position:'absolute',left:125,top:530,width:730,height:660,overflow:'hidden'}}>
 {index===0&&<><div style={{position:'absolute',left:20,top:10,width:475,height:585,overflow:'hidden'}}><Img src={staticFile('visuals/vermeer-forgery/court.jpg')} style={{width:475,transform:`scale(${1.05+p*.06})`,transformOrigin:'50% 65%'}}/></div><div style={{position:'absolute',left:375,top:380,width:345,padding:'28px 20px',boxSizing:'border-box',background:investigationPaper,color:investigationInk,transform:`translateY(${(1-reveal(t,.2))*60}px)`}}><div style={{fontSize:29}}>HAN VAN MEEGEREN</div><div style={{fontSize:53,fontWeight:600,marginTop:15}}>FORGER?</div></div></>}
 {index===1&&<><div style={{background:investigationPaper,color:investigationInk,padding:'32px 35px',margin:'15px 20px',height:180,boxSizing:'border-box',transform:`translateY(${(1-reveal(t))*35}px)`}}><div style={{fontSize:29}}>1945 • POSTWAR INVESTIGATION</div><div style={{fontSize:43,fontWeight:600,marginTop:30}}>Suspicion of collaboration</div></div><svg width="730" height="270" style={{position:'absolute',top:230}}><path d="M90 25H620" fill="none" stroke={investigationAccent} strokeWidth="4" pathLength="1" strokeDasharray="1" strokeDashoffset={1-reveal(t,5,.8)}/><path d="M605 10L620 25L605 40" fill="none" stroke={investigationAccent} strokeWidth="4" opacity={reveal(t,5,.8)}/><text x="30" y="90" fill={investigationPaper} fontSize="34">Art dealer</text><text x="385" y="90" fill={investigationPaper} fontSize="34">Hermann Göring</text><text x="385" y="138" fill={investigationAccent} fontSize="31">Nazi leader</text></svg><Label y={475} size={35}>Christ with the Adulteress</Label><Label y={540} size={30} color="#C6C3BC">Sold as a Vermeer</Label></>}
 {index===2&&<><div style={{position:'absolute',left:35,top:25,width:650,height:235,background:investigationPaper,color:investigationInk,padding:35,boxSizing:'border-box',transform:`translateX(${(1-reveal(t))*60}px)`}}><div style={{fontSize:29}}>DEFENSE CLAIM • PARAPHRASE</div><div style={{fontSize:54,fontWeight:600,marginTop:35}}>He painted it himself.</div></div><svg width="730" height="150" style={{position:'absolute',top:270}}><path d="M360 0V105M345 90L360 105L375 90" fill="none" stroke={investigationAccent} strokeWidth="3" pathLength="1" strokeDasharray="1" strokeDashoffset={1-reveal(t,3.1,.8)}/></svg><Label y={430} size={47}>Claim ≠ proof</Label><Label y={515} size={32} color="#C6C3BC">Some experts resisted the confession.</Label></>}
 {index===3&&<>{t<3.44?<><div style={{position:'absolute',left:35,top:25,width:645,height:390,border:'3px solid #8E8272'}}><div style={{fontSize:45,textAlign:'center',marginTop:105}}>VERMEER’S EARLY WORK</div><div style={{fontSize:92,textAlign:'center',color:investigationAccent,marginTop:25}}>?</div></div><Label y={475} size={38}>A gap in what was known</Label></>:<><div style={{position:'absolute',left:15,top:10,transform:`translateY(${(1-reveal(t,3.44))*(60)}px)`}}><Art t={t} width={700} height={440}/></div><Label y={480} size={32}>The Supper at Emmaus • van Meegeren</Label><Label y={540} size={33} color={investigationAccent}>{t<7.36?'Accepted as an early Vermeer':'Expert endorsement → museum acquisition'}</Label></>}</>}
 {index===4&&<PaintLayerModel t={t} mode="manufacture"/>}
 {index===5&&<><Label y={20} size={32} color="#C6C3BC">Combined material tests</Label>{[{x:45,name:'PAINT SAMPLE',color:'#D8C7A6'},{x:390,name:'STUDIO MATERIAL',color:'#D8C7A6'}].map((sample,i)=><div key={sample.name} style={{position:'absolute',left:sample.x,top:100,width:290,height:300,transform:`translateX(${(1-reveal(t,1+i*.4))*(i?-70:70)}px)`,opacity:reveal(t,1+i*.4)}}><div style={{height:210,border:'2px solid #777875',display:'flex',alignItems:'center',justifyContent:'center'}}><svg width="200" height="170"><path d={i?'M30 120L60 35L130 15L165 75L135 140L75 155Z':'M40 145L25 60L105 25L170 45L150 125L110 155Z'} fill={sample.color}/><path d="M55 70L125 55L145 100L100 130" fill="none" stroke="#92795C" strokeWidth="3"/></svg></div><div style={{fontSize:28,textAlign:'center',marginTop:25}}>{sample.name}</div></div>)}<svg width="730" height="90" style={{position:'absolute',top:440}}><path d="M80 25H645" stroke={investigationAccent} strokeWidth="3" pathLength="1" strokeDasharray="1" strokeDashoffset={1-reveal(t,4,1)}/><circle cx="365" cy="25" r="15" fill={investigationAccent} opacity={reveal(t,5,.8)}/></svg><Label y={535} size={43}>Modern synthetic resin</Label></>}
 {index===6&&<PaintLayerModel t={t} mode="networks"/>}
 {index===7&&<PaintLayerModel t={t} mode="resolve"/>}
 {index===8&&<><div style={{position:'absolute',left:20,top:10,width:330,height:470,overflow:'hidden'}}><Img src={staticFile('visuals/vermeer-forgery/court.jpg')} style={{width:330,transform:`scale(${1+p*.07})`,transformOrigin:'50% 65%'}}/></div><div style={{position:'absolute',left:375,top:40,width:330}}><div style={{fontSize:34,color:investigationAccent}}>1947 • CONVICTION</div><div style={{fontSize:46,fontWeight:600,marginTop:40,lineHeight:1.4}}>FRAUD<br/>AND FORGERY</div><div style={{height:2,background:'#8D8275',marginTop:35,transformOrigin:'left',transform:`scaleX(${reveal(t,4.1,1)})`}}/><div style={{fontSize:80,fontWeight:600,marginTop:30,opacity:reveal(t,7.1,.5)}}>1 YEAR</div></div><Label y={550} size={34}>Collaboration case ≠ fraud conviction</Label></>}
 {index===9&&<><div style={{position:'absolute',left:15,top:10}}><Art t={t} width={700} height={460}/></div><Label y={505} size={33} color="#C6C3BC">The Supper at Emmaus</Label><div style={{position:'absolute',left:35,top:560,fontSize:45,color:investigationAccent,fontWeight:600}}>Han van Meegeren</div></>}
 </div>
 <div data-disclosure data-critical="disclosure" style={{position:'absolute',left:125,top:1225,width:730,fontSize:27,lineHeight:1.35,color:'#C6C3BC'}}>{disclosures[index]}</div>
 </>;
};
