import {readFileSync,writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {openMediaCatalog} from '../src/artifacts/catalog';
import {mediaHash} from '../src/artifacts/media';
import {sha256Json} from '../src/content-intelligence/run-schema';
import {ownerDecisionSchema,readBoundRecord} from '../src/workflow/evidence';
import {inspectCycleRelease,resolveAuthorizedCycleUpload,cycleDeliverySchema} from '../src/workflow/release';
import {loadCycle,persistCycleEvent} from '../src/workflow/store';
import {nextAction} from '../src/workflow/cycle';

const root=process.cwd(),base='content-intelligence/cycles/cycle-9/publication',registry=openMediaCatalog(root);
const read=(path:string)=>JSON.parse(readFileSync(path,'utf8'));
const ref=(path:string)=>({path,sha256:mediaHash(path)});
const put=(name:string,value:unknown)=>{const path=`${base}/${name}.json`;writeFileSync(path,JSON.stringify(value,null,2)+'\n',{flag:'wx'});return ref(path);};
let cycle=loadCycle(root,'cycle.9',registry);
if(cycle.stage!=='publication-review'||!cycle.release||!cycle.candidate)throw new Error('Exact Cycle 9 publication review required');
const release=readBoundRecord(cycle.release),now=new Date().toISOString(),inspection=inspectCycleRelease(release,registry,now,root),risk=read(`${base}/risk-register-v1.json`);
if(risk.targetSha256!==sha256Json(release)||sha256Json(risk.requiredExactPresentationUnknowns)!==sha256Json(inspection.unknowns))throw new Error('Approved release/risk binding drift');
if(mediaHash('artifacts/masters/two-goals-cycle9-candidate-v2.mp4')!=='d9cb6ec0cbaa4e04c282f10deb782520f9eb924f4611e0b4e183ed07ba6feea3')throw new Error('Approved master drift');
const instruction=`APPROVE PUBLICATION — Cycle #9.
Ahmet authorizes the exact four-platform publication package for locked approved V2 artifacts/masters/two-goals-cycle9-candidate-v2.mp4 on YouTube Shorts, TikTok, Instagram Reels and Facebook Reels, accepting the documented presentation and operational uncertainties for manual release. Preserve exact V2 and approved platform-specific titles where supported, descriptions/captions, hashtags, tags/keywords where supported, first comments, cover/thumbnail recommendations, platform settings and AI/synthetic-content disclosure guidance.
Record authorization under authoritative V3 workflow and prepare final manual-release handoff. Print complete owner-facing upload instructions directly in response, including exact media/cover paths or fallback frame, all copy, settings and short checklist for correct account/Page, canonical V2, cover/crop, caption/title, disclosure, original audio and burned-in captions, no added music/effects/text/enhancement/trimming, quality and visibility/schedule, preview check for caption duplication and native UI obstruction. Do not modify V2 or create V3.
Do not upload, schedule or publish; do not infer publication from authorization; do not start Cycle #10. Stop and report Cycle9 state, journal revision, exact authorized master, validation, commit/state and remaining unknowns. End exactly AHMET — CYCLE #9 MANUAL RELEASE. Record-entry time is not a supplied owner-review time.`;
const decision=put('owner-publication-decision-v1',ownerDecisionSchema.parse({schemaVersion:3,id:'owner-decision.cycle-9.publication-v1',revision:1,gate:'publication-review',cycleId:cycle.id,targetSha256:sha256Json(release),decision:'approve',enteredAt:now,suppliedReviewTime:null,reviewer:'Ahmet — owner',evidenceBasis:'explicit-owner-message',instruction,acceptedUnknowns:[...inspection.unknowns,...risk.additionalOperationalUnknowns],scope:ref(`${base}/risk-register-v1.json`)}));
put('owner-publication-decision-reference-v1',decision);
cycle=persistCycleEvent(root,cycle,{type:'owner-decision',record:decision,at:now},registry);
const uploads=resolveAuthorizedCycleUpload(release,decision,registry,root);
put('authorized-media-resolution-v1',uploads);
const bindings=inspection.release.deliveries.map(({variant,manifest})=>{const m=cycleDeliverySchema.parse(readBoundRecord(manifest));return {variantId:variant.id,platform:variant.platform,surface:variant.surface,variantSha256:sha256Json(variant),manifest,metadata:m.metadata,uploadCopy:m.uploadCopy,media:variant.media,artifacts:m.artifacts,readyFor:'owner-manual-release'};});
put('authorization-bindings-v1',{cycleId:cycle.id,recordedAt:now,sourceReviewCommit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),release:cycle.release,releaseTargetSha256:sha256Json(release),decision,riskRegister:ref(`${base}/risk-register-v1.json`),scope:'Owner manual release only; no assistant external platform action.',stage:cycle.stage,revision:cycle.revision,nextAction:nextAction(cycle),bindings,acceptedPresentationUnknowns:inspection.unknowns.length,acceptedOperationalUnknowns:risk.additionalOperationalUnknowns.length,mediaCopied:0,mediaRegenerated:0,externalPlatformActionsPerformed:[],actualScheduling:null,actualPublication:null,analytics:null});
put('publication-evidence-intake-v1',{cycleId:cycle.id,release:cycle.release,publicationDecision:decision,state:'awaiting-owner-evidence',platforms:uploads.map(u=>({platform:u.platform,variantId:u.variantId,authorizedMedia:u.files.find(f=>f.role==='video')!.media,manifestSha256:u.manifestSha256,scheduling:null,publication:null,url:null,postId:null,publishedAt:null,actualSettings:null,firstComment:{posted:null,commentId:null,postedAt:null,pinState:null},presentationObservations:null,analytics:null})),notes:'Authorization is not scheduling/publication evidence. No PublicationRecord, real-device pass or metric inferred. Later owner evidence and raw native metrics retain actual source/time/definitions.'});
const lines=['# AHMET — CYCLE #9 MANUAL RELEASE','',`Authorized at journal revision ${cycle.revision}. All ${inspection.unknowns.length} presentation and ${risk.additionalOperationalUnknowns.length} operational uncertainties accepted. Acceptance is not a device pass. Only Ahmet performs platform actions. Scheduling/publication remain unknown.`, '', 'Exact canonical V2: /Users/ahmetnishefci/Developer/Magnivis/artifacts/masters/two-goals-cycle9-candidate-v2.mp4', 'SHA-256: d9cb6ec0cbaa4e04c282f10deb782520f9eb924f4611e0b4e183ed07ba6feea3. 10,893,377 bytes; 1080×1920,30fps,H264/AAC;82.03333333333333s picture /82.091s container.','', 'Approved prepared records remain frozen; this authorization adds references, no media copies or creative changes.',''];
for(const platform of ['youtube','tiktok','instagram','facebook']){
 const m=read(`${base}/${platform}/metadata-v1.json`),u=uploads.find(x=>x.platform===platform)!;
 lines.push(`## ${platform.toUpperCase()}`,'',`Video: ${u.files.find(f=>f.role==='video')!.path}`,'');
 if(m.title)lines.push(`Title${platform==='facebook'?' (only if composer supports it)':''}: ${m.title}`,'');
 lines.push(platform==='youtube'?'Description:':'Caption:','',m.description,'',`Hashtags: ${m.hashtags.map((h:string)=>'#'+h).join(' ')}`,'',`Tags: ${m.tags.length?m.tags.join(', '):'No separate tags/keywords field assumed.'}`,'','First comment:', '',m.firstComment,'',`Cover/reference: ${u.files.find(f=>f.role==='cover')!.path}`,`Cover selection: ${m.cover.selection}`,'','Exact approved settings (recommendations, not applied):','');
 for(const [key,value] of Object.entries(m.operatorSettings))lines.push(`- ${key}: ${typeof value==='object'?JSON.stringify(value):value}`);
 lines.push('','Native-frame reference: frame1860 at62.0s of exact V2, both goals defended. Local reference: artifacts/qa-evidence/two-goals-cycle9-v2/frame-95-62.0s.png. Changing a selected custom-cover identity requires a versioned manifest; do not silently transfer authorization.','');
}
lines.push('## Final manual checklist','', '- Confirm correct Magnivis account/Page and exact V2 file/hash.','- Inspect selected cover/crop and exact title/caption/hashtags/tags.','- Enable approved synthetic-audio disclosure.','- Preserve original audio and designed captions; no added music/effects/text, crop, trim or speed changes.','- Enable highest-quality upload where offered.', '- Preview for duplicate captions and native UI obstruction; no known collision is waived.','- Confirm visibility and chosen schedule/date/time/timezone before submitting. No time is selected by this handoff.','- Record actual controls and any material collision; accepted uncertainty does not waive a known collision.','', 'After scheduling, retain receipts and intended date/time/timezone; scheduling is not publication. After publication, supply actual URLs/IDs/time, cover/disclosure/settings/comment state and presentation issues when known. Unknowns remain unknown; no Cycle10.','', 'AHMET — CYCLE #9 MANUAL RELEASE');
writeFileSync(`${base}/manual-release-v1.md`,lines.join('\n')+'\n',{flag:'wx'});
console.log(JSON.stringify({stage:cycle.stage,revision:cycle.revision,decision,acceptedPresentationUnknowns:inspection.unknowns.length,acceptedOperationalUnknowns:risk.additionalOperationalUnknowns.length,externalPlatformActions:[]}));
