import {existsSync,mkdirSync,readFileSync,statSync,writeFileSync} from 'node:fs';
import {dirname} from 'node:path';
import {mediaHash} from '../src/artifacts/media';
import {openMediaCatalog} from '../src/artifacts/catalog';
import {sha256Json} from '../src/content-intelligence/run-schema';
import {knowledgePackageSchema} from '../src/knowledge/schema';
import {contentAssetSchema} from '../src/content-assets/schema';
import {creativeDirectionSchema} from '../src/content-assets/creative-direction';
import {validateAdaptiveCaptionPlan} from '../src/captions/adaptive-plan';
import {validateInternalProductionPlanReferences} from '../src/production/schema';
import {assessPresentationV3} from '../src/workflow/presentation';
import {loadCycle,persistCycleEvent} from '../src/workflow/store';
import {ownerHandoff} from '../src/workflow/handoff';
import {okloTarget as target} from './production-video-targets';
import metadata from '../src/production/narration/oklo.json';
import type {RecordReference} from '../src/workflow/evidence';
const base='content-intelligence/cycles/cycle-8/size-revision-v3',now=new Date().toISOString();
const read=(path:string):unknown=>JSON.parse(readFileSync(path,'utf8')),ref=(path:string):RecordReference=>({path,sha256:mediaHash(path)});
const put=(name:string,data:unknown)=>{const path=`${base}/${name}.json`;if(existsSync(path))throw new Error(`Preserve ${path}`);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,JSON.stringify(data,null,2)+'\n',{flag:'wx'});return ref(path);};
const registry=openMediaCatalog(),editorialBase='content-intelligence/cycles/cycle-8',path=target.output;
const registered=registry.list().find(m=>m.canonicalPath===path)!;if(!registered)throw new Error('Missing preflighted registration');const media={id:registered.id,sha256:registered.sha256};
const pkg=knowledgePackageSchema.parse(read(`${editorialBase}/knowledge-package.ready.json`)),asset=contentAssetSchema.parse(read(`${editorialBase}/content-asset.ready.json`)),direction=creativeDirectionSchema.parse(read(`${editorialBase}/direction-v1.json`));
const caption=validateAdaptiveCaptionPlan(read('src/captions/plans/oklo.json'),metadata.cues,metadata.format,direction,asset),plan=validateInternalProductionPlanReferences(read('src/production/plans/oklo.json'),pkg,asset,direction);
type Rect={x:number;y:number;width:number;height:number};
type Layout={passed:boolean;observations:{frame:number;bounds:(Rect&{kind:string})[]}[]};
const layout=read(`${base}/qa/typography-report.json`) as Layout;
const inspection=ref(`${base}/qa/visual-inspection-normalized.json`),manual=read(inspection.path) as {mediaSha256:string;inspectedAt:string;passed:boolean};
if(!manual.passed||manual.mediaSha256!==media.sha256)throw new Error('Detached inspection');
const qa=ref(`${base}/qa/final-report.json`),planRef=ref(`${base}/production-plan.candidate-v3.json`),scriptSha256=sha256Json(asset.script),checks={technical:'passed' as const,typography:'passed' as const,captions:'passed' as const,audio:'passed' as const};
const narration=metadata.cues.map(c=>{const m=registry.byHash(mediaHash(`public/${c.file}`))!;return {id:c.id,transcript:c.transcript,start:c.start,duration:c.duration,media:{id:m.id,sha256:m.sha256}};});
const midpoints=caption.cues.map(c=>Math.floor((c.startFrame+c.endFrame)/2)),payoff=midpoints.at(-1)!;
const preflight=['youtube','tiktok','instagram','facebook'].map(platform=>{
 const profileRef=ref(`${editorialBase}/profiles/${platform}.json`),profile=read(profileRef.path) as {platform:'youtube'|'tiktok'|'instagram'|'facebook';surface:string};
 const samples:{frame:number;kind:'critical'|'caption-midpoint'|'disclosure'|'hook'|'payoff';bounds:Rect}[]=layout.observations.flatMap(o=>o.bounds.filter(b=>b.width>0&&b.height>0).map(b=>({frame:o.frame,kind:b.kind==='caption-midpoint'?'caption-midpoint' as const:b.kind==='disclosure'?'disclosure' as const:'critical' as const,bounds:{x:b.x,y:b.y,width:b.width,height:b.height}})));
 const boundsAt=(frame:number)=>{const b=layout.observations.find(o=>o.frame===frame)!.bounds.find(b=>b.kind==='scene')!;return {x:b.x,y:b.y,width:b.width,height:b.height};};
 samples.push({frame:0,kind:'hook',bounds:boundsAt(0)},{frame:payoff,kind:'payoff',bounds:boundsAt(payoff)});
 const evidence={schemaVersion:3,media,platform:profile.platform,surface:profile.surface,profileSha256:sha256Json(profile),inspectedAt:manual.inspectedAt,fps:30,durationFrames:metadata.durationFrames,samples,coverage:{method:'sampled-bounds',captionMidpoints:midpoints,hookFrames:[0],payoffFrames:[payoff],disclosureFrames:layout.observations.map(o=>o.frame)},reports:[qa,inspection],device:{state:'not-tested',device:null,testedAt:null,evidence:[]}};
 const result=assessPresentationV3(evidence,profile,media,registry,now);if(result.collisions.length)throw new Error(result.collisions.join('; '));return {profile:profileRef,evidence:put(`preflight/${platform}`,result.evidence)};
});
const candidate=put('master-candidate-v3',{schemaVersion:3,cycleId:'cycle.8',media,durationSeconds:plan.format.durationSeconds,scriptSha256,productionPlan:planRef,captionPlan:ref('src/captions/plans/oklo.json'),narrationBundle:ref('src/production/narration/oklo.json'),platformPreflight:preflight,narration,qa:{...checks,reports:[qa]},factualSafeguards:['Natural fission zones in rock, not human-built machinery or electricity generation.','Approximate two-billion-year age, not a precise common start date for every zone.','Ancient fissile fraction, concentration/geometry, neutron retention, competing absorption and moderation are jointly relevant.','Water slows neutrons through collisions, especially hydrogen; moderation is distinct from absorption.','Present depleted uranium and fission products provide evidence of ancient fission; operational details are reconstructed.','Cycling explicitly scoped to one studied reaction zone; groundwater feedback is an inference, no universal precise pulse clock.','Original illustrative geological and atomic views, not site footage, exact ancient geometry, quantitative neutron paths or visible radioactivity.'],uncertainties:['Owner listening must judge Oklo, Gabon, xenon and isotope pronunciation, prosody and authored caption synchrony; ASR is corroboration only.','Ancient geometry, water content and detailed behavior are reconstructed; individual reaction zones need not share a schedule.','Relevant scholarly review, original criticality modeling and participant account inspected; original2004 full paper inaccessible beyond abstract, no raw-data replication.','Native UI, crop behavior and exact-media real-device performance remain untested.','Sampled browser and decoded visual inspection with full decode, not all-frame bounds or continuous human playback.','No variants, covers, deliveries, publication package, upload, scheduling, publication or analytics created.'],unusualProduction:['Continuous original geological relief and scale changes, with two limited atomic mechanism views; restrained heat illustration and voice-only sound.']});
const next=persistCycleEvent(process.cwd(),loadCycle(process.cwd(),'cycle.8',registry),{type:'complete-internal',stage:'production',record:candidate,at:new Date().toISOString()},registry);put('master-review-controller-handoff',ownerHandoff(next,registry));console.log(JSON.stringify({stage:next.stage,path,media,bytes:statSync(path).size,duration:plan.format.durationSeconds},null,2));
