import {execFileSync,spawnSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {existsSync,mkdirSync,readFileSync,renameSync,statSync,writeFileSync} from 'node:fs';
import {dirname} from 'node:path';
import {mediaHash,mediaArtifactSchema,type MediaReference} from '../src/artifacts/media';
import {openMediaCatalog,persistMediaArtifact} from '../src/artifacts/catalog';
import {sha256Json} from '../src/content-intelligence/run-schema';
import {knowledgePackageSchema} from '../src/knowledge/schema';
import {contentAssetSchema} from '../src/content-assets/schema';
import {creativeDirectionSchema} from '../src/content-assets/creative-direction';
import {validateAdaptiveCaptionPlan} from '../src/captions/adaptive-plan';
import {validateInternalProductionPlanReferences} from '../src/production/schema';
import {assessPresentationV3} from '../src/workflow/presentation';
import {loadCycle,persistCycleEvent} from '../src/workflow/store';
import {ownerHandoff} from '../src/workflow/handoff';
import {inspectMedia} from '../src/artifacts/inspection';
import {chladniTarget} from './production-video-targets';
import metadata from '../src/production/narration/chladni.json';
import type {RecordReference} from '../src/workflow/evidence';
const base='content-intelligence/cycles/cycle-5',now=new Date().toISOString();
const sourceCommit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const read=(path:string):unknown=>JSON.parse(readFileSync(path,'utf8'));
const ref=(path:string):RecordReference=>({path,sha256:mediaHash(path)});
const put=(name:string,data:unknown)=>{const path=`${base}/${name}.json`;if(existsSync(path))return ref(path);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,JSON.stringify(data,null,2)+'\n',{flag:'wx'});return ref(path);};
const registry=openMediaCatalog();
const register=(path:string,mediaType:string,kind:'original-production'|'evidence-snapshot',sourceRecords:string[],parents:MediaReference[]=[])=>{
 const sha256=mediaHash(path),existing=registry.byHash(sha256);if(existing){if(existing.canonicalPath!==path)throw new Error('Redundant media payload');return {id:existing.id,sha256};}
 return persistMediaArtifact(mediaArtifactSchema.parse({id:`media.${sha256}`,sha256,canonicalPath:path,mediaType,bytes:statSync(path).size,provenance:{kind,sourceCommit,sourceRecords,createdAt:statSync(path).birthtime.toISOString(),creationTimeUnknownReason:null},parents}));
};
type Rect={x:number;y:number;width:number;height:number};
type Layout={passed:boolean;failures:string[];observations:{frame:number;fontsLoaded:boolean;bounds:(Rect&{kind:string;text:string})[];caption:null|{width:number;height:number;availableWidth:number;availableHeight:number};disclosure:boolean}[]};
const layout=read('qa/chladni-sand/typography-report.json') as Layout;
const technical=read('qa/chladni-sand/report.json') as {passed:boolean;failures:string[]};
const audio=read('qa/chladni-sand/audio-inspection.json') as {masterSha256:string;loudnessSummary:string;results:{id:string;duration:number;recognized:string;exactText:string}[]};
const path=chladniTarget.output;
if(!layout.passed||!technical.passed||audio.masterSha256!==mediaHash(path))throw new Error('QA failed or detached from final master.');
const ffmpeg=createRequire(import.meta.url)('ffmpeg-static') as string;
const decode=spawnSync(ffmpeg,['-v','error','-xerror','-err_detect','explode','-i',path,'-map','0:v:0','-map','0:a:0','-f','null','-'],{encoding:'utf8'});if(decode.status!==0)throw new Error(decode.stderr);
const videoDigest=(file:string)=>execFileSync(ffmpeg,['-v','error','-i',file,'-map','0:v:0','-c','copy','-f','hash','-hash','sha256','-'],{encoding:'utf8'}).trim();
const videoPackets=videoDigest('output/chladni-render.mp4');if(videoPackets!==videoDigest(path))throw new Error('Audio mastering altered picture bytes.');
const pkg=knowledgePackageSchema.parse(read(`${base}/knowledge-package.ready.json`)),asset=contentAssetSchema.parse(read(`${base}/content-asset.ready.json`)),direction=creativeDirectionSchema.parse(read(`${base}/direction-v1.json`));
const caption=validateAdaptiveCaptionPlan(read('src/captions/plans/chladni.json'),metadata.cues,metadata.format,direction,asset),plan=validateInternalProductionPlanReferences(read('src/production/plans/chladni.json'),pkg,asset,direction);
const files=['src/chladni-index.tsx','src/compositions/ChladniSand.tsx','src/components/ChladniPlate.tsx','src/production/chladni-geometry.ts','scripts/render-chladni.ts','scripts/qa-chladni-layout.ts','scripts/generate-chladni-narration.mjs','scripts/generate-chladni-tones.mjs','scripts/prepare-chladni-production.ts','src/production/plans/chladni.json','src/captions/plans/chladni.json','src/production/narration/chladni.json','tests/chladni-geometry.test.ts'];
put('implementation-bindings',{enteredAt:now,sourceBaseCommit:sourceCommit,files:files.map(ref),videoPacketSha256:videoPackets,audioMastering:ref(`${base}/audio-mastering.json`),renderInputs:'Exact scoped plan/captions/narration and licensed Manrope fonts; original analytic field/grain renderer and synthesized tones.',postRenderQaMarkerChange:'Only data-critical marker moved from the clipped SVG group to its visible plate boundary after full render. This attribute affects QA extraction, not pixel/audio output; decoded master and corrected browser checkpoints both inspected.',note:'Base commit identifies starting repository policy; exact new source hashes bind the implementation without a circular self-commit claim.'});
const narration=metadata.cues.map(c=>({id:c.id,transcript:c.transcript,start:c.start,duration:c.duration,media:register(`public/${c.file}`,'audio/wav','original-production',['src/production/narration/chladni.json','scripts/generate-chladni-narration.mjs',`${base}/rights-provenance.json`])}));
const tones=register('public/audio/chladni/illustrative-tones.wav','audio/wav','original-production',['scripts/generate-chladni-tones.mjs',`${base}/tone-provenance.json`,`${base}/rights-provenance.json`]);
const media=register(path,'video/mp4','original-production',[`${base}/implementation-bindings.json`,`${base}/rights-provenance.json`,`${base}/audio-mastering.json`], [...narration.map(n=>n.media),tones]);
const evidenceDirectory='artifacts/qa-evidence/chladni-sand-v1';mkdirSync(evidenceDirectory,{recursive:true});
const contactPath=`${evidenceDirectory}/contact-sheet.jpg`;if(!existsSync(contactPath))renameSync('qa/chladni-sand/contact-sheet.jpg',contactPath);const contact=register(contactPath,'image/jpeg','evidence-snapshot',[`${base}/implementation-bindings.json`,'scripts/qa.ts'],[media]);
const reviewFrames=plan.beats.map(b=>{const cue=caption.cues.find(c=>c.startFrame>=b.frames.start&&c.startFrame<b.frames.end)!;const frame=Math.floor((cue.startFrame+cue.endFrame)/2);const i=chladniTarget.qaTimestamps.findIndex(t=>Math.round(t*30)===frame);if(i<0)throw new Error('Missing decoded proof frame');const name=`frame-${String(i+1).padStart(2,'0')}-${chladniTarget.qaTimestamps[i]!.toFixed(1)}s.png`;const destination=`${evidenceDirectory}/${name}`;if(!existsSync(destination))renameSync(`qa/chladni-sand/${name}`,destination);return register(destination,'image/png','evidence-snapshot',[`${base}/implementation-bindings.json`,'scripts/qa.ts'],[media]);});
for(const name of ['report','typography-report','audio-inspection'])put(`qa/${name}`,read(`qa/chladni-sand/${name}.json`));
const inspection=ref(`${base}/qa/visual-inspection.json`);const manual=read(inspection.path) as {mediaSha256:string;inspectedAt:string;passed:boolean};if(!manual.passed||manual.mediaSha256!==media.sha256)throw new Error('Actual-master visual inspection missing.');
const scriptSha256=sha256Json(asset.script),checks={technical:'passed' as const,typography:'passed' as const,captions:'passed' as const,audio:'passed' as const};
const qa=put('qa/final-report',{mediaSha256:media.sha256,scriptSha256,checkedAt:now,checks,actualMedia:inspectMedia(path),fullDecode:'passed',videoPayloadUnchangedByMastering:videoPackets,captionCount:caption.cues.length,browserCheckpoints:layout.observations.length,decodedContactSheet:contact,retainedReviewFrames:reviewFrames,sourceReports:['report','typography-report','audio-inspection','visual-inspection'].map(n=>ref(`${base}/qa/${n}.json`)),audio:{loudnessSummary:audio.loudnessSummary,subjectiveLimit:'ASR, loudness and source-cue checks are machine corroboration; naturalness and tone balance remain owner judgment.',recognitionNote:'Cue-level recognized wording corroborates exact narration; full-master ASR joins phrase boundaries and renders Change as changed, without replacing canonical wording.'},coverage:'43 sampled layouts and decoded checkpoints including every caption midpoint; complete media decode. No all-frame bounds or native/mobile/crop proof.',publicationApprovalGranted:false});
const renderedPlan={...plan,status:'rendered-candidate-visual-review-required' as const};validateInternalProductionPlanReferences(renderedPlan,pkg,asset,direction);const planRef=put('production-plan.candidate-v1',renderedPlan);
const midpoints=caption.cues.map(c=>Math.floor((c.startFrame+c.endFrame)/2)),payoff=1205;
const preflight=['youtube','tiktok','instagram','facebook'].map(platform=>{
 const profileRef=ref(`${base}/profiles/${platform}.json`),profile=read(profileRef.path) as {platform:'youtube'|'tiktok'|'instagram'|'facebook';surface:string};
 const samples:{frame:number;kind:'critical'|'caption-midpoint'|'disclosure'|'hook'|'payoff';bounds:Rect}[]=layout.observations.flatMap(o=>o.bounds.filter(b=>b.width>0&&b.height>0).map(b=>({frame:o.frame,kind:b.kind==='caption-midpoint'?'caption-midpoint' as const:b.kind==='disclosure'?'disclosure' as const:'critical' as const,bounds:{x:b.x,y:b.y,width:b.width,height:b.height}})));
 const boundsAt=(frame:number,kind:string)=>{const b=layout.observations.find(o=>o.frame===frame)!.bounds.find(b=>b.kind===kind)!;return {x:b.x,y:b.y,width:b.width,height:b.height};};
 samples.push({frame:0,kind:'hook',bounds:boundsAt(0,'plate')},{frame:payoff,kind:'payoff',bounds:boundsAt(payoff,'plate')});
 const evidence={schemaVersion:3,media,platform:profile.platform,surface:profile.surface,profileSha256:sha256Json(profile),inspectedAt:manual.inspectedAt,fps:30,durationFrames:metadata.durationFrames,samples,coverage:{method:'sampled-bounds',captionMidpoints:midpoints,hookFrames:[0],payoffFrames:[payoff],disclosureFrames:layout.observations.map(o=>o.frame)},reports:[qa,inspection],device:{state:'not-tested',device:null,testedAt:null,evidence:[]}};
 const result=assessPresentationV3(evidence,profile,media,registry,now);if(result.collisions.length)throw new Error(result.collisions.join('; '));return {profile:profileRef,evidence:put(`preflight/${platform}`,result.evidence)};
});
const candidate=put('master-candidate-v1',{schemaVersion:3,cycleId:'cycle.5',media,durationSeconds:plan.format.durationSeconds,scriptSha256,productionPlan:planRef,captionPlan:ref('src/captions/plans/chladni.json'),narrationBundle:ref('src/production/narration/chladni.json'),platformPreflight:preflight,narration,qa:{...checks,reports:[qa]},factualSafeguards:['Sand traces low-motion nodal lines of a plate, not a traveling air-pressure wave.','Grain paths/fields are qualitative illustrations; nodes in slowed/exaggerated side view remain fixed.','Different modes can yield different patterns; plate/support/excitation matter.','Synthesized tones are explicitly illustrative, never calibrated to displayed spatial modes.','No healing/medical/mystical claims or borrowed institutional media.'],uncertainties:['Owner should judge voice naturalness, resonant frequency/nodes pronunciation, visual pace, material impression and tone balance in actual playback.','Playback preflight clears sampled provisional insets; native exclusions, caption-safe geometry/crops and exact-media mobile behavior remain unknown.','No all-frame bounds proof; unsampled motion remains untested.','No platform adaptation, cover, delivery, upload, scheduling, publication or performance evidence created.'],unusualProduction:['Original grain/plate field choreography, clipped close view and slowed side view; two quiet illustrative tones and no music bed.']});
const cycle=loadCycle(process.cwd(),'cycle.5',registry);const next=persistCycleEvent(process.cwd(),cycle,{type:'complete-internal',stage:'production',record:candidate,at:new Date().toISOString()},registry);put('master-review-controller-handoff',ownerHandoff(next,registry));
console.log(JSON.stringify({stage:next.stage,file:path,sha256:media.sha256,bytes:statSync(path).size,duration:plan.format.durationSeconds,qa},null,2));
