import {execFileSync,spawnSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {existsSync,mkdirSync,readFileSync,renameSync,statSync,writeFileSync} from 'node:fs';
import {dirname} from 'node:path';
import {mediaHash,mediaArtifactSchema,type MediaReference} from '../src/artifacts/media';
import {openMediaCatalog,persistMediaArtifact} from '../src/artifacts/catalog';
import {sha256Json} from '../src/content-intelligence/run-schema';
import {knowledgePackageSchema} from '../src/knowledge/schema';
import {contentAssetSchema} from '../src/content-assets/schema';
import {creativeDirectionSchema} from '../src/content-assets/creative-direction';
import {validateAdaptiveCaptionPlan} from '../src/captions/adaptive-plan';
import {validateInternalProductionPlanReferences} from '../src/production/schema';
import {assessPresentationV3} from '../src/workflow/presentation';
import {loadCycle,persistCycleEvent} from '../src/workflow/store';
import {ownerHandoff} from '../src/workflow/handoff';
import {inspectMedia} from '../src/artifacts/inspection';
import {ifmTarget as target} from './production-video-targets';
import metadata from '../src/production/narration/ifm.json';
import type {RecordReference} from '../src/workflow/evidence';
const base='content-intelligence/cycles/cycle-7/revision-2',now=new Date().toISOString(),sourceCommit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const read=(path:string):unknown=>JSON.parse(readFileSync(path,'utf8')),ref=(path:string):RecordReference=>({path,sha256:mediaHash(path)});
const put=(name:string,data:unknown)=>{const path=`${base}/${name}.json`;if(existsSync(path))throw new Error(`Preserve ${path}`);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,JSON.stringify(data,null,2)+'\n',{flag:'wx'});return ref(path);};
const registry=openMediaCatalog();
const register=(path:string,mediaType:string,kind:'original-production'|'evidence-snapshot',sourceRecords:string[],parents:MediaReference[]=[])=>{
 const sha256=mediaHash(path),existing=registry.byHash(sha256);if(existing){if(existing.canonicalPath!==path)throw new Error('Redundant media payload');return {id:existing.id,sha256};}
 return persistMediaArtifact(mediaArtifactSchema.parse({id:`media.${sha256}`,sha256,canonicalPath:path,mediaType,bytes:statSync(path).size,provenance:{kind,sourceCommit,sourceRecords,createdAt:statSync(path).birthtime.toISOString(),creationTimeUnknownReason:null},parents}));
};
type Rect={x:number;y:number;width:number;height:number};
type Layout={passed:boolean;failures:string[];observations:{frame:number;fontsLoaded:boolean;bounds:(Rect&{kind:string;text:string})[];caption:null|{width:number;height:number;availableWidth:number;availableHeight:number};disclosure:boolean}[]};
const layout=read('qa/interaction-free/typography-report.json') as Layout,technical=read('qa/interaction-free/report.json') as {passed:boolean},audio=read('qa/interaction-free/audio-inspection.json') as {masterSha256:string;loudnessSummary:string},path=target.output;
if(!layout.passed||!technical.passed||audio.masterSha256!==mediaHash(path))throw new Error('Detached or failed QA');
const ffmpeg=createRequire(import.meta.url)('ffmpeg-static') as string;
const decode=spawnSync(ffmpeg,['-v','error','-xerror','-err_detect','explode','-i',path,'-map','0:v:0','-map','0:a:0','-f','null','-'],{encoding:'utf8'});if(decode.status!==0)throw new Error(decode.stderr);
const packetHash=(p:string)=>execFileSync(ffmpeg,['-v','error','-i',p,'-map','0:v:0','-c','copy','-f','hash','-hash','sha256','-'],{encoding:'utf8'}).trim();
const videoPackets=packetHash(path);if(packetHash('output/ifm-render-v2.mp4')!==videoPackets)throw new Error('Picture changed during audio mastering');
const pkg=knowledgePackageSchema.parse(read(`${base}/knowledge-package.ready.json`)),asset=contentAssetSchema.parse(read(`${base}/content-asset.ready.json`)),direction=creativeDirectionSchema.parse(read(`${base}/direction-v1.json`));
const caption=validateAdaptiveCaptionPlan(read('src/captions/plans/ifm.json'),metadata.cues,metadata.format,direction,asset),plan=validateInternalProductionPlanReferences(read('src/production/plans/ifm.json'),pkg,asset,direction);
const files=['src/ifm-index.tsx','src/compositions/InteractionFree.tsx','src/components/OpticalBench.tsx','src/content/videos/interaction-free.ts','scripts/render-ifm.ts','scripts/qa-ifm-layout.ts','scripts/inspect-ifm-audio.mjs','scripts/generate-ifm-narration.mjs','scripts/prepare-ifm-production.ts','src/production/plans/ifm.json','src/captions/plans/ifm.json','src/production/narration/ifm.json'];
put('implementation-bindings',{enteredAt:now,sourceBaseCommit:sourceCommit,files:files.map(ref),videoPacketSha256:videoPackets,audioMastering:ref(`${base}/audio-mastering-v2.json`),note:'Exact new source hashes bind implementation; base commit is not a circular self-commit claim. Original geometry, consultation-only research and established fonts/local narration.'});
const narration=metadata.cues.map(c=>({id:c.id,transcript:c.transcript,start:c.start,duration:c.duration,media:register(`public/${c.file}`,'audio/wav','original-production',['src/production/narration/ifm.json','scripts/generate-ifm-narration.mjs',`${base}/rights-provenance.json`])}));
const media=register(path,'video/mp4','original-production',[`${base}/implementation-bindings.json`,`${base}/rights-provenance.json`,`${base}/audio-mastering-v2.json`],narration.map(n=>n.media));
const ed='artifacts/qa-evidence/interaction-free-cycle7-v1';mkdirSync(ed,{recursive:true});
const contactPath=`${ed}/contact-sheet.jpg`;renameSync('qa/interaction-free/contact-sheet.jpg',contactPath);const contact=register(contactPath,'image/jpeg','evidence-snapshot',[`${base}/implementation-bindings.json`,'scripts/qa.ts'],[media]);
const proofFrames=[...new Set([0,15,30,60,...caption.cues.map(c=>Math.floor((c.startFrame+c.endFrame)/2))])];
const reviewFrames=proofFrames.map(frame=>{const i=target.qaTimestamps.findIndex(t=>Math.round(t*30)===frame);if(i<0)throw new Error('Missing proof frame');const name=`frame-${String(i+1).padStart(2,'0')}-${target.qaTimestamps[i]!.toFixed(1)}s.png`,destination=`${ed}/${name}`;const same=registry.byHash(mediaHash(`qa/interaction-free/${name}`));if(same)return {id:same.id,sha256:same.sha256};renameSync(`qa/interaction-free/${name}`,destination);return register(destination,'image/png','evidence-snapshot',[`${base}/implementation-bindings.json`,'scripts/qa.ts'],[media]);});
for(const name of ['report','typography-report','audio-inspection'])put(`qa/${name}`,read(`qa/interaction-free/${name}.json`));
const inspection=ref(`${base}/qa/visual-inspection.json`),manual=read(inspection.path) as {mediaSha256:string;inspectedAt:string;passed:boolean};if(!manual.passed||manual.mediaSha256!==media.sha256)throw new Error('Missing actual-master visual inspection');
const scriptSha256=sha256Json(asset.script),checks={technical:'passed' as const,typography:'passed' as const,captions:'passed' as const,audio:'passed' as const};
const qa=put('qa/final-report',{mediaSha256:media.sha256,scriptSha256,checkedAt:now,checks,actualMedia:inspectMedia(path),fullDecode:'passed',videoPayloadUnchangedByMastering:videoPackets,captionCount:caption.cues.length,browserCheckpoints:layout.observations.length,decodedContactSheet:contact,retainedReviewFrames:reviewFrames,sourceReports:['report','typography-report','audio-inspection','visual-inspection'].map(n=>ref(`${base}/qa/${n}.json`)),audio:{loudnessSummary:audio.loudnessSummary,limitation:'ASR and signal measurements corroborate speech; pronunciation, tone, naturalness and semantic phrase synchrony remain owner listening judgments.'},coverage:'All registered browser and decoded checkpoint samples, every caption midpoint, opening and beat boundaries. Full media decoded; no all-frame bounds or native/mobile/crop proof.',publicationApprovalGranted:false});
const renderedPlan={...plan,status:'rendered-candidate-visual-review-required' as const};validateInternalProductionPlanReferences(renderedPlan,pkg,asset,direction);const planRef=put('production-plan.candidate-v1',renderedPlan);
const midpoints=caption.cues.map(c=>Math.floor((c.startFrame+c.endFrame)/2)),payoff=midpoints.at(-1)!;
const preflight=['youtube','tiktok','instagram','facebook'].map(platform=>{
 const profileRef=ref(`${base}/profiles/${platform}.json`),profile=read(profileRef.path) as {platform:'youtube'|'tiktok'|'instagram'|'facebook';surface:string};
 const samples:{frame:number;kind:'critical'|'caption-midpoint'|'disclosure'|'hook'|'payoff';bounds:Rect}[]=layout.observations.flatMap(o=>o.bounds.filter(b=>b.width>0&&b.height>0).map(b=>({frame:o.frame,kind:b.kind==='caption-midpoint'?'caption-midpoint' as const:b.kind==='disclosure'?'disclosure' as const:'critical' as const,bounds:{x:b.x,y:b.y,width:b.width,height:b.height}})));
 const boundsAt=(frame:number)=>{const b=layout.observations.find(o=>o.frame===frame)!.bounds.find(b=>b.kind==='scene')!;return {x:b.x,y:b.y,width:b.width,height:b.height};};
 samples.push({frame:0,kind:'hook',bounds:boundsAt(0)},{frame:payoff,kind:'payoff',bounds:boundsAt(payoff)});
 const evidence={schemaVersion:3,media,platform:profile.platform,surface:profile.surface,profileSha256:sha256Json(profile),inspectedAt:manual.inspectedAt,fps:30,durationFrames:metadata.durationFrames,samples,coverage:{method:'sampled-bounds',captionMidpoints:midpoints,hookFrames:[0],payoffFrames:[payoff],disclosureFrames:layout.observations.map(o=>o.frame)},reports:[qa,inspection],device:{state:'not-tested',device:null,testedAt:null,evidence:[]}};
 const result=assessPresentationV3(evidence,profile,media,registry,now);if(result.collisions.length)throw new Error(result.collisions.join('; '));return {profile:profileRef,evidence:put(`preflight/${platform}`,result.evidence)};
});
const candidate=put('master-candidate-v1',{schemaVersion:3,cycleId:'cycle.7',media,durationSeconds:plan.format.durationSeconds,scriptSha256,productionPlan:planRef,captionPlan:ref('src/captions/plans/ifm.json'),narrationBundle:ref('src/production/narration/ifm.json'),platformPreflight:preflight,narration,qa:{...checks,reports:[qa]},factualSafeguards:['Ideal aligned optical model; curves are path amplitudes, not two photons or visible measured trajectories.','Absorbed and detected outcomes belong to explicitly different trials.','One detected photon was not absorbed by the object; no preferred classical trajectory or metaphysical no-interaction assertion.','Other trials can absorb photons or be inconclusive; no guaranteed harmless test.','Experimental author account concerns a different implementation, not authentic footage of this schematic.'],uncertainties:['Owner listening must judge interferometer pronunciation, naturalness, complete sentence prosody and authored caption timing. ASR is corroboration only.','Ideal-model dark baseline excludes practical leakage/detector noise; no claim of absolute empirical certainty.','Native UI, caption-safe geometry, crops and exact-media real-device behavior remain unknown.','Sampled visual/browser checks and complete decode, not all-frame bounds or continuous human playback.','Original theory and participant account inspected; no raw data or1995 image-only paper body inspection.','No variants, covers, deliveries, uploads, scheduling, publication or analytics created.'],unusualProduction:['Original stable instrument/outcome visualization; explicitly schematic probability amplitudes and distinct trials, voice-only sound.']});
const next=persistCycleEvent(process.cwd(),loadCycle(process.cwd(),'cycle.7',registry),{type:'complete-internal',stage:'production',record:candidate,at:new Date().toISOString()},registry);put('master-review-controller-handoff',ownerHandoff(next,registry));console.log(JSON.stringify({stage:next.stage,path,media,bytes:statSync(path).size,duration:plan.format.durationSeconds},null,2));
