import {execFileSync,spawnSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {mkdirSync,readFileSync,renameSync,statSync,writeFileSync} from 'node:fs';
import {dirname} from 'node:path';
import {mediaHash,mediaArtifactSchema,type MediaReference} from '../src/artifacts/media';
import {openMediaCatalog,persistMediaArtifact} from '../src/artifacts/catalog';
import {sha256Json} from '../src/content-intelligence/run-schema';
import {knowledgePackageSchema} from '../src/knowledge/schema';
import {contentAssetSchema} from '../src/content-assets/schema';
import {creativeDirectionSchema} from '../src/content-assets/creative-direction';
import {validateAdaptiveCaptionPlan} from '../src/captions/adaptive-plan';
import {validateInternalProductionPlanReferences} from '../src/production/schema';
import {assessPresentationV3} from '../src/workflow/presentation';
import {loadCycle,persistCycleEvent} from '../src/workflow/store';
import {ownerHandoff} from '../src/workflow/handoff';
import {inspectMedia} from '../src/artifacts/inspection';
import type {RecordReference} from '../src/workflow/evidence';
import metadata from '../src/production/narration/paper.json';
const base='content-intelligence/cycles/cycle-4';
const now=new Date().toISOString();
const sourceCommit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const read=(path:string):unknown=>JSON.parse(readFileSync(path,'utf8'));
const ref=(path:string):RecordReference=>({path,sha256:mediaHash(path)});
const put=(name:string,data:unknown)=>{const path=`${base}/${name}.json`;mkdirSync(dirname(path),{recursive:true});writeFileSync(path,JSON.stringify(data,null,2)+'\n',{flag:'wx'});return ref(path);};
const registry=openMediaCatalog();
const register=(path:string,mediaType:string,kind:'original-production'|'evidence-snapshot',sourceRecords:string[],parents:MediaReference[]=[])=>{
 const sha256=mediaHash(path);const existing=registry.byHash(sha256);
 if(existing){if(existing.canonicalPath!==path)throw new Error('Do not retain redundant media; resolve canonical payload first.');return {id:existing.id,sha256};}
 return persistMediaArtifact(mediaArtifactSchema.parse({id:`media.${sha256}`,sha256,canonicalPath:path,mediaType,bytes:statSync(path).size,provenance:{kind,sourceCommit,sourceRecords,createdAt:statSync(path).birthtime.toISOString(),creationTimeUnknownReason:null},parents}));
};
type Rect={x:number;y:number;width:number;height:number};
type Layout={passed:boolean;failures:string[];observations:{frame:number;fontsLoaded:boolean;bounds:(Rect&{kind:string;text:string})[];caption:null|{width:number;height:number;availableWidth:number;availableHeight:number};disclosure:boolean}[]};
const layout=read('qa/paper-half-shape/typography-report.json') as Layout;
const technical=read('qa/paper-half-shape/report.json') as {passed:boolean;observed:{maxVolumeDb:number};failures:string[]};
const audio=read('qa/paper-half-shape/audio-inspection.json') as {masterSha256:string;loudnessSummary:string;results:{id:string;duration:number}[];completeMasterRecognition:{text:string}};
const path='artifacts/masters/paper-half-shape-candidate-v1.mp4';
if(!layout.passed||!technical.passed||audio.masterSha256!==mediaHash(path))throw new Error('QA not passed on the final candidate.');
const ffmpeg=createRequire(import.meta.url)('ffmpeg-static') as string;
const decode=spawnSync(ffmpeg,['-v','error','-xerror','-err_detect','explode','-i',path,'-map','0:v:0','-map','0:a:0','-f','null','-'],{encoding:'utf8'});
if(decode.status!==0)throw new Error(decode.stderr);
const videoDigest=(file:string)=>execFileSync(ffmpeg,['-v','error','-i',file,'-map','0:v:0','-c','copy','-f','hash','-hash','sha256','-'],{encoding:'utf8'}).trim();
const rawVideo=videoDigest('output/paper-render.mp4');
if(rawVideo!==videoDigest(path))throw new Error('Audio mastering changed video payload.');
const pkg=knowledgePackageSchema.parse(read(`${base}/knowledge-package.ready.json`));
const asset=contentAssetSchema.parse(read(`${base}/content-asset.ready.json`));
const direction=creativeDirectionSchema.parse(read(`${base}/direction-v1.json`));
const caption=validateAdaptiveCaptionPlan(read('src/captions/plans/paper.json'),metadata.cues,metadata.format,direction,asset);
const plan=validateInternalProductionPlanReferences(read('src/production/plans/paper.json'),pkg,asset,direction);
const implementationFiles=['src/paper-index.tsx','src/compositions/PaperHalfShape.tsx','src/components/PaperObjects.tsx','src/production/paper-geometry.ts','scripts/render-paper.ts','scripts/generate-paper-narration.mjs','scripts/prepare-paper-production.ts','src/production/plans/paper.json','src/captions/plans/paper.json','src/production/narration/paper.json'];
put('implementation-bindings',{enteredAt:now,sourceBaseCommit:sourceCommit,files:implementationFiles.map(ref),videoPacketSha256:rawVideo,renderInputs:'Current immutable scoped plan/captions/narration and chosen Manrope package, rendered through the paper entry point.',audioMastering:ref(`${base}/audio-mastering-refined.json`),note:'Base commit identifies pre-cycle repository authority; exact new implementation is bound by file hashes, not a circular self-commit claim.'});
const narration=metadata.cues.map(c=>({id:c.id,transcript:c.transcript,start:c.start,duration:c.duration,media:register(`public/${c.file}`,'audio/wav','original-production',['src/production/narration/paper.json','scripts/generate-paper-narration.mjs',`${base}/rights-provenance.json`])}));
const media=register(path,'video/mp4','original-production',[`${base}/implementation-bindings.json`,`${base}/rights-provenance.json`,'src/production/narration/paper.json','src/captions/plans/paper.json',`${base}/audio-mastering-refined.json`],narration.map(n=>n.media));
const evidenceDirectory='artifacts/qa-evidence/paper-half-shape-v1';mkdirSync(evidenceDirectory,{recursive:true});
const contactPath=`${evidenceDirectory}/contact-sheet.jpg`;renameSync('qa/paper-half-shape/contact-sheet.jpg',contactPath);
const contact=register(contactPath,'image/jpeg','evidence-snapshot',[`${base}/implementation-bindings.json`,'scripts/qa.ts'],[media]);
const retainedFrames=['frame-07-5.9s.png','frame-12-11.4s.png','frame-17-18.2s.png','frame-23-25.4s.png','frame-28-31.0s.png','frame-31-34.9s.png','frame-36-41.1s.png','frame-43-49.9s.png'];
const reviewFrames=retainedFrames.map(name=>{const destination=`${evidenceDirectory}/${name}`;renameSync(`qa/paper-half-shape/${name}`,destination);return register(destination,'image/png','evidence-snapshot',[`${base}/implementation-bindings.json`,'scripts/qa.ts'],[media]);});
for(const name of ['report','typography-report','audio-inspection'])put(`qa/${name}`,read(`qa/paper-half-shape/${name}.json`));
const visualInspection=ref(`${base}/qa/visual-inspection.json`);
const manual=read(visualInspection.path) as {mediaSha256:string;inspectedAt:string;passed:boolean};
if(!manual.passed||manual.mediaSha256!==media.sha256)throw new Error('Manual visual inspection must identify final bytes.');
const scriptSha256=sha256Json(asset.script);
const checks={technical:'passed' as const,typography:'passed' as const,captions:'passed' as const,audio:'passed' as const};
const qa=put('qa/final-report',{mediaSha256:media.sha256,scriptSha256,checkedAt:now,checks,actualMedia:inspectMedia(path),fullDecode:'passed',videoPayloadUnchangedByMastering:rawVideo,captionCount:caption.cues.length,browserCheckpoints:layout.observations.length,decodedContactSheet:contact,retainedReviewFrames:reviewFrames,sourceReports:['report','typography-report','audio-inspection','visual-inspection'].map(name=>ref(`${base}/qa/${name}.json`)),audio:{loudnessSummary:audio.loudnessSummary,clipping:'No digital clipping; final measured peak has headroom.',asrCaveat:'Whisper tiny recognizes halve as have; spelling recognition alone does not prove a spoken error. Owner should inspect pronunciation and naturalness.'},coverage:'44 sampled timeline layouts and exact decoded master checkpoints; complete audio/video decode. No all-frame geometry or mobile/native/crop proof.',publicationApprovalGranted:false});
const renderedPlan={...plan,status:'rendered-candidate-visual-review-required' as const};
validateInternalProductionPlanReferences(renderedPlan,pkg,asset,direction);
const planRef=put('production-plan.candidate-v1',renderedPlan);
const midpoints=caption.cues.map(c=>Math.floor((c.startFrame+c.endFrame)/2));
const firstPayoff=1487;
const preflight=['youtube','tiktok','instagram','facebook'].map(platform=>{
 const profileRef=ref(`${base}/profiles/${platform}.json`);
 const profile=read(profileRef.path) as {platform:'youtube'|'tiktok'|'instagram'|'facebook';surface:string};
 const samples:{frame:number;kind:'critical'|'caption-midpoint'|'disclosure'|'hook'|'payoff';bounds:Rect}[]=layout.observations.flatMap(o=>o.bounds.filter(b=>b.width>0&&b.height>0).map(b=>({frame:o.frame,kind:b.kind==='caption-midpoint'?'caption-midpoint' as const:b.kind==='disclosure'?'disclosure' as const:'critical' as const,bounds:{x:b.x,y:b.y,width:b.width,height:b.height}})));
 const measured=(frame:number,kind:string)=>{const b=layout.observations.find(o=>o.frame===frame)!.bounds.find(b=>b.kind===kind)!;return {x:b.x,y:b.y,width:b.width,height:b.height};};
 samples.push({frame:0,kind:'hook',bounds:measured(0,'label')});
 samples.push({frame:firstPayoff,kind:'payoff',bounds:measured(firstPayoff,'proof')});
 const evidence={schemaVersion:3,media,platform:profile.platform,surface:profile.surface,profileSha256:sha256Json(profile),inspectedAt:manual.inspectedAt,fps:30,durationFrames:metadata.durationFrames,samples,coverage:{method:'sampled-bounds',captionMidpoints:midpoints,hookFrames:[0],payoffFrames:[firstPayoff],disclosureFrames:layout.observations.map(o=>o.frame)},reports:[qa,visualInspection],device:{state:'not-tested',device:null,testedAt:null,evidence:[]}};
 const result=assessPresentationV3(evidence,profile,media,registry,now);
 if(result.collisions.length)throw new Error(result.collisions.join('; '));
 return {profile:profileRef,evidence:put(`preflight/${platform}`,result.evidence)};
});
const candidate=put('master-candidate-v1',{schemaVersion:3,cycleId:'cycle.4',media,durationSeconds:plan.format.durationSeconds,scriptSha256,productionPlan:planRef,captionPlan:ref('src/captions/plans/paper.json'),narrationBundle:ref('src/production/narration/paper.json'),platformPreflight:preflight,narration,qa:{...checks,reports:[qa]},factualSafeguards:['Ideal A-series √2 model disclosed throughout; physical rounding spoken and shown.','Long dimension is bisected; half is rotated 90 degrees; geometry is original and mathematically checked.','Square counterexample prevents a universal-paper interpretation.','70.7% applies to each length; 50% applies to area; design scales uniformly.','No printer margin/crop guarantee, real paper footage, copied institutional figures or unsupported historical claims.'],uncertainties:['Subjective pronunciation/naturalness: A3/A4, halve and square-root phrases; ASR is corroboration, not human listening.','Pace, typography and emotional payoff need owner judgment at actual viewing size.','Four playback preflights clear provisional surviving insets; native exclusions, caption-specific geometry and crop remain unknown.','Every caption midpoint is sampled; unsampled motion lacks all-frame bounds proof.','No exact-media mobile, desktop-web platform, grid/feed/cover evidence or publication work exists.'],unusualProduction:['Original diagram-led paper choreography and original abstract print design; narration-only sound chosen for concentration.']});
const cycle=loadCycle(process.cwd(),'cycle.4',registry);
const next=persistCycleEvent(process.cwd(),cycle,{type:'complete-internal',stage:'production',record:candidate,at:new Date().toISOString()},registry);
put('master-review-controller-handoff',ownerHandoff(next,registry));
console.log(JSON.stringify({stage:next.stage,file:path,sha256:media.sha256,bytes:statSync(path).size,videoSeconds:plan.format.durationSeconds,qa},null,2));
