import json,hashlib,pathlib,datetime,wave,math,struct,subprocess
root=pathlib.Path('.')
def read(p):return json.load(open(p))
def dump(p,o):pathlib.Path(p).parent.mkdir(parents=True,exist_ok=True);pathlib.Path(p).write_text(json.dumps(o,ensure_ascii=False,sort_keys=True,indent=2)+'\n')
def sha(p):return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def jsha(o):return subprocess.check_output(['/Users/ahmetnishefci/.nvm/versions/node/v22.23.3/bin/node','--import','tsx','--input-type=module','-e',"import {sha256Json} from './src/content-intelligence/run-schema.ts';let x='';for await(const c of process.stdin)x+=c;console.log(sha256Json(JSON.parse(x)));"],input=json.dumps(o).encode()).decode().strip()
def ref(o):return dict(id=o['id'],revision=o['revision'],sha256=jsha(o))
if pathlib.Path('artifacts/masters/chocolate-crystal-choice-candidate-v1.mp4').exists(): raise SystemExit('Candidate exists; preserve exact bound artifacts')
now=datetime.datetime.now(datetime.timezone.utc).isoformat(timespec='milliseconds').replace('+00:00','Z')
b='content-intelligence/reviews/chocolate-crystal-choice-production-v1/'
if pathlib.Path(b+'owner-decision.json').exists(): now=read(b+'owner-decision.json')['enteredAt']
a=read('content-intelligence/reviews/chocolate-crystal-choice-approved-v3/content-asset.approved.json');k=read('content-intelligence/reviews/chocolate-crystal-choice-approved-v3/knowledge-package.approved.json');d=read('content-intelligence/creative-directions/chocolate-crystal-choice-same-recipe/direction-v1.json');n=read('src/production/narration/chocolate.json')
# Python canonical sorting differs from localeCompare for unusual keys; these model keys are plain Latin.
decision=dict(schemaVersion=1,id='owner-decision.chocolate-crystal-choice.production-v1',revision=1,owner='Ahmet Nishefci',decision='approved-creative-direction-and-one-master-candidate',enteredAt=now,ownerSuppliedReviewTimestamp=None,reviewTimeBasis='decision-entry',approvedDirection=ref(d),knowledgePackage=ref(k),contentAsset=ref(a),approvedScriptSha256=n['provenance']['approvedScriptSha256'],sourceCommit='cca828c3320a062764cf3185dd23bd05ce197404',scope=['CreativeDirection revision 1 approval','Production planning','One owner-review master candidate'],masterApprovalGranted=False,platformApprovalGranted=False,publicationApprovalGranted=False,nextGate='AHMET — CYCLE #3 OWNER MASTER VISUAL REVIEW')
dump(b+'owner-decision.json',decision)
d['revision']=2;d['state']='ready-for-production-planning';d['ownerReview']['decision']=ref(decision);d['provenance']['enteredAt']=now;d['provenance']['notes']='Revision 1 owner-approved without creative changes. Revision 2 records readiness and exact decision-entry binding; one candidate only, no platform/publication approval.'
dump(b+'direction-approved-v2.json',d)
fontfiles=['AtkinsonHyperlegibleNext.ttf','OFL.txt','OFL.upstream.gz','METADATA.pb'];dump('public/fonts/chocolate/provenance.json',dict(family='Atkinson Hyperlegible Next',source='https://github.com/google/fonts/tree/main/ofl/atkinsonhyperlegiblenext',license='SIL Open Font License 1.1',retrievedAt=now,unmodified=True,weights=[400,500,600],files=[dict(path='public/fonts/chocolate/'+f,sha256=sha('public/fonts/chocolate/'+f)) for f in fontfiles],rationale='Open humanist counters for material labels and calm phrase captions; browser loading and fit tested separately.'))
phrases=[['The recipe can stay','the same.'],['The chocolate','doesn’t have to.'],['Chocolate contains','cocoa butter,','a fat that forms crystals.'],['Melt it enough,','and that crystal structure','breaks down.'],['As it cools,','crystals form again.'],['But their arrangements,','and the network they build,','can differ.'],['The result can be','softer chocolate','with less snap.'],['Tempering guides','that rebuilding','with controlled temperatures','and mixing.'],['The goal is a structure','that helps chocolate','snap cleanly','and look glossy.'],['Same recipe.'],['Different structure.']]
cs=[]
for cue,groups in zip(n['cues'],phrases):
 start=round(cue['start']*30);end=round((cue['start']+cue['duration'])*30);weights=[len(g.split()) for g in groups];total=sum(weights);passed=0
 for group,w in zip(groups,weights):
  s=start+round((end-start)*passed/total);passed+=w;e=start+round((end-start)*passed/total)
  cs.append(dict(id='chocolate-caption-'+str(len(cs)+1),sourceNarrationCueId=cue['id'],startFrame=s,endFrame=e,lines=[group],bounds=dict(x=100,y=1440,width=790,height=166),presentationIntent='Speech-first phrase, restrained static setting; pause-free source coverage.'))
cp=dict(schemaVersion=2,id='caption-plan.chocolate-crystal-choice.material-cutaway',revision=1,status='review-required',creativeDirection=ref(d),approvedScriptSha256=n['provenance']['approvedScriptSha256'],fps=30,coverage='complete-narration',visualTreatment=dict(fontAsset='public/fonts/chocolate/AtkinsonHyperlegibleNext.ttf',fontFamily='Chocolate Humanist',fontSize=56,fontWeight=500,lineHeight=1.18,foreground='#352733',emphasisMethod='Semantic phrase grouping only; no karaoke',backdrop='Quiet smoky-lilac dedicated reading area, no backplate',animation='Static phrase replacement at authored measured-clip boundaries',rendererId='chocolate.material-caption.v1',rationale='Keeps the object and structure unobstructed; humanist counters support phone reading.'),cues=cs);dump('src/captions/plans/chocolate.json',cp)
starts=[0,154,292,408,632,736,892,1050,1195];treatments=['Immediate same-recipe specimen and two conceptual outcomes; illustrative not tested','Window exposes fat and retained sugar/cocoa solids','Fat order dissolves on sufficient melting; solids persist','Packing view first, then larger network with explicit distinct labels','Illustrative yielding slab reconnects structure with possible softer behavior','Temperature control and mixing guide domain rebuilding; no recipe values','Original fractured specimen with broad plausible gloss highlight','Return to intact familiar specimen and hold final distinction']
policy=read('src/design/brand-execution-policy.json');ep=dict(policySha256=jsha(policy),narrator=dict(provider='kokoro-local',voiceId='af_heart',deviationRationale=None),visualAuthority='story-specific',captionAuthority='story-specific',soundscapeAuthority='story-specific',universalMusicRequired=False,durationAuthority='story-led',monetizationOnlyPadding=False)
assets=[dict(id='chocolate.visual.material-cutaway',kind='original-procedural',path='src/components/ChocolateMaterial.tsx',provenance=dict(origin='Original authored projected three-dimensional chocolate geometry and separate explanatory schematics',rights='Magnivis original',notes='No third-party food footage, scientific figures, microscopy or exact molecular geometry.',evidence=b+'production-provenance.json')),dict(id='chocolate.font.humanist',kind='licensed-font',path='public/fonts/chocolate/AtkinsonHyperlegibleNext.ttf',provenance=dict(origin='Official Google Fonts distribution',rights='SIL Open Font License 1.1',notes='Unmodified variable font; weights 400/500/600.',evidence='public/fonts/chocolate/provenance.json'))]
for cue in n['cues']:assets.append(dict(id='chocolate.audio.'+cue['id'],kind='narration',path='public/'+cue['file'],provenance=dict(origin='Kokoro local af_heart at speed 0.98',rights='Apache-2.0 model',notes='Exact approved text, bounded original synthesis.',evidence='src/production/narration/chocolate.json')))
assets.append(dict(id='chocolate.sound.tactile',kind='original-sound',path='public/audio/chocolate/tactile.wav',provenance=dict(origin='Original deterministic waveform synthesis',rights='Magnivis original',notes='Sparse macroscopic illustrative handling/snap; no music or microscopic event sonification.',evidence=b+'sound-provenance.json')))
heads=['Same recipe.','Cocoa-butter fat phase','Fat structure breaks down','Crystal arrangement / larger fat-crystal network','Softer · less snap is possible','Controlled temperatures + mixing','Snap. Gloss.','Ingredients stay. Structure can change.']
beats=[]
for i,v in enumerate(a['visualPlan']):beats.append(dict(id='production-plan.chocolate-crystal-choice.beat.'+a['narrativeStructure'][i]['label'],sourceVisualPlanId=v['id'],narrativeBeatId=v['narrativeBeatId'],scriptSegmentIds=v['scriptSegmentIds'],claimIds=v['claimIds'],frames=dict(start=starts[i],end=starts[i+1]),sceneType=a['narrativeStructure'][i]['label'],objective=v['objective'],onScreenText=[dict(text=heads[i],claimIds=v['claimIds'])],animationIntent=treatments[i],transitionIntent='Stable specimen identity; purposeful sectional reveal and sequential analytical scale changes',audioIntent='Exact locked voice; analytical passages quiet, sparse illustrative tactile accents outside key words'))
p=dict(schemaVersion=1,id='production-plan.chocolate-crystal-choice.material-cutaway',revision=1,status='rendered-candidate-visual-review-required',knowledgePackage=ref(k),contentAsset=ref(a),ownerDecision=ref(decision),approvedScriptSha256=n['provenance']['approvedScriptSha256'],creativeDirection=ref(d),executionPolicy=ep,excludedClaimIds=[c['id'] for c in k['claims'] if c['id'] not in a['selectedClaimIds']],format=n['format'],safeAreaProfileId='safe-area.youtube-shorts.v2',beats=beats,assets=assets,captions=dict(file='captions/chocolate.en.vtt',captionPlanId=cp['id'],captionPlanRevision=1,captionPlanSha256=jsha(cp),generatorId='chocolate.measured-phrase-captions',generatorVersion=1,source='approved-narration-cues',designedBurnedIn=True,placement='optional-platform-track-lower-center'),reviewRequirements=['AHMET — CYCLE #3 OWNER MASTER VISUAL REVIEW','Owner must judge tactile quality, pacing and phone comprehension; local inspection is not real-device platform proof.','No master lock, platform approval or publication authorization.']);dump('src/production/plans/chocolate.json',p)
# Sparse original sound. Deterministic, no sample libraries or continuous bed.
sr=48000;duration=n['format']['durationSeconds'];samples=[0.0]*round(sr*duration);events=[(0.08,0.13,'handling'),(29.40,0.14,'handling'),(34.56,0.16,'illustrative-snap')]
for at,length,kind in events:
 for j in range(round(length*sr)):
  t=j/sr;env=math.exp(-t*(42 if kind=='illustrative-snap' else 27));noise=math.sin(j*78.233+12.9898)*43758.5453;noise=(noise%1)*2-1
  v=(noise*.11+math.sin(2*math.pi*230*t)*.05)*env if kind=='illustrative-snap' else .028*math.sin(2*math.pi*(170-200*t)*t)*env
  samples[round(at*sr)+j]+=v
with wave.open('public/audio/chocolate/tactile.wav','wb') as f:f.setnchannels(1);f.setsampwidth(2);f.setframerate(sr);f.writeframes(b''.join(struct.pack('<h',round(max(-1,min(1,v))*32767)) for v in samples))
dump(b+'sound-provenance.json',dict(generatorId='chocolate.original-tactile.v1',generatorVersion=1,path='public/audio/chocolate/tactile.wav',sha256=sha('public/audio/chocolate/tactile.wav'),rights='Magnivis original',events=[dict(at=at,duration=le,purpose=ki) for at,le,ki in events],music=False,microscopicSonification=False,recipe='scripts/generate-chocolate-production.py',createdAt=now))
dump(b+'production-provenance.json',dict(visuals='Original projected 3D slab geometry with bevels, original schematic packing tokens and network domains; illustrative not experimental.',externalVisualAssets=[],scientificImagesCopied=False,fontLicense='public/fonts/chocolate/OFL.txt',narrationModel='onnx-community/Kokoro-82M-v1.0-ONNX',narrationLicense='Apache-2.0; same inspected local model/voice as historical approved provider, not a voice audition',sound='Original deterministic waveform synthesis; no external recordings.',captionTiming='Phrase boundaries authored proportionally within measured clips, then decoded midpoint review; not claimed forced alignment.',regenerationByteIdentityProven=False))
# Optional exact-word accessibility artifact; no platform package.
def stamp(frame):ms=round(frame/30*1000);return f'{ms//3600000:02}:{ms//60000%60:02}:{ms//1000%60:02}.{ms%1000:03}'
pathlib.Path('public/captions').mkdir(exist_ok=True)
pathlib.Path('public/captions/chocolate.en.vtt').write_text('WEBVTT\n\n'+'\n\n'.join(f'{c["id"]}\n{stamp(c["startFrame"])} --> {stamp(c["endFrame"])}\n'+ '\n'.join(c['lines']) for c in cs)+'\n')
print('decision',now,'caps',len(cs),'frames',n['durationFrames'])
