import {existsSync,mkdirSync,readFileSync,writeFileSync,statSync} from 'node:fs';
import {masterApprovalDecisionSchema,applyMasterVisualApproval} from '../src/production/master-approval';
import {sha256Json,stableJson} from '../src/content-intelligence/run-schema';
import {longitudeFileHash} from '../src/production/longitude-integrity';
import {validateLongitudeV2} from '../src/production/longitude-v2-integrity';
import {productionPlanSchema} from '../src/production/schema';
import {longitudeClockV2} from '../src/content/videos/longitude-clock-v2';
import metadata from '../src/production/narration/longitude-clock-v2.json';
const dir='content-intelligence/reviews/longitude-clock-master-lock-v1';
if(existsSync(dir+'/owner-decision.json'))throw new Error('Preserve existing exact master decision.');
validateLongitudeV2();mkdirSync(dir,{recursive:true});
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8'));
const write=(p:string,v:unknown)=>writeFileSync(p,stableJson(v,2)+'\n');
const plan=productionPlanSchema.parse(read('src/production/plans/longitude-clock-v2.json'));
const receiptPath='content-intelligence/reviews/longitude-clock-production-v2/candidate-receipt.json';const receipt=read(receiptPath);
const artifact={...receipt.master};
if(artifact.sha256!=='dd4566d0202d654557ace127e74b641446bba2a0ffb996aed27946a6b27c3369'||longitudeFileHash(artifact.path)!==artifact.sha256||statSync(artifact.path).size!==artifact.bytes)throw new Error('Reviewed master identity mismatch');
const additional=['content-intelligence/reviews/longitude-clock-approved-v3/approved-claim-bindings.json','content-intelligence/reviews/longitude-clock-approved-v3/owner-decision.json','content-intelligence/reviews/longitude-clock-approved-v3/knowledge-package.approved.json','content-intelligence/reviews/longitude-clock-approved-v3/content-asset.approved.json','content-intelligence/reviews/longitude-clock-finalization-v2/visual-comprehension-contract.json','public/fonts/longitude-clock/source-serif-LICENSE.md','public/fonts/longitude-clock/source-sans-LICENSE.md','artifacts/longitude-clock-v2-manifests.json'];
const bindings={schemaVersion:1,candidate:artifact,narration:{bundleSha256:sha256Json(metadata),voice:metadata.provenance.voiceId,clips:metadata.provenance.cueArtifacts},reviewedCandidateReceipt:{path:receiptPath,sha256:longitudeFileHash(receiptPath)},sources:[...receipt.essentialBindings,...additional.map(path=>({path,sha256:longitudeFileHash(path)}))],qaArtifacts:read('artifacts/longitude-clock-v2-manifests.json').filter((a:{artifactType:string})=>a.artifactType==='qa-evidence').map((a:{localPath:string;identity:{sha256:string}})=>({path:a.localPath,sha256:a.identity.sha256}))};
write(dir+'/reviewed-bindings.json',bindings);write(dir+'/production-plan.reviewed.json',plan);write(dir+'/video-spec.reviewed.json',longitudeClockV2);
const decision=masterApprovalDecisionSchema.parse({schemaVersion:1,id:'owner-decision.longitude-clock.master-v2',revision:1,reviewer:'Ahmet Nishefci',authority:'explicit-owner-message',ownerInstruction:'Approve exact Longitude Clock Candidate V2 dd4566d0202d654557ace127e74b641446bba2a0ffb996aed27946a6b27c3369 as final locked master and authorize platform-delivery preparation only. Candidate V1 remains historical review evidence; no platform/publication approval or upload.',enteredAt:new Date().toISOString(),timeBasis:'decision-entry',ownerSuppliedReviewTimestamp:null,reviewedCommit:'e6fd1653d98a9e9049087f56262885e2a05a3018',candidateArtifactId:'longitude-clock.candidate-v2.0',masterArtifactId:'longitude-clock.locked-master.v2',artifact,knowledgePackage:plan.knowledgePackage,contentAsset:plan.contentAsset,editorialApproval:plan.ownerDecision,approvedScriptSha256:plan.approvedScriptSha256,reviewedProductionPlan:{id:plan.id,revision:plan.revision,sha256:sha256Json(plan)},captionPlan:{id:plan.captions.captionPlanId,revision:plan.captions.captionPlanRevision,sha256:plan.captions.captionPlanSha256},narrationBundleSha256:bindings.narration.bundleSha256,candidateBindings:{path:dir+'/reviewed-bindings.json',sha256:sha256Json(bindings)},platformPresentationQaAuthorized:true,platformApprovalGranted:false,publicationApprovalGranted:false});
write(dir+'/owner-decision.json',decision);
write(dir+'/production-plan.locked.json',applyMasterVisualApproval(decision,plan,bindings,'Exact Longitude Clock master approved; platform presentation review or explicit owner risk acceptance remains separate.'));
console.log(JSON.stringify({masterArtifactId:decision.masterArtifactId,enteredAt:decision.enteredAt,sha256:artifact.sha256,platformApproved:false,publicationAuthorized:false},null,2));
