import {execFileSync} from 'node:child_process';
import {mkdirSync,readFileSync,statSync,writeFileSync} from 'node:fs';
import {dirname} from 'node:path';
import {openMediaCatalog,persistMediaArtifact} from '../src/artifacts/catalog';
import {mediaArtifactSchema,mediaHash,type MediaReference} from '../src/artifacts/media';
import {inspectImage} from '../src/artifacts/inspection';
import {sha256Json} from '../src/content-intelligence/run-schema';
import {presentationProfileV3Schema,presentationEvidenceV3Schema,assessPresentationV3} from '../src/workflow/presentation';
import {cycleDeliverySchema,cycleReleaseSchema,inspectCycleRelease} from '../src/workflow/release';
import {loadCycle,persistCycleEvent} from '../src/workflow/store';
import {ownerHandoff} from '../src/workflow/handoff';
import type {RecordReference} from '../src/workflow/evidence';

const base='content-intelligence/cycles/cycle-5';const root=process.cwd();
const registry=openMediaCatalog(root);const now=new Date().toISOString();
let cycle=loadCycle(root,'cycle.5',registry);
if(cycle.stage!=='presentation'||!cycle.masterDecision||!cycle.candidate)throw new Error('Owner-approved master is required');
const read=(path:string)=>JSON.parse(readFileSync(path,'utf8'));
const ref=(path:string):RecordReference=>({path,sha256:mediaHash(path)});
const put=(name:string,data:unknown)=>{const path=`${base}/${name}.json`;mkdirSync(dirname(path),{recursive:true});writeFileSync(path,JSON.stringify(data,null,2)+'\n',{flag:'wx'});return ref(path);};
const candidate=read(cycle.candidate.path);const master=candidate.media as MediaReference;
const asset=read(`${base}/content-asset.ready.json`);
const policy=put('publication/policy-inspection-v1',{inspectedAt:now,method:'Actual source bodies inspected in session web tool; original summaries only, not full-text snapshots.',sources:[
 {url:'https://support.google.com/youtube/answer/72431?hl=en',access:'body-inspected',locator:'Add a custom Short thumbnail; Image size & resolution',finding:'Current help supports custom Shorts thumbnails in desktop Studio for verified accounts. Recommends 9:16, JPG/PNG, minimum height 640 and higher recommended resolution. Account eligibility and the actual upload UI are untested.'},
 {url:'https://support.google.com/youtube/answer/14328491?hl=en',access:'body-inspected',locator:'AI disclosure requirements and examples; How to disclose GenAI content',finding:'Meaningfully generated or altered photorealistic content requires disclosure. Non-realistic animation and production assistance are examples that do not require it. AI use is the current described setting; non-exhaustive examples do not specifically settle this stock synthetic narrator. Recommend transparent Yes plus accurate copy for this synthetic speech.'},
 {url:'https://newsroom.tiktok.com/new-labels-for-disclosing-ai-generated-content-ca?lang=en-CA',access:'body-inspected',locator:'Empowering creators',finding:'Official 2023 account of label rollout requires labeling realistic AI-generated audio, video or images; label can disclose significant AI use. Recommend enabling the available creator AI label for the stock synthetic voice. This historical announcement does not prove the current account control.'},
 {url:'https://about.fb.com/news/2024/04/metas-approach-to-labeling-ai-generated-content-and-manipulated-media/',access:'body-inspected',locator:'Takeaways; updates September 12 and July 1 2024',finding:'Meta describes AI info labels for generated audio, video and images based on detected signals or self-disclosure. Recommend available AI disclosure for synthetic narration. This newsroom account does not establish a specific Instagram/Facebook account UI.'},
 {url:'https://support.tiktok.com/en/using-tiktok/creating-videos/ai-generated-content',access:'body-unavailable',finding:'Help endpoint returned no text body. The separately inspected historical newsroom announcement supports disclosure rationale, not current account UI.'},
 {url:'https://support.tiktok.com/en/using-tiktok/creating-videos/editing-posting-and-deleting',access:'body-unavailable',finding:'No text body returned. No current custom-image entitlement or cover geometry is verified.'},
 {url:'https://help.instagram.com/2020477418166671',access:'inaccessible',finding:'No successful current official cover-body inspection. Dedicated cover is an internal presentation choice; actual live upload capability and grid crop remain unknown.'},
 ],recommendationsAreNotAppliedSettings:true,nativeGeometryMeasured:false});
const coverPath='artifacts/covers/chladni-sand-cover-v1.png';
const coverHash=mediaHash(coverPath);const sourceCommit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const cover=persistMediaArtifact(mediaArtifactSchema.parse({id:`media.${coverHash}`,sha256:coverHash,canonicalPath:coverPath,mediaType:'image/png',bytes:statSync(coverPath).size,provenance:{kind:'original-production',sourceCommit,sourceRecords:['src/chladni-cover-index.tsx',`${base}/qa/cover-layout-v1.json`,`${base}/Manrope-OFL.txt`],createdAt:statSync(coverPath).birthtime.toISOString(),creationTimeUnknownReason:null},parents:[]}),root);
const framePath='artifacts/qa-evidence/chladni-sand-v1/frame-24-19.4s.png';
const frameArtifact=registry.byHash(mediaHash(framePath));if(!frameArtifact)throw new Error('Selected master frame must already be canonical');
const frame={id:frameArtifact.id,sha256:frameArtifact.sha256};
const coverLayout=read(`${base}/qa/cover-layout-v1.json`) as {bounds:{x:number;y:number;width:number;height:number}[]};
const visual=put('qa/cover-visual-v1',{inspectedAt:now,reviewer:'Codex session — local visual inspection',media:cover,source:ref('src/chladni-cover-index.tsx'),dimensions:inspectImage(coverPath),passed:true,findings:['Actual PNG viewed enlarged: Drawn by vibration title, original settled-grain plate, illustrative-model qualification and brand are visible and separated.','The existing original qualitative analytic plate renderer supplies the diagram; no source photo, calibrated mode claim or AI bitmap is introduced. Master video remains unchanged.','Critical regions fit the central authoring envelope. Native crops remain unknown; centering is a design strategy, not measured crop safety.'],devicePass:false});
const frameVisual=put('qa/selected-frame-cover-v1',{inspectedAt:now,reviewer:'Codex session — local visual inspection',media:frame,sourceMaster:master,sourcePosition:{secondsLabel:19.4,frameSelectionApproximate:true},dimensions:inspectImage(framePath),passed:true,method:'Viewed existing exact decoded PNG. Conservative authored content envelope contains headline, diagram, qualifications and captions; not a pixel segmentation or native crop measurement.',bounds:[{x:120,y:358,width:750,height:1192}],findings:['Settled grains outline nodal lines; full-frame node label, illustrative-model/uncalibrated-tone disclosure and designed caption remain visible.','Headline and lower caption can crop on thumbnail surfaces; exact native crop is unknown. Select the corresponding settled nodal pattern frame in-app; this PNG is the exact local review reference, not a claim of a platform-extracted identical image.'],devicePass:false});
const presentation=put('publication/presentation-analysis-v1',{cycleId:cycle.id,inspectedAt:now,master,masterDecision:cycle.masterDecision,policyInspection:policy,scope:'Local exact-media review only',strategy:{youtube:'Exact master plus centered original custom cover when the verified-account desktop control is available.',tiktok:'Exact master; choose the settled nodal pattern frame in the native selector if available; existing decoded PNG is the cover reference.',instagram:'Exact master plus centered dedicated original cover for grid framing; live cover upload and crop remain unverified.',facebook:'Exact master; settled nodal pattern frame reference. Dedicated viewer and Page/feed are distinct; no measured Page/feed collision or geometry available.'},derivatives:{created:0,reason:'All existing exact-master playback samples clear provisional insets. No known collision justifies a derivative. Unknown native geometry is disclosed for owner review.'},additionalUncertainties:['YouTube: desktop/search/channel thumbnail behavior and account custom-cover eligibility untested.','TikTok: native cover selector, cropped profile/search frame and exact selected-frame identity untested.','Instagram: dedicated cover upload availability, profile/grid/feed crop and persistence untested.','Facebook: Page/feed playback crop/obstruction and native cover selection untested.','All destinations: platform processing, live settings, native-caption duplication and synthetic-audio labeling untested.'],factualCopyReview:'Copy uses only the five selected claims. It describes sand near stationary plate nodes, preserves can for different modes and setup dependence, labels the qualitative model and uncalibrated tones, and excludes air-wave/healing interpretations.',externalActionsPerformed:[],publicationAuthorized:false});
const descriptions={
 youtube:'Sand on a vibrating plate gathers near the lines that stay still. These are nodes: the moving regions bounce grains away, leaving a pattern of low motion. Different vibration modes can produce different patterns; the plate and how it is held matter.\n\nOriginal illustrative animation with synthetic narration. Grain paths and plate motion are qualitative; the tones are not calibrated to the displayed patterns.\n\nSources:\nhttps://amhistory.si.edu/science/chladni.htm\nhttps://annex.exploratorium.edu/xref/exhibits/bells.html\nhttps://www.phys.unsw.edu.au/~jw/guitar/guitarchladni_engl.html\n\nMagnivis — See the unimaginable.\n#Chladni #Physics #Sound',
 tiktok:'Vibration draws the pattern. The sand gathers near the lines that stay still: nodes. Different modes can make different patterns. Original illustrative model; synthetic narration; tones are not calibrated. #Chladni #Physics #Sound',
 instagram:'A vibrating plate leaves a map of stillness. Moving regions bounce the grains away; sand gathers near stationary nodal lines. Different vibration modes can produce different patterns, and the plate and its supports matter.\n\nOriginal illustrative animation with synthetic narration. Motion and grain paths are qualitative; tones are not calibrated to the displayed patterns.\nSources: Smithsonian, Exploratorium and UNSW Physics.\n#Chladni #Physics #Sound',
 facebook:'How can vibration draw a pattern in sand? On a vibrating plate, grains gather near stationary nodal lines. The pattern reveals where the plate barely moves. Different modes can produce different patterns, and the plate and how it is held matter.\n\nOriginal illustrative animation with synthetic narration; tones are not calibrated to the patterns. Sources: Smithsonian, Exploratorium and UNSW Physics.\n#Chladni #Physics',
};
const firstComments={
 youtube:'The pattern marks low motion in the plate, not a picture of a traveling sound wave in air. The animation is qualitative, and the tones are illustrative. Sources are in the description.',
 tiktok:'The lines are nodes of the plate. The tones here illustrate the idea; they are not calibrated to these patterns. Sources: Smithsonian, Exploratorium and UNSW Physics.',
 instagram:'A different vibration mode can change the pattern, but the plate and how it is held also matter. This is an illustrative model, not recorded laboratory footage.',
 facebook:'The sand traces low-motion lines of the plate. This is an original illustrative model with synthetic narration; the tones are not a calibrated demonstration.',
};
const platforms=['youtube','tiktok','instagram','facebook'] as const;
const deliveries=platforms.map(platform=>{
 const profileRef=ref(`${base}/profiles/${platform}.json`);const evidenceRef=ref(`${base}/preflight/${platform}.json`);
 const assessment=assessPresentationV3(read(evidenceRef.path),read(profileRef.path),master,registry,now,root);
 if(assessment.collisions.length)throw new Error('Known collision requires separate derivative');
 const surface=assessment.profile.surface;const selectedCover=platform==='youtube'||platform==='instagram'?cover:frame;
 const coverReport=selectedCover===cover?visual:frameVisual;
 const unknown=(rationale:string)=>({state:'unknown',regions:null,rationale,provenance:[]});
 const coverProfile=presentationProfileV3Schema.parse({schemaVersion:3,id:`presentation-profile.chladni.${platform}.cover-v1`,revision:1,platform,surface:`${platform}-cover`,canvas:{width:1080,height:1920},reviewedAt:now,reviewAfter:now,lifecycle:'current',compositionSafe:unknown('Full-canvas critical layout inspected; no platform-derived safe composition region measured.'),nativeExclusions:unknown('No native thumbnail overlay measurements.'),captionSafe:unknown('Static image; no platform caption/overlay measurements.'),cropSafe:unknown('No native cover crop measurements; no invented geometry.'),export:{containers:['png'],videoCodecs:['png'],audioCodecs:['not-applicable'],fps:[1],duration:{minimum:1,maximum:1},provenance:[coverReport,policy],rationale:'Static local 1080×1920 PNG cover reference; actual native upload/selection capability is untested.'}});
 const coverProfileRef=put(`publication/${platform}/cover-profile-v1`,coverProfile);
 const rects=selectedCover===cover?coverLayout.bounds:[{x:120,y:358,width:750,height:1192}];
 const coverEvidence=presentationEvidenceV3Schema.parse({schemaVersion:3,medium:'image',media:selectedCover,platform,surface:coverProfile.surface,profileSha256:sha256Json(coverProfile),inspectedAt:now,durationFrames:1,samples:rects.map(b=>({frame:0,kind:'critical',bounds:{x:b.x,y:b.y,width:b.width,height:b.height}})),coverage:{method:'all-frame-bounds',captionMidpoints:[],hookFrames:[],payoffFrames:[],disclosureFrames:[],noDisclosureReason:'Static explanatory cover; illustrative-model qualification included in inspected critical content.'},reports:[coverReport],device:{context:'not-tested',reviewer:null,os:null,appVersion:null,state:'not-tested',device:null,testedAt:null,evidence:[]}});
 const coverEvidenceRef=put(`publication/${platform}/cover-evidence-v1`,coverEvidence);
 const variant={id:`chladni-sand.variant.${platform}.v1`,revision:1,platform,surface,media:master,master,relationship:'exact-master' as const,adaptationReason:null,presentation:evidenceRef,profile:profileRef};
 const title=platform==='facebook'?'How vibration draws patterns in sand':'Why vibration draws patterns in sand';
 const metadata=put(`publication/${platform}/metadata-v1`,{cycleId:cycle.id,variantId:variant.id,platform,surface,media:master,claimIds:asset.selectedClaimIds,knowledgePackage:ref(`${base}/knowledge-package.ready.json`),contentAsset:ref(`${base}/content-asset.ready.json`),masterDecision:cycle.masterDecision,presentationAnalysis:presentation,policyInspection:policy,title,description:descriptions[platform],firstComment:firstComments[platform],hashtags:platform==='facebook'?['Chladni','Physics']:['Chladni','Physics','Sound'],tags:platform==='youtube'?['Chladni patterns','Chladni plate','nodal lines','vibration','resonance','physics of sound']:[],language:'en',cover:{media:selectedCover,method:selectedCover===cover?'custom-image-if-live-control-available':'select-corresponding-master-frame-in-app',selection:'Settled nodal pattern at approximately 19.4 seconds for frame covers',approval:'pending-publication-review'},captions:{designedBurnedIn:true,accessibilityTrack:platform==='youtube'?ref('captions/chladni-sand.en.vtt'):null,guidance:'Keep designed captions. Optional accessibility captions must retain wording; avoid adding a second visible native text layer over the designed captions.'},operatorSettings:{state:'recommendations-not-applied',destinationAccount:platform==='instagram'?'Magnivis @magnivis.media; owner confirms the live account':'Magnivis logical primary account; actual handle/remote ID must be confirmed in live UI',comments:'Enable normal comments if available; first comment prepared, not posted or pinned',reuse:'Owner chooses live remix/duet/stitch permissions; current state unknown',quality:'Keep original resolution and audio; enable highest-quality upload where offered; disable optional enhancement, trimming, templates and added text/music',visibility:'Owner public manual release only after exact publication approval',syntheticDisclosure:'Enable available AI/synthetic disclosure for stock synthetic narration; copy accurately says synthetic narration and original animation.',youtubeCategory:platform==='youtube'?'Science & Technology — story-specific physics explanation; confirm available live category':null,youtubeAudience:platform==='youtube'?'General audience; not specifically directed to children. Owner confirms the live audience selector.':null,paidPromotion:false,location:null,externalLinks:'Only inspected sources in YouTube description; no irrelevant location or promotional links.',music:'Preserve original narration and illustrative tones; no added music, optional audio effects or normalization edits.',schedule:'20:00 Kosovo local is the provisional test window, not an actual scheduled date/time.'},readiness:'prepared-for-publication-review',publicationAuthorized:false,publicationEvidence:null});
 const copyPath=`${base}/publication/${platform}/upload-copy-v1.txt`;
 writeFileSync(copyPath,`${platform.toUpperCase()} — prepared, publication approval pending\n\nTITLE${platform==='tiktok'||platform==='instagram'?' (editorial reference; use only if a separate live title field exists)':''}\n${title}\n\n${platform==='youtube'?'DESCRIPTION':'POST CAPTION'}\n${descriptions[platform]}\n\n${platform==='youtube'?'TAGS (optional, separate field)\nChladni patterns, Chladni plate, nodal lines, vibration, resonance, physics of sound\n\n':''}FIRST COMMENT (optional; not posted)\n${firstComments[platform]}\n\nOPERATOR\nUse the exact canonical MP4. Preserve original narration and designed captions. Disclose synthetic narration with the available AI control. Confirm destination account and native cover/crop options. No upload or schedule has occurred.\n`,{flag:'wx'});
 const manifest=cycleDeliverySchema.parse({schemaVersion:3,id:`delivery.cycle-5.${platform}.v1`,cycleId:cycle.id,variantSha256:sha256Json(variant),media:master,artifacts:[{role:'video',media:master},{role:'cover',media:selectedCover,presentation:coverEvidenceRef,profile:coverProfileRef}],metadata,uploadCopy:ref(copyPath),state:'prepared'});
 return {variant,manifest:put(`publication/${platform}/manifest-v1`,manifest)};
});
const release=cycleReleaseSchema.parse({schemaVersion:3,cycleId:cycle.id,deliveries});
const inspectionTime=new Date().toISOString();
const inspection=inspectCycleRelease(release,registry,inspectionTime,root);
const releaseRef=put('publication/release-v1',release);
put('publication/risk-register-v1',{cycleId:cycle.id,release:releaseRef,targetSha256:sha256Json(release),inspectionTime,acceptedByOwner:false,requiredExactPresentationUnknowns:inspection.unknowns,additionalOperationalUnknowns:read(presentation.path).additionalUncertainties,knownCollisions:[],requirement:'Owner publication decision must explicitly accept every exact listed presentation uncertainty for this release. Unknowns never become a device pass.'});
cycle=persistCycleEvent(root,cycle,{type:'complete-internal',stage:'presentation',record:releaseRef,at:new Date().toISOString()},registry);
put('publication/controller-handoff-v1',ownerHandoff(cycle,registry,root));
console.log(JSON.stringify({stage:cycle.stage,revision:cycle.revision,release:releaseRef,targetSha256:sha256Json(release),deliveries:inspection.uploads,unknownCount:inspection.unknowns.length,uniqueVideoPayloads:1,newCoverPayloads:1,publicationAuthorized:false},null,2));
