import {execFileSync} from 'node:child_process';
import {mkdirSync,readFileSync,statSync,writeFileSync} from 'node:fs';
import {dirname} from 'node:path';
import {openMediaCatalog,persistMediaArtifact} from '../src/artifacts/catalog';
import {mediaArtifactSchema,mediaHash,type MediaReference} from '../src/artifacts/media';
import {inspectImage} from '../src/artifacts/inspection';
import {sha256Json} from '../src/content-intelligence/run-schema';
import {presentationProfileV3Schema,presentationEvidenceV3Schema,assessPresentationV3} from '../src/workflow/presentation';
import {cycleDeliverySchema,cycleReleaseSchema,inspectCycleRelease} from '../src/workflow/release';
import {loadCycle,persistCycleEvent} from '../src/workflow/store';
import {ownerHandoff} from '../src/workflow/handoff';
import type {RecordReference} from '../src/workflow/evidence';

const base='content-intelligence/cycles/cycle-4';const root=process.cwd();
const registry=openMediaCatalog(root);const now=new Date().toISOString();
let cycle=loadCycle(root,'cycle.4',registry);
if(cycle.stage!=='presentation'||!cycle.masterDecision||!cycle.candidate)throw new Error('Owner-approved master is required');
const read=(path:string)=>JSON.parse(readFileSync(path,'utf8'));
const ref=(path:string):RecordReference=>({path,sha256:mediaHash(path)});
const put=(name:string,data:unknown)=>{const path=`${base}/${name}.json`;mkdirSync(dirname(path),{recursive:true});writeFileSync(path,JSON.stringify(data,null,2)+'\n',{flag:'wx'});return ref(path);};
const candidate=read(cycle.candidate.path);const master=candidate.media as MediaReference;
const asset=read(`${base}/content-asset.ready.json`);
const policy=put('publication/policy-inspection-v1',{inspectedAt:now,method:'Actual source bodies inspected in session web tool; original summaries only, not full-text snapshots.',sources:[
 {url:'https://support.google.com/youtube/answer/72431?hl=en',access:'body-inspected',locator:'Add a custom Short thumbnail; Image size & resolution',finding:'Current help supports custom Shorts thumbnails in desktop Studio for verified accounts. Recommends 9:16, JPG/PNG, minimum height 640 and higher recommended resolution. Account eligibility and the actual upload UI are untested.'},
 {url:'https://support.google.com/youtube/answer/14328491?hl=en',access:'body-inspected',locator:'AI disclosure requirements and examples; How to disclose GenAI content',finding:'Meaningfully generated or altered photorealistic content requires disclosure. Non-realistic animation and production assistance are examples that do not require it. AI use is the current described setting; non-exhaustive examples do not specifically settle this stock synthetic narrator. Recommend transparent Yes plus accurate copy for this synthetic speech.'},
 {url:'https://newsroom.tiktok.com/new-labels-for-disclosing-ai-generated-content-ca?lang=en-CA',access:'body-inspected',locator:'Empowering creators',finding:'Official 2023 account of label rollout requires labeling realistic AI-generated audio, video or images; label can disclose significant AI use. Recommend enabling the available creator AI label for the stock synthetic voice. This historical announcement does not prove the current account control.'},
 {url:'https://about.fb.com/news/2024/04/metas-approach-to-labeling-ai-generated-content-and-manipulated-media/',access:'body-inspected',locator:'Takeaways; updates September 12 and July 1 2024',finding:'Meta describes AI info labels for generated audio, video and images based on detected signals or self-disclosure. Recommend available AI disclosure for synthetic narration. This newsroom account does not establish a specific Instagram/Facebook account UI.'},
 {url:'https://support.tiktok.com/en/using-tiktok/creating-videos/editing-posting-and-deleting',access:'body-unavailable',finding:'Search snippet suggested frame selection, but no body returned. No current custom-image entitlement or cover geometry is verified.'},
 {url:'https://help.instagram.com/2020477418166671',access:'inaccessible',finding:'No successful current official cover-body inspection. Dedicated cover is an internal presentation choice; actual live upload capability and grid crop remain unknown.'},
 ],recommendationsAreNotAppliedSettings:true,nativeGeometryMeasured:false});
const coverPath='artifacts/covers/paper-half-shape-cover-v1.png';
const coverHash=mediaHash(coverPath);const sourceCommit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const cover=persistMediaArtifact(mediaArtifactSchema.parse({id:`media.${coverHash}`,sha256:coverHash,canonicalPath:coverPath,mediaType:'image/png',bytes:statSync(coverPath).size,provenance:{kind:'original-production',sourceCommit,sourceRecords:['src/paper-cover-index.tsx',`${base}/qa/cover-layout-v1.json`,`${base}/Manrope-OFL.txt`],createdAt:statSync(coverPath).birthtime.toISOString(),creationTimeUnknownReason:null},parents:[]}),root);
const framePath='artifacts/qa-evidence/paper-half-shape-v1/frame-43-49.9s.png';
const frameArtifact=registry.byHash(mediaHash(framePath));if(!frameArtifact)throw new Error('Selected master frame must already be canonical');
const frame={id:frameArtifact.id,sha256:frameArtifact.sha256};
const coverLayout=read(`${base}/qa/cover-layout-v1.json`) as {bounds:{x:number;y:number;width:number;height:number}[]};
const visual=put('qa/cover-visual-v1',{inspectedAt:now,reviewer:'Codex session — local visual inspection',media:cover,source:ref('src/paper-cover-index.tsx'),dimensions:inspectImage(coverPath),passed:true,findings:['Actual PNG viewed enlarged: two-line title, original nested paper diagram, qualification and brand are visible and separated.','Ideal parent has ratio √2; rotated half has the same ratio and half the area. No paper photo, source figure or AI bitmap used.','Critical regions fit the central authoring envelope. Native crops remain unknown; centering is a design strategy, not measured crop safety.'],devicePass:false});
const frameVisual=put('qa/selected-frame-cover-v1',{inspectedAt:now,reviewer:'Codex session — local visual inspection',media:frame,sourceMaster:master,sourcePosition:{secondsLabel:49.9,frameSelectionApproximate:true},dimensions:inspectImage(framePath),passed:true,method:'Viewed existing exact decoded PNG. Conservative authored content envelope contains headline, diagram, qualifications and captions; not a pixel segmentation or native crop measurement.',bounds:[{x:120,y:273,width:750,height:1261}],findings:['Final paper half and parent outline show the proportions/area payoff. Ideal model qualification remains visible in the full canvas.','Headline and lower caption can crop on thumbnail surfaces; exact native crop is unknown. Select the corresponding terminal payoff frame in-app; this PNG is the exact local review reference, not a claim of a platform-extracted identical image.'],devicePass:false});
const presentation=put('publication/presentation-analysis-v1',{cycleId:cycle.id,inspectedAt:now,master,masterDecision:cycle.masterDecision,policyInspection:policy,scope:'Local exact-media review only',strategy:{youtube:'Exact master plus centered original custom cover when the verified-account desktop control is available.',tiktok:'Exact master; choose the terminal payoff frame in the native selector if available; existing decoded PNG is the cover reference.',instagram:'Exact master plus centered dedicated original cover for grid framing; live cover upload and crop remain unverified.',facebook:'Exact master; terminal payoff frame reference. Dedicated viewer and Page/feed are distinct; no measured Page/feed collision or geometry available.'},derivatives:{created:0,reason:'All existing exact-master playback samples clear provisional insets. No known collision justifies a derivative. Unknown native geometry is disclosed for owner review.'},additionalUncertainties:['YouTube: desktop/search/channel thumbnail behavior and account custom-cover eligibility untested.','TikTok: native cover selector, cropped profile/search frame and exact selected-frame identity untested.','Instagram: dedicated cover upload availability, profile/grid/feed crop and persistence untested.','Facebook: Page/feed playback crop/obstruction and native cover selection untested.','All destinations: platform processing, live settings, native-caption duplication and synthetic-audio labeling untested.'],factualCopyReview:'All copy uses only the six selected claims; preserves ideal-model/rounded physical-size caveat and length-versus-area distinction.',externalActionsPerformed:[],publicationAuthorized:false});
const descriptions={
 youtube:'A4 has a hidden geometric rule. In the ideal A-series model, halving the long side and rotating the half preserves a 1:√2 ratio. An A3 design scales to A4 at about 70.7% of each length, while its area halves. Real paper dimensions are rounded to whole millimetres.\n\nOriginal explanatory animation with synthetic narration.\n\nSources:\nhttps://nrich.maths.org/problems/fit-photocopying\nhttps://www.din.de/de/din-und-seine-partner/presse/mitteilungen/herzlichen-glueckwunsch-a4--878664\nISO 216:2007 public preview was partially inspected; full standard not acquired.\n\nMagnivis — See the unimaginable.\n#Geometry #Design #A4',
 tiktok:'Cut A4 in half. Turn it. Almost the same shape. The ideal A-series ratio is 1:√2; real sizes are rounded to whole millimetres. Synthetic narration; original explanatory animation. #Geometry #Design #A4',
 instagram:'An everyday rectangle has a hidden rule. In the ideal A-series system, a rotated half keeps the same proportions: 1:√2. Each length becomes about 70.7% of the original; the area halves. Real paper sizes are rounded to whole millimetres.\n\nSave this for the next time you resize a design.\nOriginal explanatory animation with synthetic narration. Sources: Cambridge NRICH, “Fit for Photocopying”; DIN, “Herzlichen Glückwunsch A4!”\n#Geometry #Design #A4',
 facebook:'Why does A4 almost keep its shape when you cut it in half and turn it? The ideal A-series ratio is 1:√2. Shrinking an A3 design to A4 reduces each length to about 70.7%, while the area halves. Real paper dimensions are rounded to whole millimetres.\n\nOriginal explanatory animation with synthetic narration. Sources: Cambridge NRICH, “Fit for Photocopying”; DIN, “Herzlichen Glückwunsch A4!”',
};
const platforms=['youtube','tiktok','instagram','facebook'] as const;
const deliveries=platforms.map(platform=>{
 const profileRef=ref(`${base}/profiles/${platform}.json`);const evidenceRef=ref(`${base}/preflight/${platform}.json`);
 const assessment=assessPresentationV3(read(evidenceRef.path),read(profileRef.path),master,registry,now,root);
 if(assessment.collisions.length)throw new Error('Known collision requires separate derivative');
 const surface=assessment.profile.surface;const selectedCover=platform==='youtube'||platform==='instagram'?cover:frame;
 const coverReport=selectedCover===cover?visual:frameVisual;
 const unknown=(rationale:string)=>({state:'unknown',regions:null,rationale,provenance:[]});
 const coverProfile=presentationProfileV3Schema.parse({schemaVersion:3,id:`presentation-profile.paper.${platform}.cover-v1`,revision:1,platform,surface:`${platform}-cover`,canvas:{width:1080,height:1920},reviewedAt:now,reviewAfter:now,lifecycle:'current',compositionSafe:unknown('Full-canvas critical layout inspected; no platform-derived safe composition region measured.'),nativeExclusions:unknown('No native thumbnail overlay measurements.'),captionSafe:unknown('Static image; no platform caption/overlay measurements.'),cropSafe:unknown('No native cover crop measurements; no invented geometry.'),export:{containers:['png'],videoCodecs:['png'],audioCodecs:['not-applicable'],fps:[1],duration:{minimum:1,maximum:1},provenance:[coverReport,policy],rationale:'Static local 1080×1920 PNG cover reference; actual native upload/selection capability is untested.'}});
 const coverProfileRef=put(`publication/${platform}/cover-profile-v1`,coverProfile);
 const rects=selectedCover===cover?coverLayout.bounds:[{x:120,y:273,width:750,height:1261}];
 const coverEvidence=presentationEvidenceV3Schema.parse({schemaVersion:3,medium:'image',media:selectedCover,platform,surface:coverProfile.surface,profileSha256:sha256Json(coverProfile),inspectedAt:now,durationFrames:1,samples:rects.map(b=>({frame:0,kind:'critical',bounds:{x:b.x,y:b.y,width:b.width,height:b.height}})),coverage:{method:'all-frame-bounds',captionMidpoints:[],hookFrames:[],payoffFrames:[],disclosureFrames:[],noDisclosureReason:'Static explanatory cover; ideal-model qualification included in inspected critical content.'},reports:[coverReport],device:{context:'not-tested',reviewer:null,os:null,appVersion:null,state:'not-tested',device:null,testedAt:null,evidence:[]}});
 const coverEvidenceRef=put(`publication/${platform}/cover-evidence-v1`,coverEvidence);
 const variant={id:`paper-half-shape.variant.${platform}.v1`,revision:1,platform,surface,media:master,master,relationship:'exact-master' as const,adaptationReason:null,presentation:evidenceRef,profile:profileRef};
 const title=platform==='facebook'?'The hidden geometry of A4 paper':'Why A4 almost keeps its shape when cut in half';
 const metadata=put(`publication/${platform}/metadata-v1`,{cycleId:cycle.id,variantId:variant.id,platform,surface,media:master,claimIds:asset.selectedClaimIds,knowledgePackage:ref(`${base}/knowledge-package.ready.json`),contentAsset:ref(`${base}/content-asset.ready.json`),masterDecision:cycle.masterDecision,presentationAnalysis:presentation,policyInspection:policy,title,description:descriptions[platform],language:'en',cover:{media:selectedCover,method:selectedCover===cover?'custom-image-if-live-control-available':'select-corresponding-master-frame-in-app',selection:'Terminal payoff at approximately 49.9 seconds for frame covers',approval:'pending-publication-review'},captions:{designedBurnedIn:true,accessibilityTrack:platform==='youtube'?ref('captions/paper-half-shape.en.vtt'):null,guidance:'Keep designed captions. Optional accessibility captions must retain wording; avoid adding a second visible native text layer over the designed captions.'},operatorSettings:{state:'recommendations-not-applied',destinationAccount:'Owner confirms actual Magnivis destination at upload; no account session inspected',visibility:'Owner public manual release only after exact publication approval',syntheticDisclosure:'Enable available AI/synthetic disclosure for stock synthetic narration; copy accurately says synthetic narration and original animation.',youtubeCategory:platform==='youtube'?'Education — story-specific mathematical explanation':null,youtubeAudience:platform==='youtube'?'General audience; not specifically directed to children. Owner confirms the live audience selector.':null,paidPromotion:false,location:null,externalLinks:'Only inspected sources in YouTube description; no irrelevant location or promotional links.',music:'Preserve original synthetic narration; no additional music or automatic loudness edits.',schedule:'20:00 Kosovo local is the provisional test window, not an actual scheduled date/time.'},readiness:'prepared-for-publication-review',publicationAuthorized:false,publicationEvidence:null});
 const copyPath=`${base}/publication/${platform}/upload-copy-v1.txt`;
 writeFileSync(copyPath,`${platform.toUpperCase()} — prepared, publication approval pending\n\nTITLE${platform==='tiktok'||platform==='instagram'?' (editorial reference; use only if a separate live title field exists)':''}\n${title}\n\n${platform==='youtube'?'DESCRIPTION':'POST CAPTION'}\n${descriptions[platform]}\n\nOPERATOR\nUse the exact canonical MP4. Preserve original narration and designed captions. Disclose synthetic narration with the available AI control. Confirm destination account and native cover/crop options. No upload or schedule has occurred.\n`,{flag:'wx'});
 const manifest=cycleDeliverySchema.parse({schemaVersion:3,id:`delivery.cycle-4.${platform}.v1`,cycleId:cycle.id,variantSha256:sha256Json(variant),media:master,artifacts:[{role:'video',media:master},{role:'cover',media:selectedCover,presentation:coverEvidenceRef,profile:coverProfileRef}],metadata,uploadCopy:ref(copyPath),state:'prepared'});
 return {variant,manifest:put(`publication/${platform}/manifest-v1`,manifest)};
});
const release=cycleReleaseSchema.parse({schemaVersion:3,cycleId:cycle.id,deliveries});
const inspectionTime=new Date().toISOString();
const inspection=inspectCycleRelease(release,registry,inspectionTime,root);
const releaseRef=put('publication/release-v1',release);
put('publication/risk-register-v1',{cycleId:cycle.id,release:releaseRef,targetSha256:sha256Json(release),inspectionTime,acceptedByOwner:false,requiredExactPresentationUnknowns:inspection.unknowns,additionalOperationalUnknowns:read(presentation.path).additionalUncertainties,knownCollisions:[],requirement:'Owner publication decision must explicitly accept every exact listed presentation uncertainty for this release. Unknowns never become a device pass.'});
cycle=persistCycleEvent(root,cycle,{type:'complete-internal',stage:'presentation',record:releaseRef,at:new Date().toISOString()},registry);
put('publication/controller-handoff-v1',ownerHandoff(cycle,registry,root));
console.log(JSON.stringify({stage:cycle.stage,revision:cycle.revision,release:releaseRef,targetSha256:sha256Json(release),deliveries:inspection.uploads,unknownCount:inspection.unknowns.length,uniqueVideoPayloads:1,newCoverPayloads:1,publicationAuthorized:false},null,2));
