import {existsSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {dirname} from 'node:path';
import {loadMediaRegistry,mediaHash} from '../src/artifacts/media';
import {sha256Json} from '../src/content-intelligence/run-schema';
import {knowledgePackageSchema} from '../src/knowledge/schema';
import {contentAssetSchema} from '../src/content-assets/schema';
import {verifyInternalEditorial} from '../src/workflow/editorial';
import {recentApprovedVisualWorks} from '../src/content-assets/visual-convergence';
import {loadCycle,persistCycleEvent} from '../src/workflow/store';
import type {RecordReference} from '../src/workflow/evidence';
const base='content-intelligence/cycles/cycle-6',now=new Date().toISOString();
const ref=(path:string):RecordReference=>({path,sha256:mediaHash(path)});
const put=(name:string,data:unknown)=>{const path=`${base}/${name}.json`;if(existsSync(path))return ref(path);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,JSON.stringify(data,null,2)+'\n',{flag:'wx'});return ref(path);};
const advance=(stage:'discovery'|'editorial'|'creative',record:RecordReference)=>{const registry=loadMediaRegistry();persistCycleEvent(process.cwd(),loadCycle(process.cwd(),'cycle.6',registry),{type:'complete-internal',stage,record,at:new Date().toISOString()},registry);};
const data=JSON.parse(readFileSync(`${base}/authoring-data.json`,'utf8')) as {sources:{key:string;organization:string;title:string;type:'government'|'museum';url:string;locator:string;summary:string;limits:string[]}[];definitions:[string,string,string[],string][];lines:[string,string[]][];objectives:string[]};
const id='tally-fire',aid=`${id}.asset.disposal`,cid=(key:string)=>`${id}.claim.${key}`;
const works=recentApprovedVisualWorks(now,aid);
const search=ref(`${base}/discovery-search.json`);
const options=[
 ['tally-fire','Disposing of wooden receipts set Parliament on fire',['historical-records','institutional-decisions'],'How can clearing out old accounts destroy Parliament?','premise-led','An ordinary disposal task has a disproportionate documented consequence; no prior domain interest needed.','Start with fire, rewind to matching receipts, follow the furnace decision and warning signs, return to surviving Hall.','Selected: powerful causal narrative independent of visual tools.'],
 ['whale-earwax','Earwax preserves a whale’s lifetime chemical history',['marine-biology','environmental-archives'],'What can a lifetime of earwax tell scientists?','premise-led','An apparently disposable material becomes a biological archive.','Layer formation, sectioning and chemical profile with one-whale study scope.','Strong rival; specific hormone interpretation and transfer require deeper primary study audit.'],
 ['closed-scroll','Reading a burned scroll without opening it',['cultural-preservation','computational-imaging'],'How do you read a scroll too fragile to open?','premise-led','Clear impossible-seeming task with a real technological answer.','Scan layers, track surfaces, flatten digitally, recover ink with ink-specific qualifications.','Strong rival; distinct ink/scan methods across scrolls must not be merged into one magic process.'],
 ['sailing-stones','Thin ice moves rocks across a desert lake bed',['geology','field-observation'],'What moves the rocks that leave tracks in the desert?','premise-led','Visible tracks demand a cause; thin ice in hot Death Valley is surprising.','Reconstruct shallow pond, frozen sheet, wind-driven panel and slow rock motion.','Strong credible rival; selected historical story has an equally immediate premise and richer decision/consequence route.'],
 ['crystal-skull','Tool marks reveal a crystal skull’s modern manufacture',['archaeology','artifact-authentication'],'How did tiny tool marks expose a supposedly ancient skull?','premise-led','Object authenticity mystery resolves through material evidence.','Catalogue identity, microscopic wheel marks, scoped conclusion without supernatural framing.','Promising; requires exact object-specific analytical paper, not general all-skulls verdict.'],
 ['flat-disc','A recording’s shape changes how it reaches people',['media-history','manufacturing'],'Why did flat records displace cylinders?','context-led','Interest needs initial context about reproduction and distribution.','Compare copying workflows, avoid lone-inventor simplification.','Legitimate but this initial premise less arresting than fire/scroll/earwax stories.'],
] as const;
if(loadCycle(process.cwd(),'cycle.6',loadMediaRegistry()).stage==='discovery')advance('discovery',put('topic-selection',{schemaVersion:3,cycleId:'cycle.6',method:'qualitative-open-world-comparison',searchRecord:search,searchBreadth:'Fresh broad institutional discovery across objects/culture, nature, behavioral research, space, money, archives and documented history; six substantive leads compared after discovery. Reservoir and recent topic history inspected without preferred domain or ordered queue.',classificationAfterDiscovery:true,historyReviewed:works.map(w=>w.approval),analyticsInfluence:'provenance-bearing-signals-not-category-rules',convenienceAdvantageRejected:true,selectionStandard:'cold-audience-curiosity.v1',poolReview:{adequateOpportunityFound:true,rationale:'Fire caused by disposal of receipts is compelling in its own right, not simply the least weak pool entry; scroll and earwax also supply strong legitimate questions. No shock claim or domain preference required.',nextSearchChange:null},candidates:options.map(c=>({id:c[0],subject:c[1],domains:[...c[2]],novelty:'No prior selected story covers this central question. Recent physical explainers do not impose a domain rotation.',evidenceFeasibility:c[0]==='tally-fire'?'Four institutional bodies inspected, including historical PDF and separate museum split-record account.':'Institutional lead acquired; selected claim-level source review still required.',explanatoryPayoff:c[6],visualPotential:'Story-specific original reconstruction or material demonstration; no existing renderer grants priority.',audienceCuriosity:c[5],productionFeasibility:'New bespoke scenes may be needed; local capabilities are feasible but not a selection advantage.',portfolioDiversity:'Classified after discovery; no quotas, forced rotation or familiar-domain preference.',comparison:c[7],disposition:'eligible',evidence:[search],limitations:['Feasibility is not verification. Bounded qualitative selection is not predicted performance.'],curiosityReview:{honestPremise:c[3],coldAudienceReason:c[5],interestOrigin:c[4],storyRoute:c[6],truthBoundary:{state:'credible-lead',rationale:c[0]==='tally-fire'?'Documented fire causation; must distinguish old Palace and survival, avoid malicious intent or faulty-records framing.':'Institutional lead supports a bounded investigation; no unsupported superlative or mystery certainty.'},opportunityJudgment:{sufficient:c[0]!=='flat-disc',rationale:c[7]},shareability:null}})),selectedId:id,outcome:'selected',rationale:'Documented catastrophic consequence of an everyday administrative task creates immediate cold-viewer curiosity. Split receipts explain the unusual fuel before the disposal decision resolves the fire. Source sufficiency is inspectable; no research/rendering convenience, historical domain preference or scheduling-derived metrics decide selection.'}));
const sourceInfo=data.sources;
const evidenceRecords=sourceInfo.map(s=>put(`sources/${s.key}-inspection`,{sourceId:`source.tally-fire.${s.key}`,url:s.url,retrievedAt:now,accessStatus:'inspected',inspectedText:s.summary,acquisition:'manual-source-inspection',inspectionMethod:'Actual body opened in session web tool; original bounded inspection summary and section locator. Not a stored HTTP body, full paper or snippet-only verification.',locator:s.locator,limitations:s.limits}));
const definitions=data.definitions;
const claims=definitions.map(d=>({id:cid(d[0]),type:'qualitative' as const,statement:d[1],verificationStatus:['all-destroyed'].includes(d[0])?'unverified' as const:'supported' as const,caveats:[d[3]],evidence:d[2].map(k=>({sourceId:`source.tally-fire.${k}`,locator:sourceInfo.find(s=>s.key===k)!.locator,notes:`${d[3]} Assessment limited to documented historical scope.`}))}));
const lines=data.lines;
const selected=claims.filter(c=>c.verificationStatus==='supported').map(c=>c.id);
const pkg=knowledgePackageSchema.parse({id,revision:1,topic:'The wooden receipts behind Parliament’s 1834 fire',centralQuestion:'How did disposing of obsolete wooden receipts help destroy the old Palace of Westminster?',taxonomy:{pillar:'history-stories',domains:['institutional-history','accounting','fire-history'],topics:['tally-sticks','palace-of-westminster','disposal-decisions']},timeliness:'evergreen',thesis:'A record system became obsolete; furnace disposal of its wooden leftovers caused a chimney fire that spread through the old Palace.',viewerPayoff:'Understand matching split tally receipts and the documented disposal decision that led to catastrophic fire.',sources:sourceInfo.map(s=>({id:`source.tally-fire.${s.key}`,organization:s.organization,title:s.title,sourceType:s.type,url:s.url,retrieved:now.slice(0,10),notes:s.limits.join(' ')})),claims,caveats:[{id:`${id}.caveat.reconstruction`,statement:'Original simplified reconstruction, not eyewitness footage, surveyed architecture or a combustion simulation. Other portions besides Hall survived.',claimIds:selected}],hooks:[{id:`${id}.hook.receipts`,archetype:'documented-consequence',text:lines[0]![0],viewerPromise:'Explain how clearing old receipts could cause a catastrophic fire.',claimIds:[cid('receipts')]},{id:`${id}.hook.choice`,archetype:'causal-question',text:'How can throwing away receipts destroy a parliament?',viewerPromise:'Follow the physical disposal decision and its consequences.',claimIds:[cid('receipts'),cid('furnaces')]}],narrativeOpportunities:[{id:`${id}.narrative.disposal`,title:'Receipts to ruin',description:'Rewind from outcome to records; follow disposal and warning signs back to consequence.',claimIds:selected}],visualOpportunities:[{id:`${id}.visual.sequence`,title:'Record, furnace, floor, aftermath',description:'Original split-record macro and architectural cutaway, disclosed qualitative reconstruction.',claimIds:selected}],relatedQuestions:['How did matching tallies resist alteration?','How was the old Palace rebuilt?'],followUpOpportunities:['A separately evidenced story of physical authentication or rebuilding.'],editorialStatus:'review'});
const objectives=data.objectives;
const asset=contentAssetSchema.parse({id:aid,revision:1,knowledgePackageId:id,assetType:'short-form-video',editorialPurpose:pkg.viewerPayoff,storyAngle:'An everyday disposal decision became a catastrophe.',hookId:pkg.hooks[0]!.id,selectedClaimIds:selected,durationIntentSeconds:{minimum:40,maximum:75},script:{language:'en',segments:lines.map((l,i)=>({id:`${aid}.script.${i+1}`,type:'factual',text:l[0],claimIds:l[1].map(cid)}))},narrativeStructure:lines.map((_,i)=>({id:`${aid}.beat.${i+1}`,label:['outcome','wooden-receipts','matching-record','obsolete-loads','disposal','warnings','breakthrough','survivors','choice'][i],purpose:objectives[i],scriptSegmentIds:[`${aid}.script.${i+1}`]})),visualPlan:lines.map((l,i)=>({id:`${aid}.visual.${i+1}`,narrativeBeatId:`${aid}.beat.${i+1}`,objective:objectives[i],visualType:'bespoke',suggestedPrimitive:'bespoke',scriptSegmentIds:[`${aid}.script.${i+1}`],claimIds:l[1].map(cid),notes:'Original schematic reconstruction; not exact architecture, measured flame spread, authentic currency notches or an actual surviving 1834 stick. No modern clock tower.'})),narrationPlan:{mode:'narrated',voiceDirection:'Current primary af_heart; direct intrigued opening, measured explanation, restrained gravity at fire and survival.',pronunciationNotes:['1834 read as eighteen thirty-four','Westminster; House of Lords; chimney; tally']},editorialStatus:'editorial-review'});
const review={schemaVersion:3,cycleId:'cycle.6',topicCandidateId:id,enteredAt:now,reviewer:'Codex session — internal evidence review, not Ahmet',packageSha256:sha256Json(pkg),assetSha256:sha256Json(asset),scriptSha256:sha256Json(asset.script),inspections:sourceInfo.map((s,i)=>({sourceId:`source.tally-fire.${s.key}`,accessStatus:'inspected',identityConfirmed:true,evidenceLocations:[s.locator],supportsClaimIds:claims.filter(c=>c.verificationStatus==='supported'&&c.evidence.some(e=>e.sourceId===`source.tally-fire.${s.key}`)).map(c=>c.id),limitations:s.limits,inspectedEvidence:evidenceRecords[i],sourceQualityRationale:s.key==='boe'?'Museum object corroborates matching split-record mechanism.':'Institutional archival/historical account; Parliament records correlated, not independent corroboration.'})),claims:claims.map(c=>({id:c.id,statementSha256:sha256Json(c.statement),disposition:c.verificationStatus==='supported'?'verify':'exclude',rationale:c.verificationStatus==='supported'?'Exact statement traced to inspected bodies; historical scope and reconstruction limits preserved.':'Unsupported or false extension explicitly excluded; cannot enter script or visual.',evidence:c.verificationStatus==='supported'?c.evidence.map(e=>({sourceId:e.sourceId,locator:e.locator,assessment:e.notes,sufficientForWording:true})):[],qualificationsPreserved:true})),misconceptionSafeguards:['Old Palace in 1834, not present Victorian Palace or Big Ben.','Both chambers destroyed; Hall and other portions survived.','Disposal caused fire; wooden accounting not inherently faulty or malicious.','Chimney/furnace/floor drawings are schematics, no explosion or measured spread.'],comprehensionReview:'Outcome earns attention; physical split record explains receipts; obsolete loads lead to furnace decision, warnings and destruction; survived Hall preserves scope.',rightsReview:'Original code/synthesis and licensed existing fonts/local Kokoro only. Institutional images, photographs, diagrams, video and audio are consultation evidence only. No new paid service, cost deviation, purchase or infrastructure.',careAssessment:{state:'routine',rationale:'Documented nonsensitive institutional history; adequate central evidence, no sensitive judgment, personal advice or unresolved rights.'},exceptionalConditions:[]};
put('draft-package',pkg);put('draft-asset',asset);put('internal-editorial-review',review);advance('editorial',put('editorial-receipt',{draftPackage:pkg,draftAsset:asset,review}));
const ready=verifyInternalEditorial(review,pkg,asset);put('knowledge-package.ready',ready.knowledgePackage);put('content-asset.ready',ready.contentAsset);
console.log('Cycle #6 editorial ready. Creative review follows actual rendered inspection.');
