import {longitudePreparedDeliveryDependencies} from './longitude-prepared-delivery';
import {existsSync,mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {generateDeliveryPackage,validateDeliveryPackage} from './delivery-packages';
import {longitudePlatformVariants} from '../src/platform-variants/variants/longitude-clock';
import {validateLongitudeLockedMaster} from '../src/production/longitude-master-integrity';
import {longitudeFileHash} from '../src/production/longitude-integrity';
import {stableJson,sha256Json} from '../src/content-intelligence/run-schema';
const dir='content-intelligence/reviews/longitude-clock-platform-v1';
if(existsSync(dir+'/delivery-index.json'))throw new Error('Preserve durable delivery revision; do not overwrite.');
const master=validateLongitudeLockedMaster();const generatedAt=new Date().toISOString();mkdirSync(dir,{recursive:true});
const packages=longitudePlatformVariants.map(v=>generateDeliveryPackage({variantId:v.id,outputRoot:'artifacts/deliveries/longitude-clock-v1',generatedAt,dependencies:longitudePreparedDeliveryDependencies}));
for(const p of packages)validateDeliveryPackage(p.directory,longitudePreparedDeliveryDependencies);
writeFileSync(dir+'/platform-variants.json',stableJson(longitudePlatformVariants,2)+'\n');
writeFileSync(dir+'/delivery-index.json',stableJson({schemaVersion:1,generatedAt,master,packages:packages.map(p=>({directory:p.directory.replace(process.cwd()+'/',''),deliveryId:p.manifest.deliveryId,platform:p.manifest.destination.platform,state:p.manifest.state,manifestSha256:sha256Json(p.manifest),manifestFileSha256:longitudeFileHash(p.directory+'/manifest.json'),uploadVideoSha256:longitudeFileHash(p.directory+'/video.mp4')})),platformApproved:false,publicationAuthorized:false},2)+'\n');
const copy=JSON.parse(readFileSync(dir+'/platform-copy.json','utf8'));const covers=JSON.parse(readFileSync(dir+'/cover-evaluation.json','utf8'));
// Separate readiness records, never native PublicationRecord or MetricSnapshot instances.
const intake={schemaVersion:1,purpose:'prepared-intake-not-publication-record',recordedAt:generatedAt,publicationAuthorized:false,entries:packages.map(p=>({platform:p.manifest.destination.platform,preparedVariant:p.manifest.source.platformVariant,preparedDelivery:{id:p.manifest.deliveryId,path:p.directory.replace(process.cwd()+'/',''),manifestSha256:longitudeFileHash(p.directory+'/manifest.json')},masterSha256:master.artifact.sha256,publicUrl:null,platformContentId:null,publishedAt:null,publishedOn:null,actualUploadedVariant:null,actualUploadedDelivery:null,ownerPresentationResult:null,commentState:'unknown',uploadSettings:'unknown',instruction:'After separate authorization and actual manual publication, bind the exact release variant/delivery, capture actual URL/ID/time if known; never copy these pending preparation references into a false published record.'}))};
writeFileSync(dir+'/publication-evidence-intake.json',stableJson(intake,2)+'\n');
writeFileSync(dir+'/analytics-readiness.json',stableJson({schemaVersion:1,purpose:'native-metric-intake-guidance-not-metric-snapshot',metricSnapshots:[],publicationRecords:[],platforms:['youtube','tiktok','instagram','facebook'],captureAt:null,observationWindow:null,instructions:['Bind actual PublicationRecord first.','Preserve each native metric name/definition, source/screenshot/export and actual capture time/window.','Do not normalize views/engaged views/reach across platforms or invent zero metrics.','Record unknowns as unknown; no inference from Phantom Traffic.']},2)+'\n');
const checklist=['# Longitude Clock — manual publication checklist','', '**STOP: no upload, scheduling or publication authorized.** Review packages first, then Ahmet chooses either separately authorized private/device preview or explicit presentation-risk acceptance with publication authorization. Neither decision is inferred.','',`Exact locked upload SHA-256: ${master.artifact.sha256}`,'','Common settings: preserve original audio and burned-in captions; no added music/filter/effect/auto-reframing/enhancement; highest quality/HD when offered; native visible captions off to avoid duplication; comments on with normal moderation; remix/reuse/download/duet/stitch off initially where available; auto cross-post off; no paid partnership, location or link. Synthetic audio disclosure recommended on; confirm live wording. No age restriction recommended; audience is general education, not child-directed. Public visibility only after explicit publication authorization.',''];
for(const p of packages){const platform=p.manifest.destination.platform,c=copy[platform];checklist.push(`## ${platform.toUpperCase()}`,'',`File: ${p.directory.replace(process.cwd()+'/','')}/video.mp4`,'',...(c.title?[`Title: ${c.title}`,'']:[]),...(c.description?['Description:',c.description,'']:[]),...(c.caption?['Caption:',c.caption,'']:[]),`Hashtags: ${c.hashtags.map((s:string)=>'#'+s).join(' ')}`,'',`Keywords/tags ${platform==='facebook'?'(only if a separate Tags field exists)':platform==='youtube'?'(optional Studio tags)':'(none recommended)'}: ${c.keywords.join(', ')||'none'}`,'',`Optional first comment: ${c.firstComment}`,'',`Cover: ${covers[platform].reason} ${platform==='instagram'?p.directory.replace(process.cwd()+'/','')+'/cover.png':`Reference ${covers[platform].time}s; ${covers[platform].path}`}`,'',platform==='youtube'?'YouTube: English; Education category if offered; Not made for kids based on general audience. Confirm thumbnail/AI-use/reuse controls in actual account. Check Shorts mobile and desktop separately.':platform==='tiktok'?'TikTok: Only Me for an explicitly authorized private test; Public only after release authorization. AI-generated-content toggle on; verify cover/top/right/bottom controls.':platform==='instagram'?'Instagram: select cover.png; preview Reel and profile/grid crops separately; share-to-feed only after crop review or explicit risk acceptance. Facebook auto-sharing off. Private-account/draft or preview controls differ: confirm available workflow before any external action.':'Facebook: select the intended Magnivis Page/account manually; review dedicated Reel and Page/feed separately; use title and Tags field only if actually available. Instagram auto-sharing off. Check audience/privacy options live.','', 'After actual publication: capture URL and platform ID when available, actual date/time if known, exact released variant and manifest hash, presentation result/context and comment state. Unknowns stay unknown.','');}
writeFileSync(dir+'/publication-checklist.md',checklist.join('\n').trimEnd()+'\n');
console.log(packages.map(p=>({path:p.directory,state:p.manifest.state,publishEligible:p.manifest.publishEligible})));
