import {existsSync as requireExists,mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {loadMediaRegistry,mediaHash} from '../src/artifacts/media';
import {sha256Json} from '../src/content-intelligence/run-schema';
import {loadCycle,persistCycleEvent} from '../src/workflow/store';
import {ownerDecisionSchema} from '../src/workflow/evidence';
import {validateCreativeDirection} from '../src/content-assets/creative-direction-integrity';
import {creativeDirectionSchema} from '../src/content-assets/creative-direction';
import {knowledgePackageSchema} from '../src/knowledge/schema';
import {contentAssetSchema} from '../src/content-assets/schema';
import {validateAdaptiveCaptionPlan} from '../src/captions/adaptive-plan';
import {validateInternalProductionPlanReferences,productionPlanV3Schema} from '../src/production/schema';
import narration from '../src/production/narration/vermeer-forgery.json';
const base='content-intelligence/cycles/cycle-11/revision-v2',old='content-intelligence/cycles/cycle-11',now=new Date().toISOString(),registry=loadMediaRegistry();
const read=(p:string):unknown=>JSON.parse(readFileSync(p,'utf8')),ref=(path:string)=>({path,sha256:mediaHash(path)});
const put=(n:string,d:unknown)=>{const path=`${base}/${n}.json`;if(process.argv.includes('--resume')&&requireExists(path))return ref(path);mkdirSync(path.slice(0,path.lastIndexOf('/')),{recursive:true});writeFileSync(path,JSON.stringify(d,null,2)+'\n',{flag:'wx'});return ref(path);};
let cycle=loadCycle(process.cwd(),'cycle.11',registry);if(!process.argv.includes('--resume')){if(cycle.stage!=='master-review'||cycle.revision!==8||!cycle.candidate)throw new Error('Unexpected V1 state');
put('preserved-v1-state',cycle);
put('preservation-bindings',{files:[cycle.candidate.path,'artifacts/masters/vermeer-forgery-cycle11-candidate-v1.mp4',`${old}/knowledge-package.ready.json`,`${old}/content-asset.ready.json`,'src/production/narration/vermeer-forgery.json','src/captions/plans/vermeer-forgery.json','src/production/plans/vermeer-forgery.json',...narration.cues.map(c=>`public/${c.file}`)].map(ref),scope:'Same approved premise, exact verified script, source qualifications, narrator, audio, timing and legacy inputs/media preserved.'});
const decision=put('owner-master-revision',ownerDecisionSchema.parse({schemaVersion:3,id:'owner-decision.cycle-11.master-revision-v2',revision:1,gate:'master-review',cycleId:'cycle.11',targetSha256:sha256Json(read(cycle.candidate.path)),decision:'revise',enteredAt:now,suppliedReviewTime:null,reviewer:'Ahmet — owner',evidenceBasis:'explicit-owner-message',instruction:'AHMET — MASTER REVIEW: REVISION REQUESTED. Cycle11 V1 not approved; Han van Meegeren premise remains approved. Produce substantially better V2: immediate Nazi-sale/own-forgery contradiction, developing accusation/confession/expert acceptance/material investigation/legal outcome, supported understandable forensic mechanisms, less repetitive static documentary/text compositions, phone hierarchy and honest simulated/device distinction. Preserve strong V1 narration/structure/qualifications where effective; no unsupported stakes, courtroom dialogue/reenactments/demonstrations/lab footage/execution deadline or innocent-hero framing. Investigate recurring Cycle10/11 weakness without assuming root cause; improve current artifact and smallest existing canonical production/review/learning practices, discoverable through AGENTS, with evidence, cold-viewer judgment, proportionate recurrence detection, bounded internal revisions, no numerical scores/new owner gates/framework/infrastructure. Complete technical/audiovisual/caption/historical/artifact QA and independent complete-result review as tools permit. Preserve V1/all historical artifacts/decisions/publications. Back up authorized Cycle11 branch to origin and verify sync; no main merge. STOP AHMET — MASTER REVIEW · Cycle11 · V2; no publication preparation/Cycle12/publish/schedule. Faithful scope transcription; supplied owner review time unknown.',reason:'Recurring static documentary panels and repetitive explanatory structures underuse a compelling historical investigation.',acceptedUnknowns:[]}));
cycle=persistCycleEvent(process.cwd(),cycle,{type:'owner-decision',record:decision,at:now},registry);
cycle=persistCycleEvent(process.cwd(),cycle,{type:'retry-internal',stage:'creative',record:put('revision-scope',{cycleId:'cycle.11',reason:'Presentation-only revision retains exact editorial receipt and narration; new direction and production identities.'}),at:new Date().toISOString()},registry);
}
cycle=persistCycleEvent(process.cwd(),cycle,{type:'begin-internal',stage:'creative',record:put('creative-start',{cycleId:'cycle.11',stage:'creative',action:'Investigate transfer failure; inspect V1 and recent masters; design authorship reversal and continuous material investigation.'}),at:new Date().toISOString()},registry);
const pkg=knowledgePackageSchema.parse(read(`${old}/knowledge-package.ready.json`)),asset=contentAssetSchema.parse(read(`${old}/content-asset.ready.json`)),direction=creativeDirectionSchema.parse(read(`${old}/direction-v1.json`));
// Same four approved predecessors at this revision; original bound decoded comparisons retained.
direction.id='creative-direction.vermeer-forgery.v2';direction.revision=2;direction.provenance.enteredAt=now;direction.provenance.notes='Owner-requested V2. Original bounded approved set and inspected portfolio evidence retained; current V1 scene overview and Craft V3 scene overview inspected again. Same verified wording/audio; no new historical assertion.';
direction.visualThesis='An attribution under investigation: the sale object changes from supposed Vermeer to authorship claim; accepted Emmaus becomes an image plane, then the mechanism moves through hardening, manufactured cracks, binder comparison and separated layer networks before returning to culpability.';
for(const d of direction.decisions){if(['visual-medium','art-direction','hook'].includes(d.dimension)){d.treatment='Opening juxtaposes supposed Vermeer/Nazi buyer with must prove his own forgery; a visibly schematic empty painting frame carries the intermediary-sale question into authorship reversal. Emmaus is shown only in the acceptance/payoff context. Enlarged material plane changes state; binder comparison uses magnified schematic cross-section rather than arbitrary rock shapes; crack layers separate in depth and align for comparison. Legal reversal retains fraud conviction.';d.rationale='V1 repeatedly reset title, object, disclosure in identical slots. Here the object and changing evidence status carry the investigation, with essential labels subordinate to explanatory action.';}if(d.dimension==='platform-presentation'){d.treatment='Larger730×850 central content field; essential labels42–62px, designed captions48px; short32px disclosures explicitly identify models/archive dates.360px decoded preview and transition/checkpoint measurements, with provisional geometry and native-device uncertainty retained.';}}
for(const a of direction.convergenceReview.recentAssets){a.visualComparison!.dimensions.push({dimension:'rendered-story-progression',observed:'V1 promised object inspection but rendered repeated heading/box layouts, including arbitrary identical material shapes.',proposed:'Visible attribution reversal, large image inspection, continuous hardened-paint/crack/layer sequence and concrete binder comparison.',reason:'Implementation must realize the thesis; alternate scene labels and sampled motion do not demonstrate a developing story.'});}
direction.convergenceReview.conclusion='Retain truthful restraint, current voice and speech clarity. Replace repeated panels where they conceal mechanism or narrative development; no forced style rotation or reenactment.';
const dref=put('direction-v2',validateCreativeDirection(direction,pkg,asset,{registry}));cycle=persistCycleEvent(process.cwd(),cycle,{type:'complete-internal',stage:'creative',record:dref,at:new Date().toISOString()},registry);
const caption=JSON.parse(readFileSync('src/captions/plans/vermeer-forgery.json','utf8'));caption.id='caption-plan.vermeer-forgery.v2';caption.revision=2;caption.creativeDirection={id:direction.id,revision:2,sha256:sha256Json(direction)};caption.visualTreatment.rendererId='renderer.vermeer-investigation.v2';caption.visualTreatment.backdrop='Stable speech field under evolving enlarged visual investigation.';validateAdaptiveCaptionPlan(caption,narration.cues,narration.format,direction,asset);writeFileSync('src/captions/plans/vermeer-forgery-v2.json',JSON.stringify(caption,null,2)+'\n',{flag:'wx'});
const plan=productionPlanV3Schema.parse(read('src/production/plans/vermeer-forgery.json'));plan.id='production-plan.vermeer-forgery.v2';plan.revision=2;plan.creativeDirection=caption.creativeDirection;plan.captions.captionPlanId=caption.id;plan.captions.captionPlanRevision=2;plan.captions.captionPlanSha256=sha256Json(caption);
for(const b of plan.beats){b.animationIntent='Develop a persistent investigation object and its evidence status; enlarge material mechanisms and progressively separate crack layers. Motion reveals causal changes, not decorative loops.';b.transitionIntent='Carry framed attribution through accusation/confession; retain paint plane through manufacture/testing/layer reveal; distinguish archival art from schematic materials.';}
plan.reviewRequirements.push('Separate cold-viewer editorial review of complete rendered sequence: opening, progression, visual developments, adjacent repetition, mechanism clarity, payoff, worth watching; preserve weaknesses/actions/coverage limits.');validateInternalProductionPlanReferences(plan,pkg,asset,direction);writeFileSync('src/production/plans/vermeer-forgery-v2.json',JSON.stringify(plan,null,2)+'\n',{flag:'wx'});
const start=put('production-start',{cycleId:'cycle.11',stage:'production',action:'Render V2 with unchanged195words and82.9s timing; actual-media QA and cold-viewer sequence review; stop owner Master Review.'});persistCycleEvent(process.cwd(),cycle,{type:'begin-internal',stage:'production',record:start,at:new Date().toISOString()},registry);
