import {existsSync, readFileSync, writeFileSync} from 'node:fs';
import {generateDeliveryPackage, validateDeliveryPackage} from './delivery-packages';
import {longitudePublicationVariants as variants} from '../src/platform-variants/variants/longitude-clock-publication';
import {validateLongitudePublicationAuthorization} from '../src/platform-variants/longitude-publication';
import {longitudeFileHash} from '../src/production/longitude-integrity';
import {sha256Json, stableJson} from '../src/content-intelligence/run-schema';
import {coverAssetSchema} from '../src/platform-variants/presentation';
import {youtubeCategoryPolicy} from '../src/platform-variants/youtube-category-policy';

const root = 'content-intelligence/reviews/longitude-clock-publication-v1';
if (existsSync(`${root}/final-bindings.json`)) throw new Error('Preserve this release handoff; changes require a new revision.');
const decision = validateLongitudePublicationAuthorization();
const generatedAt = new Date().toISOString();
const packages = variants.map(variant => generateDeliveryPackage({variantId: variant.id, outputRoot: 'artifacts/deliveries/longitude-clock-publication-v1', generatedAt}));
for (const item of packages) validateDeliveryPackage(item.directory);
const write = (name: string, data: unknown) => writeFileSync(`${root}/${name}`, stableJson(data, 2)+'\n');
write('platform-variants.json', variants);
write('final-bindings.json', {
  schemaVersion: 1, decision: {id: decision.id, revision: decision.revision, sha256: sha256Json(decision)},
  publicationAuthorized: true, publicationOccurred: false, assistantUploadAuthorized: false,
  masterArtifactId: decision.masterArtifactId, master: decision.master,
  coverSelection: {...decision.selectedInstagramCover, selectedForPublication: true, deviceTested: false},
  packages: packages.map((item, index) => ({directory: item.directory.replace(process.cwd()+'/', ''), deliveryId: item.manifest.deliveryId, platform: item.manifest.destination.platform, state: item.manifest.state, variantSha256: sha256Json(variants[index]), manifestSha256: sha256Json(item.manifest), manifestFileSha256: longitudeFileHash(`${item.directory}/manifest.json`), uploadFile: `${item.directory.replace(process.cwd()+'/', '')}/video.mp4`, uploadSha256: decision.master.sha256})),
  realDevicePassesGranted: [], acceptedRisks: decision.acceptedRisks, postPublicationReview: decision.postPublicationReview,
});
const originalCover = JSON.parse(readFileSync('artifacts/longitude-clock-cover-assets.json', 'utf8'))[0];
write('cover-selection.json', coverAssetSchema.parse({...originalCover, status: 'approved', approvalDecisionId: decision.id, provenance: originalCover.provenance+' Exact original cover selected for publication under owner-accepted crop uncertainty; no device pass.'}));
write('upload-settings.json', {schemaVersion: 1, settingsApplied: false, audience: 'general audience; not child-directed', comments: 'on with normal moderation', reuse: 'off initially where available', quality: 'highest-quality/HD where available', crossPost: 'off', nativeVisibleCaptions: 'off to avoid duplicate overlays', originalMedia: 'Preserve original audio and burned-in captions; no added music/filter/effect/reframing/enhancement', disclosures: 'Follow actual live wording; transparently disclose synthetic narration when applicable. Original animation/H4 reconstruction is not realistic historical footage.', youtube: {categoryPolicy: youtubeCategoryPolicy, preferredCategory: 'Science & Technology', fallbackCategory: 'Education', fallbackCondition: 'Only when materially more appropriate among live available categories', language: 'English', madeForKids: 'No, based on intended general audience; owner confirms live setting'}, visibility: 'Public/Everyone for owner manual publication; no scheduling', account: 'Owner confirms intended Magnivis account/Page; no unknown handles or live controls invented'});
write('post-publication-review.json', {schemaVersion: 1, state: 'pending-live-publication-evidence', publicationOccurred: false, prepublicationRealDevicePasses: 0, releaseBlocked: false, decisionId: decision.id, surfaces: ['youtube-mobile-shorts', 'youtube-desktop-web', 'tiktok-mobile-feed-playback', 'instagram-reel-playback', 'instagram-profile-grid', 'facebook-reel-viewer', 'facebook-page-feed'].map(surface => ({surface, state: 'NOT_TESTED', url: null, device: null, os: null, appVersion: null, observedAt: null, screenshots: [], observations: [], audioResult: 'unknown'})), inspect: ['opening and cover/crop', 'captions', 'top/bottom UI and right-side controls', 'correction and BOTH MEAN SOLAR TIME / SAME INSTANT', '12:00 / 14:00', '+2 HOURS', '30° EAST', 'H4', 'final payoff', 'audio'], instructions: ['Record real observations first; qualitative reports are not measured geometry.', 'Unknown timestamp/device/settings/screenshots remain unknown.', 'Do not automatically rerender for minor issues. Improve future engineering with evidence.', 'Material problems return to an explicit owner remediation decision.']});
write('publication-evidence-intake.json', {schemaVersion: 1, purpose: 'prepared-intake-not-publication-record', publicationAuthorized: true, publicationOccurred: false, entries: packages.map((item, index) => ({platform: item.manifest.destination.platform, authorizedVariant: {id: variants[index]!.id, revision: 2, sha256: sha256Json(variants[index])}, authorizedDelivery: {id: item.manifest.deliveryId, path: item.directory.replace(process.cwd()+'/', ''), manifestFileSha256: longitudeFileHash(`${item.directory}/manifest.json`)}, masterSha256: decision.master.sha256, publicUrl: null, platformContentId: null, shortcode: null, publishedAt: null, publishedOn: null, successfulPublication: null, actualUploadedVariant: null, actualUploadedDelivery: null, mobilePresentation: null, desktopWebPresentation: null, commentsPosted: null, cropUiProblems: null, settings: 'unknown', screenshots: [], expectedRemoteEvidence: item.manifest.destination.platform === 'youtube' ? 'Public Shorts URL and video ID' : item.manifest.destination.platform === 'tiktok' ? 'Public permalink/video ID if obtainable; Studio URL is not a public permalink' : item.manifest.destination.platform === 'instagram' ? 'Public Reel/post URL and shortcode/ID where obtainable' : 'Public Reel URL and Reel ID where obtainable'}))});
write('analytics-readiness.json', {schemaVersion: 1, metricSnapshots: [], instructions: ['Bind an actual published record first.', 'Capture meaningful observation windows with actual capture time and native metric names/definitions/source.', 'Do not normalize all view metrics, infer performance from early views, or transfer Phantom Traffic performance.', 'Performance forms hypotheses, not permanent visual/audio/creative rules.'], observationWindows: 'Owner/platform-appropriate later windows; none fabricated now'});
const copy = JSON.parse(readFileSync(`${root}/platform-copy.json`, 'utf8'));
const covers = JSON.parse(readFileSync('content-intelligence/reviews/longitude-clock-platform-v1/cover-evaluation.json', 'utf8'));
const lines = ['# Longitude Clock — final owner manual-upload checklist', '', '**PUBLICATION AUTHORIZED for Ahmet manual upload only.** No further private/device preview required. Zero Longitude prepublication device passes; documented presentation uncertainty explicitly accepted. Assistant must not upload, schedule or publish.', '', `Every video.mp4 below: SHA-256 ${decision.master.sha256}. No rerender/re-encode/creative or copy change.`, '', 'Common fields: Public/Everyone; comments on with normal moderation; remix/reuse/download/duet/stitch off initially where available; highest-quality/HD where available; automatic cross-posting off. Preserve original narration, soundscape and burned-in captions. Add no music/filter/effect/auto-reframing/enhancement; disable duplicate visible native captions. No age restriction recommended; general educational audience. No paid promotion/branded content, location or added link. Confirm intended Magnivis account/Page and actual live controls.', '', 'AI/synthetic field: follow actual platform wording; transparently disclose synthetic narration when applicable. No realistic synthetic historical footage is present. Controls/settings have not been applied or observed.', ''];
for (const item of packages) {
  const platform = item.manifest.destination.platform;
  const text = copy[platform];
  const directory = item.directory.replace(process.cwd()+'/', '');
  lines.push(`## ${platform.toUpperCase()}`, '', `Upload file: ${directory}/video.mp4`, '', ...(text.title ? [`Title${platform === 'facebook' ? ' (if available)' : ''}: ${text.title}`, ''] : []), text.description ? 'Description:' : 'Caption:', text.description ?? text.caption, '', `Hashtags (append to body): ${text.hashtags.map((tag: string) => '#'+tag).join(' ')}`, '', `Tags/keywords${platform === 'facebook' ? ' (only if separate Tags field exists)' : platform === 'youtube' ? ' (optional Studio tags)' : ''}: ${text.keywords.join(', ') || 'none'}`, '', `Cover/frame: ${platform === 'instagram' ? `${directory}/cover.png — exact approved cover, SHA-256 ${decision.selectedInstagramCover.sha256}; grid crop uncertainty accepted` : `${covers[platform].time}s representative frame; ${covers[platform].path}; use available live frame/thumbnail controls`}`, '', `Optional first comment: ${text.firstComment}`, '', platform === 'youtube' ? 'Audience: Not made for kids based on intended general audience; owner confirms. Language: English. Category: story-specific; Science & Technology preferred for Longitude; Education only when materially more appropriate among live available categories. No universal Magnivis category.' : platform === 'tiktok' ? 'Audience/visibility: Everyone/Public where offered. Duet, Stitch, reuse and downloads off initially where available. Retain original sound; confirm applicable AI-generated-content prompt.' : platform === 'instagram' ? 'Audience: Public according to intended account/release. Use exact cover; profile/grid uncertainty accepted. Facebook automatic sharing off; share-to-feed is owner choice under accepted crop uncertainty. Confirm applicable AI disclosure.' : 'Audience: Public/Everyone according to intended Page/account. Title and separate Tags field only if offered. Instagram automatic sharing off; Page/feed crop uncertainty accepted. Confirm applicable AI disclosure.', '', 'Comments: on, normal moderation. Reuse/remix/download: off initially where offered. Quality: highest-quality/HD. Native visible captions: off to avoid duplication. Cross-post: off. AI disclosure: transparent when applicable to synthetic narration under actual live wording. Original media: unchanged. Schedule: none.', '');
}
lines.push('## After publication', '', 'Supply actual public URLs/IDs where obtainable and report success, mobile/desktop presentation, posted comments and any UI/crop issue. Unknown metadata remains unknown. Follow post-publication-review.json; inspect before deciding on remediation. No MetricSnapshots yet.', '', '**Exact next gate: AHMET — CYCLE #2 MANUAL PUBLICATION.**');
writeFileSync(`${root}/publication-checklist.md`, lines.join('\n').trimEnd()+'\n');
console.log({packages: packages.length, states: packages.map(item => item.manifest.state), publicationAuthorized: true, publicationOccurred: false});
