import {existsSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname} from 'node:path';
import {mediaHash, loadMediaRegistry} from '../src/artifacts/media';
import {sha256Json} from '../src/content-intelligence/run-schema';
import {knowledgePackageSchema} from '../src/knowledge/schema';
import {contentAssetSchema} from '../src/content-assets/schema';
import {verifyInternalEditorial} from '../src/workflow/editorial';
import {validateCreativeDirection} from '../src/content-assets/creative-direction-integrity';
import {loadCycle, persistCycleEvent} from '../src/workflow/store';
import {projectLegacyPresentationProfile} from '../src/workflow/profile-compatibility';
import type {RecordReference} from '../src/workflow/evidence';

const base='content-intelligence/cycles/cycle-4';
const now=new Date().toISOString();
const ref=(path:string):RecordReference=>({path,sha256:mediaHash(path)});
const read=(path:string):unknown=>JSON.parse(readFileSync(path,'utf8'));
const put=(name:string,data:unknown)=>{const path=`${base}/${name}.json`;mkdirSync(dirname(path),{recursive:true});writeFileSync(path,JSON.stringify(data,null,2)+'\n',{flag:'wx'});return ref(path);};
const advance=(stage:'discovery'|'editorial'|'creative',record:RecordReference)=>{const registry=loadMediaRegistry();const c=loadCycle(process.cwd(),'cycle.4',registry);persistCycleEvent(process.cwd(),c,{type:'complete-internal',stage,record,at:new Date().toISOString()},registry);};
const bind=(data:{id:string;revision:number})=>({id:data.id,revision:data.revision,sha256:sha256Json(data)});
const id='paper-half-shape';
const cid=(key:string)=>`${id}.claim.${key}`;
const aid=`${id}.asset.hidden-geometry`;
const sourceUrls={
  din:'https://www.din.de/de/din-und-seine-partner/presse/mitteilungen/herzlichen-glueckwunsch-a4--878664',
  nrich:'https://nrich.maths.org/problems/fit-photocopying',
  iso:'https://preview.sist.si/sist-preview/36631/c0883203ea25445c9992bb09343620c5/ISO-216-2007.pdf',
};
if(!process.argv.includes('--profiles-only')) {
const search=put('discovery-search',{
  cycleId:'cycle.4',enteredAt:now,method:'Session-assisted open-web search and source-body inspection; no provider/API run or scores.',
  queries:['A4 geometry NRICH and DIN','Louis Braille Library of Congress','lunar laser ranging NASA','GS1 check digit','Tyrian purple Smithsonian','aspen clone National Park Service'],
  opportunities:[
    {id:'paper-half-shape',url:sourceUrls.nrich,access:'body-inspected',finding:'Cambridge NRICH supplies the similarity derivation and copying scale; DIN supplies dimensions; ISO preview confirms the basic principle.'},
    {id:'braille-cell',url:'https://loc.gov/exhibits/louis-braille/overview.html',access:'body-inspected',finding:'Six-dot cell and development history; a tactile story needs care in implying experience and dating stages.'},
    {id:'retreating-moon',url:'https://www.nasa.gov/missions/apollo/apollo-11/the-apollo-experiment-that-keeps-on-giving/',access:'body-inspected',finding:'Laser ranging measures present recession; extrapolating current rate indefinitely would mislead.'},
    {id:'barcode-check',url:'https://www.gs1.org/services/check-digit-calculator',access:'search-only-body-open-error',finding:'Check-digit concept appears feasible; central algorithm still needs body acquisition.'},
    {id:'purple-snails',url:'https://library.si.edu/exhibition/color-in-a-new-light/making',access:'search-only-body-open-error',finding:'Dye origin feasible; cost/royalty universals require stronger scoped evidence.'},
    {id:'forest-clone',url:'https://www.nps.gov/brca/learn/nature/quakingaspen.htm?simple=True',access:'body-inspected',finding:'Connected clonal roots; exceptional age and largest-organism claims require additional review.'},
  ],
  excludedInfluences:['No fixed category whitelist.','No convenience preference for prior renderers.','No invented recent analytics or causal performance claims.'],
});
const historyPaths=[
  'content-intelligence/reviews/chocolate-crystal-choice-approved-v3/content-asset.approved.json',
  'content-intelligence/reviews/longitude-clock-approved-v3/content-asset.approved.json',
  'content-intelligence/reviews/phantom-traffic-approved-v3/content-asset.approved.json',
];
const history=historyPaths.map(path=>{read(path);return ref(path);});
const candidateData=[
  ['paper-half-shape','The rectangle that survives halving',['geometry','everyday-design'],'A familiar object becomes a miniature proof, distinct from prior material, time-navigation and traffic mechanisms.','ISO/DIN/Cambridge provide central evidence plus independent algebra.','Understand why this ratio preserves shape and why half the area is not half the length.','Cut, rotate and overlay the same geometry; use an original print layout to demonstrate scaling.','A4 appears mundane until a square fails the same test.','New bespoke paper choreography is feasible locally; exact geometry matters more than realism.','Adds everyday mathematical design without imposing a new domain preference.','Stronger immediate visual proof and fewer empirical caveats than the other current candidates.','eligible'],
  ['braille-cell','Why braille uses six dots',['language','accessibility','design-history'],'New tactile knowledge angle.','LOC body inspected; detailed chronology needs further bounded research.','Distinguish tactile literacy design from visually imitating printed letters.','Macro raised dots and a well-qualified tactile demonstration.','A small design decision opens a whole writing system.','Original modeling feasible; a faceless depiction must not invent user experience.','Adds language and human design.','Strong future candidate, but the paper story resolves its central mechanism more directly within a short.','eligible'],
  ['retreating-moon','The Moon is moving away',['astronomy','geodesy'],'New mechanism; overlaps prior space-scale portfolio.','NASA body inspected; tidal mechanism can be corroborated with primary literature.','Explain how ranging reveals orbital evolution.','Laser-return and energy-transfer views, not a simple scale montage.','The Moon changes distance while it looks constant.','New orbital mechanism feasible; preserve present-rate scope.','Astronomy is eligible without receiving automatic preference.','Strong curiosity, but central-rate extrapolation risk and portfolio overlap reduce its advantage today.','eligible'],
  ['barcode-check','A barcode digit checks the others',['information-systems','arithmetic'],'Everyday systems explanation distinct from history.','GS1 result found; body open failed and algorithm not yet inspected.','Explain error detection without promising authentication.','Digits, weighted sums and a deliberate typo.','The last digit has a hidden job.','Original arithmetic visuals feasible after central evidence acquisition.','Expands information literacy.','Hold because central-source body access is incomplete, not because its domain is excluded.','hold'],
  ['purple-snails','Purple made from sea snails',['culture','chemistry','history'],'Cultural-material story, distinct from chocolate phase structure.','Smithsonian result located; body open failed.','Explain a material source behind historical color prestige.','Original mollusk and dye-process reconstruction with historical scope.','A luxurious color begins with an unexpected animal.','New illustration feasible, but period costume and extraction details need rights and evidence care.','Adds cultural history.','No central source body yet; avoid repeating sensational snail counts or universal royalty restrictions.','hold'],
  ['forest-clone','Many trunks, one clonal system',['ecology','organism-identity'],'Fresh ecological mental-model story.','NPS body inspected; quantitative Pando age/extent not yet substantiated.','Distinguish individual stems from connected clone identity.','Forest-to-root reveal with a truthful scale disclosure.','What looks like many trees can share one root system.','Original ecological imagery possible; connection/identity caveats require additional scrutiny.','Eligible nature, without inheriting Wood Frog style.','Excellent future candidate; paper offers a clearer bounded proof with fewer biological ambiguities.','eligible'],
] as const;
advance('discovery',put('topic-selection',{
  schemaVersion:3,cycleId:'cycle.4',method:'qualitative-open-world-comparison',searchRecord:search,
  searchBreadth:'Six distinct opportunities across everyday mathematics/design, tactile language, astronomy, information systems, cultural-material history and ecology. Search opened institutional bodies where available; failed access stays explicit. The pool is a bounded sample of an open universe, not a whitelist.',
  classificationAfterDiscovery:true,historyReviewed:history,analyticsInfluence:'provenance-bearing-signals-not-category-rules',convenienceAdvantageRejected:true,
  candidates:candidateData.map(c=>({id:c[0],subject:c[1],domains:[...c[2]],novelty:c[3],evidenceFeasibility:c[4],explanatoryPayoff:c[5],visualPotential:c[6],audienceCuriosity:c[7],productionFeasibility:c[8],portfolioDiversity:c[9],comparison:c[10],disposition:c[11],evidence:[search],limitations:c[11]==='hold'?['Discovery lead only; not claim verification.']:['No performance forecast or owner topic approval claimed.']})),
  selectedId:id,outcome:'selected',rationale:'Select A-series paper for an immediately visible paradox, rigorous but accessible proof, useful scaling payoff, source feasibility and portfolio novelty. New paper-specific scenes will serve the mechanism; no old renderer/style or storage preference influenced selection.',
}));

const sourceInfo=[
  {key:'din',organization:'DIN Deutsches Institut für Normung',title:'Herzlichen Glückwunsch, A4!',type:'primary-source' as const,access:'inspected' as const,locator:'Vom Formatchaos zum Standard; Die Maße der A-Formate',summary:'DIN describes an A0 basis, successive long-dimension halving and conserved aspect ratio. Its table lists A3 as 297 by 420 mm, A4 as 210 by 297 mm, and A5 as 148 by 210 mm. These integer dimensions approximate the ideal irrational-ratio model. The page explicitly notes US Letter as a different format.',limits:['German source; assessment uses original German text, not an invented official translation.','Historical details not used in narration.']},
  {key:'nrich',organization:'University of Cambridge, NRICH',title:'Fit for Photocopying',type:'university' as const,access:'inspected' as const,locator:'Problem; Student Solutions ratio derivation; scale-factor solution; Teachers Resources',summary:'The task describes related A sizes. Its algebra equates original and rotated half-sheet ratios, yielding a squared ratio of two. It distinguishes the half-area factor from the square-root length factor and obtains approximately 70.7 percent for A3-to-A4 copying. Independently recomputed here; student solutions are educational reasoning, not an experimental dataset.',limits:['One displayed A2 student-result rounding differs from DIN; no student size table is used.','The scaling explanation concerns ideal geometry, not a printer margins guarantee.']},
  {key:'iso',organization:'ISO, preview hosted by SIST',title:'ISO 216:2007 preview',type:'technical-documentation' as const,access:'partially-inspected' as const,locator:'Printed pages 2–3 clauses 4.1/4.3; printed page 5 Table 1; preview scope and tolerances page 6',summary:'The publicly viewable ISO preview states the halving and similarity principles, gives the side-to-diagonal-of-square ratio, defines the A-series basis, and lists A3/A4/A5 integer-millimetre sizes. It also recognizes alternate North American office sizes and size tolerances. Only the available preview was inspected; full tolerance continuation and Annex A were unavailable.',limits:['Partial preview, not purchased full standard.','No protected source figures/PDF/page images reproduced as production assets or stored here.','Text extraction loses the radical glyph; ratio corroborated by DIN/NRICH and independent algebra.']},
];
const sources=sourceInfo.map(s=>({id:`source.paper.${s.key}`,organization:s.organization,title:s.title,sourceType:s.type,url:sourceUrls[s.key as keyof typeof sourceUrls],retrieved:now.slice(0,10),notes:s.limits.join(' ')}));
const evidenceRecords=sourceInfo.map(s=>put(`sources/${s.key}-inspection`,{sourceId:`source.paper.${s.key}`,url:sourceUrls[s.key as keyof typeof sourceUrls],retrievedAt:now,accessStatus:s.access,inspectedText:s.summary,acquisition:'manual-source-inspection',inspectionMethod:'Source body opened in session web tool; ISO public preview parsed by page. This is an original inspection summary, not a saved HTTP/PDF body or fabricated full-text acquisition.',locator:s.locator,limitations:s.limits}));
const definitions=[
  ['similarity','The ideal A-series geometry preserves its aspect ratio after bisecting the long dimension and rotating the half sheet.',['iso','din','nrich'],'Real integer sizes and manufacturing tolerances only approximate the ideal.'],
  ['square','A square bisected parallel to one side yields a rectangle whose long-to-short ratio is two, rather than one.',['nrich'],'Geometrical derivation independently checked; not an empirical experiment.'],
  ['ratio','The ideal A-series long-to-short ratio is the square root of two.',['iso','din','nrich'],'Ideal defining ratio; integer dimensions are not exact irrational ratios.'],
  ['scaling','In ideal A-series geometry, an A3 design scales uniformly to A4, preserving proportions.',['nrich','iso'],'No promise about printer margins or actual crop behavior.'],
  ['length-area','The ideal adjacent-size length factor is one over the square root of two, about 70.71 percent, while the area factor is one half.',['nrich'],'71 percent is spoken rounding, not an exact copying instruction.'],
  ['rounded','Published A-series dimensions are whole millimetres that approximate the ideal geometry; for example A4 is 210 by 297 mm.',['iso','din'],'Actual manufactured sheet tolerances are additional, not quantified here.'],
  ['universal','Every paper rectangle preserves its shape when halved.',['iso'],'Excluded: false for squares, US Letter and general rectangles.'],
] as const;
const claims=definitions.map(d=>({id:cid(d[0]),type:'qualitative' as const,statement:d[1],verificationStatus:d[0]==='universal'?'unverified' as const:'supported' as const,caveats:[d[3]],evidence:d[2].map(key=>({sourceId:`source.paper.${key}`,locator:sourceInfo.find(s=>s.key===key)!.locator,notes:d[0]==='square'?'Independent geometrical check: unit square halves to 1 by 0.5; ratio is 2.':`Inspected source supports the scoped ideal/nominal distinction. ${d[3]}`}))}));
const lines=[
  ['Cut A4 paper in half. Turn it. It’s almost the same shape, only smaller.',['similarity','rounded']],
  ['A square cannot do that. Halve it, and you get a skinny rectangle.',['square']],
  ['A-series paper is built around a special ratio: one to the square root of two.',['ratio']],
  ['Halve the long side, then rotate the piece. That ratio comes back.',['similarity','ratio']],
  ['In the ideal system, an A3 design shrinks to A4 without stretching.',['scaling']],
  ['Each length shrinks to about seventy-one percent. The area halves.',['length-area']],
  ['Real paper sizes are rounded to whole millimetres. The perfect rule lives in the geometry.',['rounded','ratio']],
  ['Half the paper. Same proportions.',['similarity']],
] as const;
const pkg=knowledgePackageSchema.parse({id,revision:1,topic:'The hidden geometry of A-series paper',centralQuestion:'Why can A-series paper keep its proportions when halved?',taxonomy:{pillar:'technology-built-world',domains:['geometry','everyday-design'],topics:['a-series-paper','similarity','area-scaling']},timeliness:'evergreen',thesis:'A √2 aspect ratio makes the rotated half-sheet similar to its parent; physical sizes approximate the ideal.',viewerPayoff:'Understand a familiar design and distinguish length scaling from area scaling.',sources,claims,caveats:[{id:`${id}.caveat.ideal`,statement:'Ideal models are exact; physical sheet dimensions are rounded and toleranced.',claimIds:[cid('similarity'),cid('ratio'),cid('rounded')]},{id:`${id}.caveat.printer`,statement:'Scaling preserves proportions; it does not guarantee borderless printing or universal paper applicability.',claimIds:[cid('scaling'),cid('universal')]}],hooks:[{id:`${id}.hook.cut`,archetype:'demonstrated-invariant',text:lines[0][0],viewerPromise:'Watch the shape survive a cut and learn why.',claimIds:[cid('similarity'),cid('rounded')]},{id:`${id}.hook.scale`,archetype:'everyday-hidden-rule',text:'Half the area does not mean half the length.',viewerPromise:'Understand the copy-size factor.',claimIds:[cid('length-area')]}],narrativeOpportunities:[{id:`${id}.narrative.proof`,title:'Counterexample to proof',description:'A square fails, then the special ratio resolves the contrast.',claimIds:[cid('square'),cid('ratio'),cid('similarity')]}],visualOpportunities:[{id:`${id}.visual.paper`,title:'Cut, turn, align',description:'Original proportional sheets, a square counterexample and a uniform print layout scaling.',claimIds:[cid('similarity'),cid('square'),cid('scaling'),cid('length-area')]}],relatedQuestions:['Why is A0 based on one square metre?','Why does US Letter behave differently?'],followUpOpportunities:['Paper formats as a standards-history story, separately sourced.'],editorialStatus:'review'});
const asset=contentAssetSchema.parse({id:aid,revision:1,knowledgePackageId:id,assetType:'short-form-video',editorialPurpose:pkg.viewerPayoff,storyAngle:'Make a mundane rectangle perform an understandable mathematical trick.',hookId:pkg.hooks[0]!.id,selectedClaimIds:claims.filter(c=>c.id!==cid('universal')).map(c=>c.id),durationIntentSeconds:{minimum:35,maximum:65},script:{language:'en',segments:lines.map((l,i)=>({id:`${aid}.script.${i+1}`,type:'factual',text:l[0],claimIds:l[1].map(cid)}))},narrativeStructure:lines.map((l,i)=>({id:`${aid}.beat.${i+1}`,label:['cut-turn','square-fails','special-ratio','returning-ratio','layout-fit','length-not-area','physical-limit','payoff'][i],purpose:['Open with the actual operation.','Show that preserving shape is special.','Name the mathematical relationship.','Expose the mechanism.','Give a practical application.','Prevent length/area confusion.','Preserve physical rounding.','Land the reframe.'][i],scriptSegmentIds:[`${aid}.script.${i+1}`]})),visualPlan:lines.map((l,i)=>({id:`${aid}.visual.${i+1}`,narrativeBeatId:`${aid}.beat.${i+1}`,objective:['Bisect a portrait sheet across its long dimension and rotate a half; overlay outline.','Halve a square and rotate; width/height comparison clearly differs.','Extend a unit square to its diagonal length, creating the √2 rectangle.','Track original 1 and √2 edges to the rotated half: √2/2 and 1.','Scale an original abstract print composition uniformly from A3 to A4.','Show 70.7% length beside a half-area two-piece construction.','Separate ideal ratio from DIN nominal A4/A5 numbers; visibly disclose schematic model.','Return to the original sheet/half outline with a quiet final alignment.'][i],visualType:'bespoke',suggestedPrimitive:'bespoke',scriptSegmentIds:[`${aid}.script.${i+1}`],claimIds:l[1].map(cid),notes:'Original geometry; no source figures copied. Exact ideal ratio model is disclosed. Physical nominal dimensions never imply exact √2 equality.'})),narrationPlan:{mode:'narrated',voiceDirection:'af_heart, warm precise curiosity; deliberate cut/turn pauses and clear length versus area contrast.',pronunciationNotes:['A4: ay four; A3: ay three; square root of two; millimetres.']},editorialStatus:'editorial-review'});
const review={schemaVersion:3,cycleId:'cycle.4',topicCandidateId:id,enteredAt:now,reviewer:'Codex session — internal evidence review (not Ahmet)',packageSha256:sha256Json(pkg),assetSha256:sha256Json(asset),scriptSha256:sha256Json(asset.script),inspections:sourceInfo.map((s,i)=>({sourceId:`source.paper.${s.key}`,accessStatus:s.access,identityConfirmed:true,evidenceLocations:[s.locator],supportsClaimIds:claims.filter(c=>c.id!==cid('universal')&&c.evidence.some(e=>e.sourceId===`source.paper.${s.key}`)).map(c=>c.id),limitations:s.limits,inspectedEvidence:evidenceRecords[i],sourceQualityRationale:s.key==='iso'?'Primary standard preview; only inspected clauses used.':s.key==='din'?'Standards body is an authoritative first-party source for nominal sizes and underlying principle.':'Cambridge mathematics education explains derivation; operator recomputation independently validates it.'})),claims:claims.map(c=>({id:c.id,statementSha256:sha256Json(c.statement),disposition:c.id===cid('universal')?'exclude':'verify',rationale:c.id===cid('universal')?'False universal excluded; narration and geometry scoped to A-series.':'Source traced, caveat preserved and independent mathematics checked.',evidence:c.id===cid('universal')?[]:c.evidence.map(e=>({sourceId:e.sourceId,locator:e.locator,assessment:e.notes,sufficientForWording:true})),qualificationsPreserved:true})),misconceptionSafeguards:['Cut parallel to the short edge, halving the long dimension.','Rotate the half-sheet 90 degrees before comparing portrait proportions.','Disclose ideal geometry; physical A4/A5 integer rounding differs slightly.','Length ~70.7%, area 50%; never scale both axes to 50%.','No universal-paper, borderless-printing or historical invention claims.'],comprehensionReview:'Viewer can identify the cut, rotation, failed square, √2 edge relationship and distinct length/area scaling. Rounding is in speech, not hidden in notes.',rightsReview:'Factual source consultation only. No protected PDF, institutional diagrams/photos/logos copied into media. Original SVG/CSS paper/print shapes, already licensed Manrope, established local Kokoro af_heart; no new purchase, provider or infrastructure.',careAssessment:{state:'routine',rationale:'Elementary geometrical design explanation; no personal advice, sensitive human judgment, disputed central evidence or cost deviation.'},exceptionalConditions:[]};
put('draft-package',pkg);put('draft-asset',asset);put('internal-editorial-review',review);
advance('editorial',put('editorial-receipt',{draftPackage:pkg,draftAsset:asset,review}));
const ready=verifyInternalEditorial(review,pkg,asset);
put('knowledge-package.ready',ready.knowledgePackage);put('content-asset.ready',ready.contentAsset);
const direction=validateCreativeDirection({schemaVersion:1,id:'creative-direction.paper-half-shape.v1',revision:1,state:'ready-for-production-planning',knowledgePackage:bind(ready.knowledgePackage),contentAsset:bind(ready.contentAsset),approvedScriptSha256:sha256Json(asset.script),creativeThesis:'A tactile-looking paper proof: every transformation reveals a mathematical relationship.',viewerExperience:'An everyday sheet surprises, a square fails, then the viewer sees why the right rectangle succeeds.',emotionalTarget:'Quiet delight and understanding, rather than awe at large quantities.',visualThesis:'Warm pale paper, vermilion cut marks and forest-green edge annotations; generous space and precise choreography. Sheets feel physical through shadows, but models remain disclosed.',decisions:[
  {dimension:'visual-medium',treatment:'Original SVG/CSS paper choreography, proportional geometry and original abstract printed artwork.',rationale:'Exact transformations carry the proof; generative imagery would add ambiguous shape changes.',alternativesConsidered:['Live tabletop footage: appealing but requires a camera setup and obscures exact edge correspondence.','Photoreal generated paper montage: weaker temporal geometry fidelity.']},
  {dimension:'art-direction',treatment:'Cream work surface, near-white sheets, dark green mathematical ink, vermilion cut line. Manrope sentence-case typography with no dashboard framing.',rationale:'Distinguish paper objects, operations and annotations; warm print character follows the object, not a domain palette.'},
  {dimension:'narration',treatment:'Kokoro-local af_heart, speed 0.96; short clip-level pauses around operations.',rationale:'Current primary narrator; precise but accessible explanation requires room to watch.'},
  {dimension:'captions',treatment:'Speech phrases in large dark Manrope, sentence case on a plain cream field beneath the proof; restrained opacity transitions, no word bounce.',rationale:'Captions support silent understanding without covering transformed sheets. Exact words and qualifiers retained.'},
  {dimension:'sound',treatment:'Narration only; deliberate quiet during rotations, no continuous music.',rationale:'The shapes and edge correspondence require concentration. Silence lets the audience inspect the relationship; no simulated measurement sound.'},
  {dimension:'pacing',treatment:'Measured narration determines duration, with operation pauses and a brief final hold.',rationale:'Story-led; no threshold padding or inherited runtime.'},
  {dimension:'hook',treatment:'Cut and turn immediately; narration says almost to distinguish physical paper from the ideal model.',rationale:'The operation creates the question in frame one rather than a title-card promise.'},
  {dimension:'platform-presentation',treatment:'Master critical content inside surviving provisional playback insets; caption/native/crop geometry remains unknown. Target profiles bound before render.',rationale:'Local master preflight informs later adaptations without claiming mobile safety or preparing publication.'},
],convergenceReview:{recentAssets:historyPaths.map(path=>{const a=contentAssetSchema.parse(read(path));return {contentAsset:bind(a),learnedPrinciple:'A visible mechanism should resolve the opening question; captions complement necessary objects.',applicability:'Applies to proof clarity, not a prescribed color, material, hook or duration.',similarities:['Established af_heart narrator policy.','Original explanatory geometry and designed captions.'],differences:['Pale graphic paper field rather than traffic terrain, watch theatre or chocolate cutaway.','No ambient/tactile bed; identity comes from edge continuity and printed composition.','Mathematical counterexample rather than experimental/historical progression.'],assessment:'distinct-execution',rationale:'New story-specific paper construction selected before implementation; infrastructure reuse does not import historical treatments.'};}),unresolvedConvenienceReuse:[],conclusion:'No convenience-driven renderer, palette, timing or sound reuse. Existing Manrope license supports readable print typography; consciously chosen for this composition.'},ownerReview:{required:false,rationale:'Routine internal V3 direction within established narrator, rights, local tooling and cost; no exceptional departure.'},risks:['Rotations must visibly preserve geometry; no morphing shortcut.','Ideal/physical rounding disclosure must be legible.','Caption and proof annotations must not compete.','Actual mobile/crop/native presentation remains untested.'],provenance:{method:'ai-assisted-editorial',enteredAt:now,notes:'Session-authored and source-validated decisions under owner cycle-start authority. No separate LLM/provider run or owner direction approval fabricated.'},platformApprovalGranted:false,publicationApprovalGranted:false},ready.knowledgePackage,ready.contentAsset);
advance('creative',put('direction-v1',direction));
}
const profileSource=ref('artifacts/presentation-profiles.json');
const exportSource=ref('src/platform-variants/platform-profiles.ts');
const profiles=JSON.parse(readFileSync(profileSource.path,'utf8')) as {platform:string;id:string;lifecycle:string;surface:string}[];
for(const platform of ['youtube','tiktok','instagram','facebook']){
  const p=profiles.find(p=>p.platform===platform&&p.lifecycle!=='HISTORICAL_SUPERSEDED'&&p.id.startsWith('safe-area.'));
  if(!p)throw new Error(`Missing playback profile ${platform}`);
  if(!existsSync(`${base}/profiles/${platform}.json`))put(`profiles/${platform}`,projectLegacyPresentationProfile(p,profileSource,exportSource,now));
}
const c=loadCycle(process.cwd(),'cycle.4',loadMediaRegistry());
const started=put('production-start',{cycleId:c.id,stage:'production',action:'Generate primary narration, author measured CaptionPlan and ProductionPlan, implement new paper scenes, render and inspect exact media.'});
persistCycleEvent(process.cwd(),c,{type:'begin-internal',stage:'production',record:started,at:new Date().toISOString()},loadMediaRegistry());
console.log('Cycle #4 editorial and direction ready; production in progress.');
