import {existsSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {loadMediaRegistry,mediaHash} from '../src/artifacts/media';
import {sha256Json} from '../src/content-intelligence/run-schema';
import {loadCycle,persistCycleEvent} from '../src/workflow/store';
import {ownerDecisionSchema} from '../src/workflow/evidence';
import {validateCreativeDirection} from '../src/content-assets/creative-direction-integrity';
import {creativeDirectionSchema} from '../src/content-assets/creative-direction';
import {knowledgePackageSchema} from '../src/knowledge/schema';
import {contentAssetSchema} from '../src/content-assets/schema';
import {validateAdaptiveCaptionPlan} from '../src/captions/adaptive-plan';
import {validateInternalProductionPlanReferences,productionPlanV3Schema} from '../src/production/schema';
import {projectLegacyPresentationProfile} from '../src/workflow/profile-compatibility';
import narration from '../src/production/narration/craft-escape-v2.json';
const base='content-intelligence/cycles/cycle-10/revision-v3',old='content-intelligence/cycles/cycle-10/revision-v2',now=existsSync(`${base}/direction-v3.json`)?JSON.parse(readFileSync(`${base}/direction-v3.json`,'utf8')).provenance.enteredAt:new Date().toISOString(),root=process.cwd(),registry=loadMediaRegistry();
const read=(p:string):unknown=>JSON.parse(readFileSync(p,'utf8')),ref=(path:string)=>({path,sha256:mediaHash(path)});
const put=(n:string,d:unknown)=>{const path=`${base}/${n}.json`;mkdirSync(path.slice(0,path.lastIndexOf('/')),{recursive:true});if(process.argv.includes('--resume')&&existsSync(path))return ref(path);writeFileSync(path,JSON.stringify(d,null,2)+'\n',{flag:'wx'});return ref(path);};
let cycle=loadCycle(root,'cycle.10',registry);if(!process.argv.includes('--resume')){if(cycle.stage!=='master-review'||cycle.revision!==17||!cycle.candidate)throw new Error('Unexpected checkpoint');
put('preserved-v2-review-state',cycle);
put('preservation-bindings',{baselineCommit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),files:[cycle.candidate.path,'artifacts/masters/craft-escape-cycle10-candidate-v2.mp4',`${old}/knowledge-package.ready.json`,`${old}/content-asset.ready.json`,'src/production/narration/craft-escape-v2.json','src/captions/plans/craft-escape-v2.json',...narration.cues.map(c=>`public/${c.file}`)].map(ref),scope:'Unchanged189-word script, claims, inspected evidence, narration binaries, timing and previous masters; presentation-only refinement.'});
const decision=put('owner-master-revision',ownerDecisionSchema.parse({schemaVersion:3,id:'owner-decision.cycle-10.master-revision-v3',revision:1,gate:'master-review',cycleId:'cycle.10',targetSha256:sha256Json(read(cycle.candidate.path)),decision:'revise',enteredAt:now,suppliedReviewTime:null,reviewer:'Ahmet — owner',evidenceBasis:'explicit-owner-message',instruction:'Cycle10 V2 REVISION REQUEST. V2 NOT approved. Preserve stronger opening, tighter189-word narration, historical accuracy, evidence qualifications and progression. Focused visual/presentation refinement: reduce repeated static documentary slides, meaningful motion and transitions especially signing/Baltimore; make danger/uncertainty understandable without invented events/dialogue/footage/details; essential mobile hierarchy readable, source annotations secondary; audit pauses/caption sync and change timing only for demonstrated improvement; preserve agency/testimony distinction. Independent judgment; explain and retain stronger treatment if request would weaken truth/compellingness. V3 only for meaningful improvement; otherwise limitations/recommendation. Full required QA, exact master and concise V2/V3 comparison at AHMET MASTER REVIEW. Preserve all versions/history; no publication preparation/Cycle11/main merge.',reason:'Focused visual-storytelling and mobile presentation refinement; approved premise and V2 script retained.',acceptedUnknowns:[]}));
cycle=persistCycleEvent(root,cycle,{type:'owner-decision',record:decision,at:now},registry);
cycle=persistCycleEvent(root,cycle,{type:'retry-internal',stage:'creative',record:put('revision-scope',{cycleId:'cycle.10',reason:'Presentation refinement only; same verified editorial receipt and exact narration retained. New direction and production binding required.'}),at:new Date().toISOString()},registry);
cycle=persistCycleEvent(root,cycle,{type:'begin-internal',stage:'creative',record:put('creative-start',{cycleId:'cycle.10',stage:'creative',action:'Inspect V2 motion/hierarchy, recent approved portfolio; develop connected signing/checkpoint explanation.'}),at:new Date().toISOString()},registry);
}
const pkg=knowledgePackageSchema.parse(read(`${old}/knowledge-package.ready.json`)),asset=contentAssetSchema.parse(read(`${old}/content-asset.ready.json`));
const direction=creativeDirectionSchema.parse(read(`${old}/direction-v2.json`));
const inspection=put('portfolio-visual-inspection',{enteredAt:now,method:'Actual V2 scene overview/motion sheet and all four recent approved contact sheets inspected using view_image. Existing source-bound directions read. Current bounded set unchanged; no continuous playback or native feed proof.',works:direction.convergenceReview.recentAssets.map(a=>{const v=a.visualComparison!;if(v.creativeDirection)read(v.creativeDirection.path);return {master:v.master,approval:v.approval,inspectedVisuals:[v.inspectedVisuals[0]],findings:[v.overallImpression]};}),overallFeedImpression:'Recent work remains dark explanatory content above stable speech. For this same story the weak point is discrete document-slide replacement; connected explanatory objects and larger hierarchy improve understanding without forced domain/style change.'});
direction.id='creative-direction.craft-escape.v3';direction.revision=3;direction.provenance.enteredAt=now;direction.provenance.notes='Focused owner-requested presentation refinement; exact V2 script/audio retained. New current portfolio contact-sheet inspection; historical directions read. Internal artistic judgment, no owner master approval.';
direction.visualThesis='Connect the blank signature line to the bound-hand adaptation, and carry the same onward-travel question through Baltimore demand, appearance-versus-proof and discretionary release. Essential labels are large; authentic source reports remain secondary evidence objects.';
for(const d of direction.decisions){if(d.dimension==='visual-medium'||d.dimension==='art-direction'){d.treatment='Connected explanatory objects: route recedes into a blank register; the same signature line remains as the bound hand enters. Baltimore holds both named Crafts and an interrupted schematic onward-travel line; assurance demand, appearance/proof distinction and release change this same field.';d.rationale='Motion changes the information state, rather than decorating a completed slide. An unresolved line shows the vulnerability without claiming a physical gate, threat scene, countdown or original document.';}if(d.dimension==='platform-presentation'){d.treatment='Essential headings58px, core constraint labels42–50px and captions48px at1080width; source notes27px secondary. Inspect360px decoded previews and layout samples through transitions, not merely settled states.';}if(d.dimension==='pacing'){d.treatment='Retain exact V2 audio clips, starts and pauses,2447frames/81.5667seconds. Audit measured clip/sentence boundaries and caption timing; no demonstrated reason to shorten or retime. Use motion within existing time.';}}
for(const a of direction.convergenceReview.recentAssets){a.visualComparison!.inspectionRecord=inspection;a.visualComparison!.inspectedVisuals=a.visualComparison!.inspectedVisuals.slice(0,1);a.visualComparison!.dimensions.push({dimension:'object-continuity',observed:'V2 resets into mostly settled documentary panels.',proposed:'Keep signature and Baltimore question as continuous explanatory objects while their state changes.',reason:'The same unanswered question carries uncertainty forward; motion is causal and legible, without cinematic reenactment.'});}
direction.convergenceReview.conclusion='Same story/voice/evidence continuity retained; connected object movement and mobile hierarchy replace convenience-driven discrete slide resets. No decorative effect or forced visual variety.';
const dref=put('direction-v3',validateCreativeDirection(direction,pkg,asset,{registry}));
if(cycle.stage==='creative')cycle=persistCycleEvent(root,cycle,{type:'complete-internal',stage:'creative',record:dref,at:new Date().toISOString()},registry);
const profiles=read('artifacts/presentation-profiles.json') as {platform:string;lifecycle:string;id:string}[];
const profileRefs=['youtube','tiktok','instagram','facebook'].map(platform=>put(`profiles/${platform}`,projectLegacyPresentationProfile(profiles.find(p=>p.platform===platform&&p.lifecycle!=='HISTORICAL_SUPERSEDED'&&p.id.startsWith('safe-area.'))!,ref('artifacts/presentation-profiles.json'),ref('src/platform-variants/platform-profiles.ts'),now)));
const caption=JSON.parse(readFileSync('src/captions/plans/craft-escape-v2.json','utf8'));caption.id='caption-plan.craft-escape.v3';caption.revision=3;caption.creativeDirection={id:direction.id,revision:3,sha256:sha256Json(direction)};caption.visualTreatment.rendererId='renderer.craft-document-theatre-phrases.v3';
validateAdaptiveCaptionPlan(caption,narration.cues,narration.format,direction,asset);if(!existsSync('src/captions/plans/craft-escape-v3.json'))writeFileSync('src/captions/plans/craft-escape-v3.json',JSON.stringify(caption,null,2)+'\n',{flag:'wx'});
const plan=productionPlanV3Schema.parse(read('src/production/plans/craft-escape-v2.json'));plan.id='production-plan.craft-escape.v3';plan.revision=3;plan.creativeDirection=caption.creativeDirection;plan.presentationProfiles=profileRefs;plan.captions.captionPlanId=caption.id;plan.captions.captionPlanRevision=3;plan.captions.captionPlanSha256=sha256Json(caption);
for(const b of plan.beats){b.animationIntent='Connected signature/register and hand adaptation; continuous Baltimore onward-travel line and assurance question through demand, proof distinction and release. Essential labels42–50px, documentary sources secondary; other approved story beats retained.';b.transitionIntent='Move and replace information within a persistent explanatory field, avoiding hard card replacement and decorative motion.';}
for(const a of plan.assets)if(a.id==='craft-escape.narration')a.path='public/audio/craft-escape-v2/narration';
validateInternalProductionPlanReferences(plan,pkg,asset,direction);writeFileSync('src/production/plans/craft-escape-v3.json',JSON.stringify(plan,null,2)+'\n',{flag:'wx'});
put('timing-audit',{enteredAt:now,source:ref(`${old}/narration-clip-inspection.json`),narration:ref('src/production/narration/craft-escape-v2.json'),captionSource:ref('src/captions/plans/craft-escape-v2.json'),durationFrames:narration.durationFrames,words:189,decision:'Retain exact audio binaries, start times, pauses and55caption phrase intervals. Major sentence boundaries corroborated by inspected clip timestamps. No demonstrable timing defect found in that evidence; intra-sentence sync remains approximate and owner listening judgment. Visual changes follow existing speech rather than move speech to fit effects.',newTimingChanges:[],limitations:'Machine segment/geometry audit is not human acoustic listening or exact word forced alignment.'});
const start=put('production-start',{cycleId:'cycle.10',stage:'production',action:'Focused V3 connected visuals and mobile hierarchy; reuse exact V2 narration/caption timing, render and full QA; stop Master Review.'});persistCycleEvent(root,cycle,{type:'begin-internal',stage:'production',record:start,at:new Date().toISOString()},registry);
console.log('V3 presentation refinement in production; V2 preserved and not approved.');
