import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {loadMediaRegistry,mediaHash} from '../src/artifacts/media';
import {sha256Json} from '../src/content-intelligence/run-schema';
import {loadCycle,persistCycleEvent} from '../src/workflow/store';
import {knowledgePackageSchema} from '../src/knowledge/schema';
import {contentAssetSchema} from '../src/content-assets/schema';
import {verifyInternalEditorial} from '../src/workflow/editorial';
import {validateCreativeDirection} from '../src/content-assets/creative-direction-integrity';
import {recentApprovedVisualWorks} from '../src/content-assets/visual-convergence';
import {projectLegacyPresentationProfile} from '../src/workflow/profile-compatibility';
const old='content-intelligence/cycles/cycle-7/revision-2',base='content-intelligence/cycles/cycle-7/revision-3',now=new Date().toISOString(),registry=loadMediaRegistry();
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8')),ref=(path:string)=>({path,sha256:mediaHash(path)});
const put=(n:string,d:unknown)=>{const path=`${base}/${n}.json`;mkdirSync(path.slice(0,path.lastIndexOf('/')),{recursive:true});writeFileSync(path,JSON.stringify(d,null,2)+'\n',{flag:'wx'});return ref(path);};
const advance=(e:Parameters<typeof persistCycleEvent>[2])=>persistCycleEvent(process.cwd(),loadCycle(process.cwd(),'cycle.7',registry),e,registry);
const owner=put('owner-master-revision-v1',{schemaVersion:3,id:'owner-decision.cycle-7.ifm-master-revision.v1',revision:1,gate:'master-review',cycleId:'cycle.7',targetSha256:sha256Json(read(`${old}/master-candidate-v1.json`)),decision:'revise',enteredAt:now,suppliedReviewTime:null,reviewer:'Ahmet — owner',evidenceBasis:'explicit-owner-message',instruction:'REVISE MASTER — Cycle #7 replacement premise APPROVED; exact master NOT approved. Interaction-Free Measurement independently clears calibrated editorial threshold. Preserve question: How can light reveal an obstacle without being absorbed or reflected by it? Execution/cold-audience comprehension needs revision: fixed interferometer schematic dominates and asks simultaneous decoding of apparatus, paths, recombination, interference, cancellation, dark detector and click inference. Make visual causality lead terminology. Establish ONE photon, TWO possible paths, open-path cancellation and dark output; insert absorber; separate absorbed trials from successful dark-output click. Climax: obstacle detected + photon not absorbed in that successful trial. Explain blocked possible path removed cancellation; probabilistic with absorbed/inconclusive outcomes. Explore materially intuitive, dynamic, progressively simplified story treatments; suggestions are possibilities, not mandates. No literal classical half photons or scientific inaccuracies. Evaluate runtime honestly, reducing friction/holds without arbitrary limit or lost qualifications. No shallow clickbait, premise change, discovery, Cycle8, publication preparation, upload, scheduling or publication. Preserve scroll/rejection, IFM/revision/evidence/comparisons/journal/artifacts. Full normal QA/validation then AHMET — MASTER REVIEW with exact revised master/narration, comprehension changes, qualifications, QA and uncertainties. Faithful transcription; enteredAt is entry time, no supplied review time.',acceptedUnknowns:[]});
advance({type:'owner-decision',record:owner,at:now});
const retry=put('editorial-revision-scope',{cycleId:'cycle.7',ownerDecision:owner,reason:'Renew exact script and direction for approved premise; original discovery/selection retained. No discovery or new topic work.'});
advance({type:'retry-internal',stage:'editorial',record:retry,at:new Date().toISOString()});
const pkg=read(`${old}/draft-package.json`);pkg.revision=2;pkg.viewerPayoff='The click reveals a blocked possibility without absorption of the detected photon, while unsuccessful trials retain risk.';pkg.visualOpportunities[0].description='Progressive path construction, enlarged cancellation, separate trial outcomes and successful detector climax; original ideal model.';
const lines:[string,string[]][]=[
 ['How can light reveal an obstacle without being absorbed or reflected by it?',['detect']],
 ['Start with one photon and two possible paths that meet again.',['paths']],
 ['In this carefully aligned setup, the waves associated with the paths cancel at one output. This detector stays dark.',['dark','cancel']],
 ['Now block one path with an absorber.',['absorber','click']],
 ['Sometimes it absorbs the photon. That trial ends.',['absorber','fail']],
 ['But in another trial, the dark detector clicks.',['click']],
 ['The photon reached this detector. The obstacle was detected, without absorbing that photon.',['detect']],
 ['Why? Blocking one possible path removed the cancellation that kept this detector dark.',['cancel','click']],
 ['This is interaction-free measurement, demonstrated in experiments.',['demo']],
 ['It succeeds only in some trials. Others absorb the photon, or give no clear answer.',['fail']]
];
const objectives=['Pose approved no-absorption/reflection puzzle; withhold answer.','One input photon; progressively reveal two coherent alternatives and reunion.','Enlarge opposed probability amplitudes and their zero sum at dark output; other output retains photon possibility.','Introduce absorber only after baseline is understood.','A separate absorbed trial ends; no output click.','A different successful trial produces the formerly dark click.','Make detected obstacle and nonabsorbed photon the visual climax.','Compare cancellation with blocked alternative; remove opposing contribution at same output.','Name demonstrated effect after viewer understands the successful inference.','Retain probabilistic success, absorbed trials and inconclusive bright output.'];
const asset=read(`${old}/draft-asset.json`);asset.revision=2;asset.durationIntentSeconds={minimum:40,maximum:75};asset.script.segments=lines.map(([text,keys],i)=>({id:`${asset.id}.script.${i+1}`,type:'factual',text,claimIds:keys.map(k=>`${pkg.id}.claim.${k}`)}));asset.narrativeStructure=lines.map((_,i)=>({id:`${asset.id}.beat.${i+1}`,label:['puzzle','alternatives','cancellation','intervention','absorbed','successful','paradox','reason','name','qualification'][i],purpose:objectives[i],scriptSegmentIds:[asset.script.segments[i].id]}));asset.visualPlan=lines.map(([_,keys],i)=>({id:`${asset.id}.visual.${i+1}`,narrativeBeatId:asset.narrativeStructure[i].id,objective:objectives[i],visualType:'bespoke',suggestedPrimitive:'bespoke',scriptSegmentIds:[asset.script.segments[i].id],claimIds:keys.map(k=>`${pkg.id}.claim.${k}`),notes:'Progressive enlarged ideal-model possibilities, not measured photon trajectories. Exactly one event particle at source or output/absorption; path animation denotes amplitudes, never two half photons. Separate trials; no observed complete classical route.'}));asset.narrationPlan.pronunciationNotes=['Interaction-free.'];
const proposal=knowledgePackageSchema.parse(pkg),draft=contentAssetSchema.parse(asset),review=read(`${old}/internal-editorial-review.json`);review.enteredAt=now;review.packageSha256=sha256Json(proposal);review.assetSha256=sha256Json(draft);review.scriptSha256=sha256Json(draft.script);review.comprehensionReview='Owner approves premise, requests causal execution. New exact wording removes front-loaded interferometer jargon; one photon/two possibilities precede cancellation; intervention precedes two separately identified outcomes; successful nonabsorption is climax before explanatory return. Demonstration and probabilistic risks remain explicit. Source statements and qualifications unchanged; original inspected evidence records reused with original retrieval dates, not falsely reread or redated.';
put('draft-package',proposal);put('draft-asset',draft);put('internal-editorial-review',review);const ready=verifyInternalEditorial(review,proposal,draft);put('knowledge-package.ready',ready.knowledgePackage);put('content-asset.ready',ready.contentAsset);advance({type:'complete-internal',stage:'editorial',record:put('editorial-receipt',{draftPackage:proposal,draftAsset:draft,review}),at:new Date().toISOString()});
const direction=read(`${old}/direction-v1.json`),bind=(v:{id:string;revision:number})=>({id:v.id,revision:v.revision,sha256:sha256Json(v)});direction.id='creative-direction.interaction-free.v2';direction.revision=2;direction.knowledgePackage=bind(ready.knowledgePackage);direction.contentAsset=bind(ready.contentAsset);direction.approvedScriptSha256=sha256Json(draft.script);direction.provenance.enteredAt=now;direction.provenance.notes='Session revised from exact owner comprehension feedback. Actual recent approved-master sheets re-viewed; historical direction records read; original prior IFM sheet also viewed. No discovery or owner master approval.';
direction.visualThesis='Progressively reveal alternatives; leave the apparatus to enlarge cancellation, separate trial events, then expand the successful detector into a two-fact visual climax.';direction.viewerExperience='One photon, two possible routes, a visibly zero dark-output contribution; blocker, absorption, separate click, paradox, then before/after cancellation and honest trial qualification.';
const treatment='Progressive spatial path construction with moving amplitude ribbons; full-field cancellation demonstration; enlarged separate absorption and detection events; paired obstacle-detected/nonabsorbed-photon climax. No fixed optical bench, equipment jargon or simulated measured trajectory.';
const alternatives=[{treatment:'Keep the full fixed apparatus and improve labels, colors and pulse speed.',materialChanges:['More annotation and local highlight, same bench view.'],storyTradeoffs:'Preserves topology but retains owner-identified textbook decoding burden; rejected as insufficient comprehension change.'},{treatment:'Human-scale maze or railway analogy replacing quantum apparatus.',materialChanges:['Replace optical routes with familiar walkers or trains.','Use narrative action instead of amplitude representation.'],storyTradeoffs:'Approachable movement but invites classical definite path and literal divided objects; rejected because cancellation has no faithful classical-agent counterpart.'},{treatment:'Progressively constructed possibilities and enlarged cancellation, with separate event stages.',materialChanges:['Withhold nonessential hardware and labels.','Move from path space into full-field opposed amplitudes, then isolated trial events and large detector payoff.'],storyTradeoffs:'Reduces simultaneous decoding and distinguishes event from amplitude. Still an abstract ideal model; explicit path/amplitude disclosure and trial labels are necessary.'}];
const works=recentApprovedVisualWorks(now,asset.id);const priorInspection=read(`${old}/portfolio-visual-inspection.json`);for(const w of works){if(w.creativeDirection)read(w.creativeDirection.path);}
const inspection=put('portfolio-visual-inspection',{...priorInspection,enteredAt:now,method:'Session re-viewed actual four latest approved contact sheets and prior IFM candidate sheet; read bound historical directions. Overview sampled evidence only, no continuous playback or native feed.',ownerFeedback:owner,priorCandidate:ref(`${old}/master-candidate-v1.json`),overallFeedImpression:'Recent masters repeatedly use a central explanatory object above lower speech. Prior IFM remains essentially one bench. Proposed progressive route construction, enlarged zero-sum comparison and isolated detector climax change spatial organization and cognitive load; dark color/lower captions alone confer no distinction.'});
for(const d of direction.decisions){if(d.dimension==='visual-medium'){d.treatment=treatment;d.rationale='Teach one causal relationship at a time; preserve path identity but change scale and composition as attention moves.';d.alternativesConsidered=alternatives.map(a=>a.treatment);}if(d.dimension==='art-direction')d.treatment='Deep ink field, cyan/amber alternatives and warm absorber; dark output becomes a luminous event. No metal bench or serial equipment labels.';if(d.dimension==='hook')d.treatment='Single source photon and unlit detector separated by an unexplained obstacle. Reveal route relationships progressively after question.';if(d.dimension==='pacing')d.treatment='Connected plain-language narration; no initial equipment vocabulary. Event-scale transitions and brief causal holds; measured runtime rather than duration target.';}
for(const r of direction.convergenceReview.recentAssets){r.differences=['Progressive route construction and changing scene scale instead of fixed apparatus.','Full-field cancellation and separated absorption/success events, followed by paired-fact paradox climax.'];r.rationale='Owner identified actual fixed-bench comprehension friction. Rejected cosmetic polishing and classical-agent analogy; selected progressive amplitude/event treatment.';r.visualComparison.inspectionRecord=inspection;r.visualComparison.convenienceResponse={alternatives,resolution:treatment,chosenForStory:'The audience can register each causal prerequisite before seeing the extraordinary click. Representing alternatives separately from single detection/absorption events avoids half-photon and trajectory misconceptions.'};r.visualComparison.dimensions[0].proposed=treatment;r.visualComparison.dimensions[0].reason='Progressive disclosure and changing spatial scale reduce simultaneous apparatus decoding.';}
direction.convergenceReview.conclusion='Keep necessary quantum diagram representation but reject fixed-bench convenience. Progressively constructed paths, enlarged cancellation and event-led climax carry explanation; no forced palette rotation.';direction.convergenceReview.portfolioReview.proposedFeedImpression=treatment;direction.convergenceReview.portfolioReview.toolingBiasCheck='Reuse typography/QA engineering only; new story primitive and stage layout replace fixed OpticalBench. Classical-agent analogy rejected for factual cost, cosmetic fixed-bench revision rejected for comprehension.';
const dref=put('direction-v2',validateCreativeDirection(direction,ready.knowledgePackage,ready.contentAsset,{registry}));advance({type:'complete-internal',stage:'creative',record:dref,at:new Date().toISOString()});
const psource=ref('artifacts/presentation-profiles.json'),esource=ref('src/platform-variants/platform-profiles.ts'),profiles=read(psource.path) as {platform:string;lifecycle:string;id:string}[];for(const platform of ['youtube','tiktok','instagram','facebook']){const p=profiles.find(p=>p.platform===platform&&p.lifecycle!=='HISTORICAL_SUPERSEDED'&&p.id.startsWith('safe-area.'));if(!p)throw new Error('Missing profile');put(`profiles/${platform}`,projectLegacyPresentationProfile(p,psource,esource,now));}
advance({type:'begin-internal',stage:'production',record:put('production-start',{cycleId:'cycle.7',stage:'production',action:'Revised progressive causal visuals, connected narration, designed captions, smoke/full render and complete local QA; no publication preparation.'}),at:new Date().toISOString()});
console.log('Approved premise retained; exact script/direction renewed; production begun.');
