import {readFileSync,writeFileSync,statSync,mkdirSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {mediaHash,mediaArtifactSchema} from '../src/artifacts/media';
import {persistMediaArtifact} from '../src/artifacts/catalog';
const base='content-intelligence/cycles/cycle-7/revision-2',path='artifacts/masters/interaction-free-cycle7-candidate-v1.mp4',sourceCommit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),now=new Date().toISOString();
mkdirSync(`${base}/qa`,{recursive:true});
const record=`${base}/qa/production-iteration-v1.json`;
writeFileSync(record,JSON.stringify({enteredAt:now,media:{path,sha256:mediaHash(path)},sourceBaseCommit:sourceCommit,implementationBeforeRevision:['src/components/OpticalBench.tsx','src/compositions/InteractionFree.tsx'].map(path=>({path,currentFileSha256:mediaHash(path),snapshotBasis:'Original unsubmitted source reconstructed by reversing the sole53px result-curve translation; other source unchanged.',sourceText:readFileSync(path,'utf8').replace('translate(498 0) scale(.68 1)','translate(445 0) scale(.68 1)')})),technical:JSON.parse(readFileSync('qa/interaction-free/report.json','utf8')),layout:{scope:'Original v1 browser observations from saved log, before correction; sampled outer bounds only.',observations:readFileSync('/tmp/magnivis-ifm-layout.log','utf8').split('\n').filter(l=>l.includes('IFM_LAYOUT_QA ')).map(l=>JSON.parse(l.slice(l.indexOf('IFM_LAYOUT_QA ')+14)))},audio:JSON.parse(readFileSync('qa/interaction-free/audio-inspection.json','utf8')),finding:'Full-size decoded38.5s frame shows result wave crossing equals sign. Outer-bound checks do not detect this interior overlap. Draft fails final visual readiness; not a submitted master or owner decision.',disposition:'preserve-and-revise-own-unapproved-replacement',change:'Move only result curve53px right. No script, claims, timing, narration, direction or prior rejected Sealed Scroll changes.'},null,2)+'\n',{flag:'wx'});
persistMediaArtifact(mediaArtifactSchema.parse({id:`media.${mediaHash(path)}`,sha256:mediaHash(path),canonicalPath:path,mediaType:'video/mp4',bytes:statSync(path).size,provenance:{kind:'original-production',sourceCommit,sourceRecords:[record,`${base}/audio-mastering.json`],createdAt:now,creationTimeUnknownReason:null},parents:[]}));
