import {chladniSand} from '../src/content/videos/chladni-sand';
import chladniCaptions from '../src/captions/plans/chladni.json';
import chladniPlan from '../src/production/plans/chladni.json';
import {chocolateCrystalChoice} from '../src/content/videos/chocolate-crystal-choice';
import {paperHalfShape} from '../src/content/videos/paper-half-shape';
import paperCaptions from '../src/captions/plans/paper.json';
import paperPlan from '../src/production/plans/paper.json';
import chocolateCaptions from '../src/captions/plans/chocolate.json';
import chocolatePlan from '../src/production/plans/chocolate.json';
import {longitudeClockLocked} from '../src/content/videos/longitude-clock-locked';
import {longitudeClockV2} from '../src/content/videos/longitude-clock-v2';
import captionsV2 from '../src/captions/plans/longitude-clock-v2.json';
import planV2 from '../src/production/plans/longitude-clock-v2.json';
import {resolveVideoTarget as resolveHistoricalTarget} from './video-targets';
import {longitudeClock} from '../src/content/videos/longitude-clock';
import captions from '../src/captions/plans/longitude-clock.json';
import plan from '../src/production/plans/longitude-clock.json';
export const longitudeTarget={spec:longitudeClock,entryPoint:'src/longitude-index.tsx',output:'output/longitude-clock-narrated.mp4',qaDirectory:'qa/longitude-clock-narrated',qaTimestamps:[...new Set([0,0.5,...plan.beats.flatMap(b=>[b.frames.start/30+0.1,(b.frames.start+b.frames.end)/60,(b.frames.end-1)/30]),...captions.cues.map(c=>(c.startFrame+c.endFrame)/60)])].sort((a,b)=>a-b)};
export const longitudeV2Target={spec:longitudeClockV2,entryPoint:'src/longitude-v2-index.tsx',output:'output/longitude-clock-narrated-v2.mp4',qaDirectory:'qa/longitude-clock-narrated-v2',qaTimestamps:[...new Set([0,0.5,...planV2.beats.flatMap(b=>[b.frames.start/30+0.1,(b.frames.start+b.frames.end)/60,(b.frames.end-1)/30]),...captionsV2.cues.map(c=>(c.startFrame+c.endFrame)/60)])].sort((a,b)=>a-b)};
export const chocolateTarget={spec:chocolateCrystalChoice,entryPoint:'src/chocolate-index.tsx',output:'output/chocolate-crystal-choice-candidate-v1.mp4',qaDirectory:'qa/chocolate-crystal-choice-candidate-v1',qaTimestamps:[...new Set([0,0.5,16.9,18.9,34.6,39.6,...chocolatePlan.beats.flatMap(b=>[b.frames.start/30+0.1,(b.frames.start+b.frames.end)/60,(b.frames.end-1)/30]),...chocolateCaptions.cues.map(c=>(c.startFrame+c.endFrame)/60)])].sort((a,b)=>a-b)};
export const paperTarget={spec:paperHalfShape,entryPoint:'src/paper-index.tsx',output:'artifacts/masters/paper-half-shape-candidate-v1.mp4',qaDirectory:'qa/paper-half-shape',qaTimestamps:[...new Set([0,.5,...paperPlan.beats.flatMap(b=>[b.frames.start/30+.1,(b.frames.start+b.frames.end)/60,(b.frames.end-1)/30]),...paperCaptions.cues.map(c=>Math.floor((c.startFrame+c.endFrame)/2)/30)])].sort((a,b)=>a-b)};
export const chladniTarget={spec:chladniSand,entryPoint:'src/chladni-index.tsx',output:'artifacts/masters/chladni-sand-candidate-v1.mp4',qaDirectory:'qa/chladni-sand',qaTimestamps:[...new Set([0,.5,1.5,2.4,...chladniPlan.beats.flatMap(b=>[b.frames.start/30+.1,(b.frames.start+b.frames.end)/60,(b.frames.end-1)/30]),...chladniCaptions.cues.map(c=>Math.floor((c.startFrame+c.endFrame)/2)/30)])].sort((a,b)=>a-b)};
export const resolveProductionVideoTarget=(id:string)=>id==='chladni-sand'?chladniTarget:id==='paper-half-shape'?paperTarget:id==='chocolate-crystal-choice'?chocolateTarget:id==='longitude-clock-locked'?{...longitudeV2Target,spec:longitudeClockLocked,output:'artifacts/masters/longitude-clock-candidate-v2.mp4'}:id==='longitude-clock-v2'?longitudeV2Target:id==='longitude-clock'?longitudeTarget:resolveHistoricalTarget(id);
