import {createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {createPlatformVariantRegistry} from '../src/platform-variants/registry';
import type {PlatformVariant} from '../src/platform-variants/schema';
import {deliveryDependencies, type DeliveryDependencies} from './delivery-packages';
import {resolveVideoTarget} from './video-targets';

export const recoveryMediaPath = (videoId: string) => {
  resolveVideoTarget(videoId);
  return resolve('recovery-work', videoId, `${videoId}-narrated.mp4`);
};

export const createRecoveryDeliveryContext = (
  originals: readonly PlatformVariant[],
  masterPath = recoveryMediaPath('wood-frog'),
) => {
  const variants = originals.map((original) => {
    const variant = structuredClone(original);
    variant.id = `${original.id}.recovery-phase-1`;
    variant.revision = 1;
    variant.status = 'editorial-review';
    variant.approval = undefined;
    variant.previewStatus = 'not-ready';
    variant.productionIntent.platformPreviewRequired = true;
    variant.productionIntent.notes = 'RECOVERY-GENERATED DELIVERY PACKAGE. Local technical reconstruction only; no visual, platform or publication approval for regenerated bytes.';
    // Retain a locked source chain only when the staging master is byte-identical.
    // Otherwise the original identity belongs solely in the separate recovery record.
    if (variant.sourceMaster) {
      const hash = createHash('sha256').update(readFileSync(masterPath)).digest('hex');
      if (hash === variant.sourceMaster.artifact.sha256) {
        variant.sourceMaster.artifact.path = masterPath;
      } else {
        variant.sourceMaster = undefined;
      }
    }
    return variant;
  });
  const variantRegistry = createPlatformVariantRegistry(variants);
  const dependencies: DeliveryDependencies = {
    ...deliveryDependencies,
    variantRegistry,
    productionResolver: (variant) => {
      const target = resolveVideoTarget(variant.productionIntent.videoSpecId);
      const spec = structuredClone(target.spec);
      if (spec.platformVariantId) spec.platformVariantId = variant.id;
      if (spec.production && !variant.sourceMaster) {
        spec.production.outputReviewState = 'visual-review-required';
      }
      return {spec, sourceVideoPath: recoveryMediaPath(target.spec.id)};
    },
  };
  return {variants: variantRegistry.list(), dependencies};
};
