import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {mediaHash,loadMediaRegistry} from '../src/artifacts/media';
import {sha256Json} from '../src/content-intelligence/run-schema';
import {cycleDeliverySchema,cycleReleaseSchema,inspectCycleRelease} from '../src/workflow/release';
const base='content-intelligence/cycles/cycle-10/publication',read=(p:string)=>JSON.parse(readFileSync(p,'utf8'));
const put=(name:string,data:unknown)=>{const path=`${base}/${name}.json`;mkdirSync(`${base}/tiktok`,{recursive:true});writeFileSync(path,JSON.stringify(data,null,2)+'\n',{flag:'wx'});return {path,sha256:mediaHash(path)};};
const release=cycleReleaseSchema.parse(read(`${base}/release-v1.json`)),entry=release.deliveries.find(d=>d.variant.platform==='tiktok')!;
const metadata=read(`${base}/tiktok/metadata-v1.json`);
metadata.firstComment='Brown’s1849 report supports the signing strategy. The detailed Baltimore checkpoint comes from William Craft’s1860 account.'.replace('Brown’s1849','Brown’s 1849').replace('Craft’s1860','Craft’s 1860');
if(metadata.firstComment.length>150)throw new Error('Conservative comment envelope exceeded');
metadata.description+='\n\nSources: William Craft (1860), https://docsouth.unc.edu/neh/craft/craft.html ; Brown report (1849), https://fair-use.org/the-liberator/1849/01/12/the-liberator-19-02.pdf';
metadata.variantId='craft-escape.variant.tiktok.v2';
metadata.commentEnvelope={maximum:150,basis:'Conservative internal limit; exact live TikTok comment limit not verified from accessible official policy. No universal native limit asserted.'};
const mref=put('tiktok/metadata-v2',metadata);
const text=readFileSync(`${base}/tiktok/upload-copy-v1.txt`,'utf8').replace(read(`${base}/tiktok/metadata-v1.json`).description,metadata.description).replace(read(`${base}/tiktok/metadata-v1.json`).firstComment,metadata.firstComment);
const copyPath=`${base}/tiktok/upload-copy-v2.txt`;writeFileSync(copyPath,text,{flag:'wx'});
entry.variant={...entry.variant,id:metadata.variantId,revision:2};
const manifest=cycleDeliverySchema.parse({...read(entry.manifest.path),id:'delivery.cycle-10.tiktok.v2',variantSha256:sha256Json(entry.variant),metadata:mref,uploadCopy:{path:copyPath,sha256:mediaHash(copyPath)}});
entry.manifest=put('tiktok/manifest-v2',manifest);
const result=inspectCycleRelease(release,loadMediaRegistry(),new Date().toISOString()),ref=put('release-v2',release);
const risks=read(`${base}/risk-register-v1.json`);risks.release=ref;risks.targetSha256=sha256Json(release);risks.inspectionTime=new Date().toISOString();risks.requiredExactPresentationUnknowns=result.unknowns;
put('risk-register-v2',risks);
put('copy-constraints-v1',{passed:true,reason:'Shorten TikTok first comment to a conservative150character envelope and move participant/early-report source URLs into its post caption. Accessible official policy did not establish a universal comment limit. Preserve first proposal rather than silently rewriting its hashes.',tiktok:{firstCommentCharacters:metadata.firstComment.length,captionCharacters:metadata.description.length},supersedes:{release:`${base}/release-v1.json`,tiktokManifest:`${base}/tiktok/manifest-v1.json`},currentRelease:ref,videoChanged:false,claimsChanged:false});
console.log(JSON.stringify({target:sha256Json(release),unknowns:result.unknowns.length,tiktokComment:metadata.firstComment.length}));
