import {existsSync,readFileSync,readdirSync,writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {extname} from 'node:path';
import {parseManifests,type ArtifactManifest} from '../src/artifacts/schema';
import {chocolateMasterDecision as decision,chocolateFileHash as hash} from '../src/production/chocolate-master-integrity';
import {stableJson} from '../src/content-intelligence/run-schema';
const collection='artifacts/chocolate-crystal-choice-platform-manifests.json';
try{execFileSync('git',['cat-file','-e',`HEAD:${collection}`],{stdio:'pipe'});throw new Error('Committed milestone is immutable; create a new collection/revision.');}catch(e){if(e instanceof Error&&e.message.startsWith('Committed milestone'))throw e;}
const recordedAt=new Date().toISOString();const files=(d:string):string[]=>readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(`${d}/${e.name}`):[`${d}/${e.name}`]);
const paths=[decision.artifact.path,'artifacts/covers/chocolate-crystal-choice-instagram-cover-v1.png','artifacts/chocolate-crystal-choice-cover-assets.json',...files('content-intelligence/reviews/chocolate-crystal-choice-master-lock-v1'),...files('content-intelligence/reviews/chocolate-crystal-choice-platform-v1'),...files('artifacts/qa-evidence/chocolate-crystal-choice-platform-v1'),...files('artifacts/deliveries/chocolate-crystal-choice-v1')].sort();
const previous:ArtifactManifest[]=existsSync(collection)?parseManifests(JSON.parse(readFileSync(collection,'utf8'))):[];
for(const p of previous)if(hash(p.localPath)!==p.identity.sha256)throw new Error('Previously registered bytes changed: '+p.localPath);
const records:ArtifactManifest[]=[...previous];for(const path of paths.filter(p=>!previous.some(r=>r.localPath===p))){const index=records.length,isMaster=path===decision.artifact.path,isCover=path==='artifacts/covers/chocolate-crystal-choice-instagram-cover-v1.png';const extension=extname(path);records.push({schemaVersion:1,artifactId:isMaster?decision.masterArtifactId:isCover?'chocolate-crystal-choice.instagram-cover.v1':`chocolate-crystal-choice.platform-v1.${index}`,contentId:'chocolate-crystal-choice',artifactType:isMaster?'video-master':isCover?'cover-image':path.includes('/deliveries/')?'delivery-file':'qa-evidence',revision:1,identity:{sha256:hash(path),bytes:readFileSync(path).length,mimeType:extension==='.mp4'?'video/mp4':extension==='.png'?'image/png':extension==='.jpg'?'image/jpeg':extension==='.json'?'application/json':'text/plain'},createdAt:null,creationUnknownReason:'File creation time is not an authoritative editorial or approval event.',recordedAt,sourceCommit:decision.reviewedCommit,productionPlanId:decision.reviewedProductionPlan.id,captionPlanId:decision.captionPlan.id,platformVariantId:null,approvalDecisionId:isMaster?decision.id:null,approvalScope:isMaster?'owner-visual':'none',publication:'not-authorized',localPath:path,locations:[{provider:'git',key:path,durability:'git-tracked'}],provenance:'ORIGINAL_PRODUCTION',retention:'DURABLE_REQUIRED',historicalSha256:null,historicalStatus:'new-production',replacesArtifactId:null,parentArtifactIds:isMaster?[decision.candidateArtifactId]:[decision.masterArtifactId],exactBytesMatter:true,reproducibility:{status:isMaster?'hash-only':'derived',recipe:null,evidence:['content-intelligence/reviews/chocolate-crystal-choice-platform-v1/owner-review.md']}});}
writeFileSync(collection,stableJson(parseManifests(records),2)+'\n');console.log(JSON.stringify({registered:records.length,appended:records.length-previous.length,masterArtifactId:decision.masterArtifactId}));
