import {readFileSync,renameSync,statSync,writeFileSync} from 'node:fs';
import {openMediaCatalog,persistMediaArtifact} from '../src/artifacts/catalog';
import {mediaArtifactSchema,mediaHash} from '../src/artifacts/media';
import {preflightMediaRegistration} from '../src/artifacts/durability';
const base='content-intelligence/cycles/cycle-9',inspection=JSON.parse(readFileSync(`${base}/qa/visual-inspection.json`,'utf8')) as {inspectedVisuals:{path:string;sha256:string}[]};
const registry=openMediaCatalog(),master=registry.byHash(mediaHash('artifacts/masters/two-goals-cycle9-candidate-v1.mp4'))!;
preflightMediaRegistration(inspection.inspectedVisuals.filter(v=>!registry.byHash(v.sha256)).map(v=>v.path));
const retained=inspection.inspectedVisuals.map(v=>{const existing=registry.byHash(v.sha256);if(existing)return {observedPath:v.path,media:{id:existing.id,sha256:existing.sha256},canonicalPath:existing.canonicalPath};if(mediaHash(v.path)!==v.sha256)throw new Error('Inspected capture drift');const path=`artifacts/qa-evidence/two-goals-cycle9-v1/${v.path.split('/').at(-1)}`;renameSync(v.path,path);const media=persistMediaArtifact(mediaArtifactSchema.parse({id:`media.${v.sha256}`,sha256:v.sha256,canonicalPath:path,mediaType:'image/png',bytes:statSync(path).size,provenance:{kind:'evidence-snapshot',sourceCommit:master.provenance.sourceCommit,sourceRecords:[`${base}/qa/visual-inspection.json`,'scripts/qa.ts','scripts/retain-two-goals-inspection.ts'],createdAt:statSync(path).birthtime.toISOString(),creationTimeUnknownReason:null},parents:[{id:master.id,sha256:master.sha256}]}));return {observedPath:v.path,media,canonicalPath:path};});
writeFileSync(`${base}/qa/inspection-capture-retention.json`,JSON.stringify({enteredAt:new Date().toISOString(),inspection:{path:`${base}/qa/visual-inspection.json`,sha256:mediaHash(`${base}/qa/visual-inspection.json`)},retained,note:'Observed scratch paths resolved to one immutable canonical payload each; no image regeneration or same-byte copies.'},null,2)+'\n',{flag:'wx'});
