import {readFileSync,writeFileSync} from 'node:fs';
import {mediaHash,loadMediaRegistry} from '../src/artifacts/media';
import {chooseTopicAutonomously} from '../src/workflow/topic-selection';
import {loadCycle,persistCycleEvent} from '../src/workflow/store';
const base='content-intelligence/cycles/cycle-6/revision-2';
const ref=(path:string)=>({path,sha256:mediaHash(path)});
const search=ref(`${base}/discovery-search.json`);
const history=JSON.parse(readFileSync('content-intelligence/cycles/cycle-6/topic-selection.json','utf8')).historyReviewed;
type Lead=[string,string,string[],string,string,string,string,boolean];
const initial:Lead[]=[
 ['diamond','The Hope Diamond travelled by ordinary mail',['institutional-history','logistics'],'Why was a famous diamond sent in a plain postal package?','Its value and ordinary packaging conflict immediately.','Institutional transfer and insured mail explain the decision, but the payoff risks being merely a delivery anecdote.','Interesting before execution; modest eventual understanding, below opportunity threshold.',false],
 ['kevlar','Cloudy polymer solution became a strong fiber',['materials','invention'],'How did an apparently bad mixture lead to a stronger fiber?','Contradiction needs context about laboratory expectations.','Explain molecular alignment only after a fuller materials audit; discovery chance alone is an interesting-after-context fact.','Context-led; not yet an exceptional plain premise.',false],
 ['hidden-text','Recovering erased writing',['cultural-preservation','imaging'],'How can erased text still be read?','An apparent information loss leaves a clear recovery question.','Different wavelengths expose remaining material contrast; exact text/recovery must be object specific.','Legitimate information gap; first lead lacks a consequential reveal.',false],
 ['ceres','Bright deposits on Ceres',['planetary-science'],'What are the bright spots on Ceres?','Image asks a cause, but plain wording relies on existing space interest.','Composition and surface processes could yield an explanation; initial lead not audited.','Not yet a strong broadly accessible question without the picture.',false],
 ['heat-barrier','Hotter surface, longer-lived water',['heat-transfer','fluid-physics'],'Why can a hotter surface make water last longer?','Contradicts an everyday expectation without needing field interest.','A vapor layer might explain the reversal; establish conditional experimental scope and whether payoff exceeds a name.','Promising premise; initial search lead alone does not yet justify advancement.',false],
];
const developed:Lead[]=[
 ['heat-barrier','Why a hotter pan can make a drop last longer',['heat-transfer','fluid-physics'],'Why can a hotter pan make a drop of water last longer?','A familiar heat-and-water expectation predicts the opposite; a plain question creates a strong specific information gap.','Heat makes vapor; vapor supports the liquid away from metal; the poorly conducting gap slows heat transfer. Temperature and thermal contact are distinct. Experimental boundary and continued evaporation keep the payoff honest.','Clears overall threshold independently: immediate contradiction plus substantial causal understanding. Not selected for cheap diagrams, ease of sourcing, previous science or a danger frame.',true],
 ['star','A star fades beyond visible detection',['stellar-evolution','scientific-investigation'],'Did a disappearing star become a black hole, or hide behind dust?','A massive familiar object disappearing creates strong curiosity even with truthful uncertainty.','Infrared persistence and competing energy/dust models would explain why optical disappearance alone does not establish a black hole.','Strong premise and investigation route; inspected competing research prevents a definitive collapse reveal. Keep eligible for a deeper investigation, no mystery bonus. Heat story has a complete experimentally established causal payoff.',true],
 ['auction','Winning can reveal an overestimate',['economics','reasoning'],'Why can winning an auction be evidence that you guessed too high?','Winning normally sounds like success; conditioning on the highest noisy estimate reverses that intuition.','Common-value selection bias and rational conditioning, not a curse or all-auctions rule.','Strong rival with meaningful transferable reasoning. Needs common-value setup before the gap resolves; heat contradiction requires less setup while delivering equally real mechanism.',true],
 ['hidden-text','Imaging an erased manuscript',['cultural-preservation','imaging'],'How can you read writing someone erased?','Clear task that appears impossible.','Residual ink/surface differences detected across wavelengths; recovered letter content should matter, not just instrument name.','Legitimate but this lead has a weaker consequential reveal; no borrowed historical-owner example bank.',false],
 ['wetness','Skin infers wetness from combined signals',['perception','neuroscience'],'How can dry cold contact feel wet?','Recognizable perceptual mismatch invites an answer.','Combined thermal and mechanical cues can account for wetness perception; no-receptors claim must not become cannot-feel-water.','Interesting meaningful explanation, but current evidence access is a review lead and the stripped question is less arresting than heat reversal. No medical advice.',false],
];
const candidate=(l:Lead,round:number)=>({id:l[0],subject:l[1],domains:l[2],novelty:'Distinct central question from existing cycle topics; no topic-history similarity requirement.',evidenceFeasibility:l[0]==='heat-barrier'&&round===2?'Two peer-reviewed experimental bodies and university-hosted experimental explanation inspected with access limitations. Conditional reversal and thermal mechanism supportable.':l[0]==='star'?'NASA body and primary competing preprint abstract/introduction inspected; controversy must remain explicit.':'Credible institutional/primary lead, not claim verification; source inspection required if selected.',explanatoryPayoff:l[5],visualPotential:l[0]==='heat-barrier'?'Paired contact/no-contact behavior and enlarged vapor gap make an invisible causal barrier legible.':'A story-specific visual route may be possible; no inherited renderer advantage.',audienceCuriosity:l[4],productionFeasibility:'Original or properly licensed execution feasible in principle; feasibility is a constraint, never a ranking reward.',portfolioDiversity:'Domains assigned after discovery. No quotas, rotations, whitelist or historical-domain preference.',comparison:l[6],evidence:[search],disposition:'eligible' as const,limitations:['Qualitative editorial judgment is not a prediction of views or owner approval.','Lead-level evidence remains distinct from verified selected claims.'],curiosityReview:{honestPremise:l[3],coldAudienceReason:l[4],interestOrigin:(l[0]==='kevlar'||l[0]==='ceres'?'context-led':'premise-led') as 'context-led'|'premise-led',storyRoute:l[5],truthBoundary:{state:'credible-lead' as const,rationale:l[0]==='heat-barrier'?'Can, across-regime reversal only; no hotter-always law, fixed pan temperature or immunity to burns.':l[0]==='star'?'Disappearance in visible light is observed; black-hole interpretation remains contested, not a settled reveal.':'Specific empirical or historical scope required, no manufactured mystery or superlative.'},opportunityJudgment:{sufficient:l[7],rationale:l[6]},shareability:null}});
const result=await chooseTopicAutonomously({maximumRounds:3,discoverAndCompare:async(round)=>({schemaVersion:3,cycleId:'cycle.6',method:'qualitative-open-world-comparison',searchRecord:search,searchBreadth:'Fresh institutional and primary discovery across objects, inventions, archives, astronomy, markets, perception and physical phenomena; classify only afterward. No owner conversational example bank or domain order.',classificationAfterDiscovery:true,historyReviewed:history,analyticsInfluence:'provenance-bearing-signals-not-category-rules',convenienceAdvantageRejected:true,selectionStandard:'cold-audience-curiosity.v1',poolReview:round===1?{adequateOpportunityFound:false,rationale:'Initial leads contain facts that become interesting with context and intriguing questions whose payoff or evidence scope is not established. The most promising heat reversal still needs primary support; do not force a winner.',nextSearchChange:'Broaden to markets, perception and current astrophysical investigation; deepen the thermal lead against primary lifetime and heat-transfer evidence, compare plain questions and actual payoffs.'}:{adequateOpportunityFound:true,rationale:'The pool now contains independently compelling opportunities: everyday heat reversal with established mechanism, auction conditioning with reasoning payoff, and optical disappearance with a legitimate competing-model investigation. Heat clears an absolute premise/payoff judgment before relative comparison; no minimum score, category target or required pool size grants sufficiency.',nextSearchChange:null},candidates:(round===1?initial:developed).map(l=>candidate(l,round)),selectedId:round===1?null:'heat-barrier',outcome:round===1?'continue-discovery':'selected',rationale:round===1?'Preserve insufficient first replacement pool and continue with a changed search.':'Choose the hotter-pan question because it is unusually arresting in plain words and resolves into a general understanding of thermal contact, rather than a trivia answer. Complete experimental support allows truthful accessible payoff. Strong rival opportunities make comparison meaningful, but best-in-pool status alone does not authorize selection.'}),preserve:async(s)=>{const path=`${base}/topic-pool-${s.outcome==='selected'?2:1}.json`;writeFileSync(path,JSON.stringify(s,null,2)+'\n',{flag:'wx'});return ref(path);}});
if(result.outcome!=='selected'||!result.record)throw new Error('Preserve unfinished discovery; no forced topic.');
writeFileSync(`${base}/topic-selection-session.json`,JSON.stringify({maximumRounds:3,consumedRounds:2,outcome:result.outcome,records:result.records,priorRejectedSelection:'content-intelligence/cycles/cycle-6/topic-selection.json'},null,2)+'\n',{flag:'wx'});
const registry=loadMediaRegistry();persistCycleEvent(process.cwd(),loadCycle(process.cwd(),'cycle.6',registry),{type:'complete-internal',stage:'discovery',record:result.record,at:new Date().toISOString()},registry);
console.log('Heat barrier selected in replacement round 2; Cycle #6 advances to editorial.');
