import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {loadMediaRegistry,mediaHash} from '../src/artifacts/media';
import {sha256Json} from '../src/content-intelligence/run-schema';
import {loadCycle,persistCycleEvent} from '../src/workflow/store';
import {ownerDecisionSchema} from '../src/workflow/evidence';
const base='content-intelligence/cycles/cycle-10/publication';mkdirSync(base,{recursive:true});
const put=(n:string,d:unknown)=>{const path=`${base}/${n}.json`;writeFileSync(path,JSON.stringify(d,null,2)+'\n',{flag:'wx'});return {path,sha256:mediaHash(path)};};
const registry=loadMediaRegistry(),root=process.cwd(),cycle=loadCycle(root,'cycle.10',registry);
if(cycle.stage!=='master-review'||cycle.revision!==23||!cycle.candidate)throw new Error('Unexpected approval checkpoint');
const candidate=JSON.parse(readFileSync(cycle.candidate.path,'utf8'));
const master='artifacts/masters/craft-escape-cycle10-candidate-v3.mp4';
if(mediaHash(master)!=='b8e1e4433ec33ee4de08eb6dbd3b9c9a27e73f457245ab49bc67aac1a0e531fc')throw new Error('Exact V3 master drift');
put('preserved-master-review-state',cycle);
const instruction='Cycle #10 — AHMET MASTER REVIEW: FINAL APPROVAL. I confirm that I have reviewed the exact V3 master and that pronunciation, caption synchrony, and mobile presentation are acceptable. The conditional approval is now final. Approve and freeze the exact V3 master. Proceed autonomously with the four platform-specific publication packages, including captions, covers, descriptions, sources, disclosures, first comments, safe-area validation, and delivery QA. Stop at AHMET — PUBLICATION REVIEW / AUTHORIZATION. Do not upload, schedule, publish, begin Cycle #11, or merge into main without separate authorization. Preserve all prior versions and historical records.';
const decision=put('master-approval-v1',ownerDecisionSchema.parse({schemaVersion:3,id:'owner-decision.cycle-10.master-approval-v3',revision:1,gate:'master-review',cycleId:'cycle.10',targetSha256:sha256Json(candidate),decision:'approve',enteredAt:new Date().toISOString(),suppliedReviewTime:null,reviewer:'Ahmet — owner',evidenceBasis:'explicit-owner-message',instruction,acceptedUnknowns:[]}));
let state=persistCycleEvent(root,cycle,{type:'owner-decision',record:decision,at:new Date().toISOString()},registry);
put('master-lock-v1',{cycleId:cycle.id,master:candidate.media,path:master,candidate:cycle.candidate,decision,conditionalAcceptance:{path:'content-intelligence/cycles/cycle-10/revision-v3/conditional-owner-approval.json',sha256:mediaHash('content-intelligence/cycles/cycle-10/revision-v3/conditional-owner-approval.json')},frozen:true,ownerAccepts:['pronunciation','caption synchrony','mobile presentation of exact master'],suppliedReviewTime:null,platformDeviceEvidence:'No platform, device, OS, app version, test time or screenshot supplied; native platform evidence remains not-tested.',publicationAuthorized:false});
const start=put('presentation-start-v1',{cycleId:cycle.id,stage:'presentation',action:'Prepare four exact-master packages, original cover, copy and evidence. No public operation or approval transfer; preserve prior records.'});
state=persistCycleEvent(root,state,{type:'begin-internal',stage:'presentation',record:start,at:new Date().toISOString()},registry);
console.log(JSON.stringify({stage:state.stage,revision:state.revision,master:candidate.media,publicationAuthorized:false}));
