import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {loadMediaRegistry,mediaHash} from '../src/artifacts/media';
import {sha256Json} from '../src/content-intelligence/run-schema';
import {loadCycle,persistCycleEvent} from '../src/workflow/store';
import {ownerDecisionSchema} from '../src/workflow/evidence';
const base='content-intelligence/cycles/cycle-11/publication';mkdirSync(base,{recursive:true});
const put=(n:string,d:unknown)=>{const path=`${base}/${n}.json`;writeFileSync(path,JSON.stringify(d,null,2)+'\n',{flag:'wx'});return {path,sha256:mediaHash(path)};};
const registry=loadMediaRegistry(),root=process.cwd(),cycle=loadCycle(root,'cycle.11',registry);
if(cycle.stage!=='master-review'||cycle.revision!==14||!cycle.candidate)throw new Error('Unexpected approval checkpoint');
const candidate=JSON.parse(readFileSync(cycle.candidate.path,'utf8'));
const master='artifacts/masters/vermeer-forgery-cycle11-candidate-v2.mp4';
if(mediaHash(master)!=='f6d6da416f45aef07d7ac61eac232eadce5a854b9cd97094162849a70ee98df8')throw new Error('Exact V2 master drift');
put('preserved-master-review-state',cycle);
const instruction='AHMET — MASTER REVIEW: V2 APPROVED. I approve Cycle #11 V2, the Han van Meegeren / Vermeer forgery video, as the final production master, subject to my completed playback and device review. Approved master: artifacts/masters/vermeer-forgery-cycle11-candidate-v2.mp4. SHA-256: f6d6da416f45aef07d7ac61eac232eadce5a854b9cd97094162849a70ee98df8. Freeze this exact master and preserve its identity. Do not alter narration, timing, visuals, captions, audio, or historical qualifications without a new explicit owner decision. Proceed with the established publication preparation workflow for YouTube Shorts, TikTok, Instagram Reels and Facebook Reels. Review the existing permanent production improvements; avoid redundant guidance. Preserve historical artifacts and decisions, validate, back up origin/content/cycle-11-discovery without merging main. Stop at AHMET — PUBLICATION REVIEW / AUTHORIZATION · CYCLE #11. Do not upload, schedule, publish or start Cycle #12. Await explicit publication authorization.';
const decision=put('master-approval-v1',ownerDecisionSchema.parse({schemaVersion:3,id:'owner-decision.cycle-11.master-approval-v2',revision:1,gate:'master-review',cycleId:'cycle.11',targetSha256:sha256Json(candidate),decision:'approve',enteredAt:new Date().toISOString(),suppliedReviewTime:null,reviewer:'Ahmet — owner',evidenceBasis:'explicit-owner-message',instruction,acceptedUnknowns:[]}));
let state=persistCycleEvent(root,cycle,{type:'owner-decision',record:decision,at:new Date().toISOString()},registry);
put('master-lock-v1',{cycleId:cycle.id,master:candidate.media,path:master,candidate:cycle.candidate,decision,frozen:true,ownerQualification:'as the final production master, subject to my completed playback and device review',interpretation:'Explicit exact-master approval permits preparation. No named device, completed listening result or native-platform acceptance was supplied; qualification retained without manufacturing evidence.',suppliedReviewTime:null,platformDeviceEvidence:'No device, OS, app version, test time or screenshot supplied; native platform evidence remains not-tested.',publicationAuthorized:false});
const start=put('presentation-start-v1',{cycleId:cycle.id,stage:'presentation',action:'Prepare four exact-master packages, original cover, copy and evidence. No public operation or approval transfer; preserve prior records.'});
state=persistCycleEvent(root,state,{type:'begin-internal',stage:'presentation',record:start,at:new Date().toISOString()},registry);
console.log(JSON.stringify({stage:state.stage,revision:state.revision,master:candidate.media,publicationAuthorized:false}));
