import {execFileSync,spawnSync} from 'node:child_process';
import {existsSync,readFileSync,writeFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {mediaHash} from '../src/artifacts/media';
import {openMediaCatalog} from '../src/artifacts/catalog';
import {sha256Json} from '../src/content-intelligence/run-schema';
import {loadCycle,recoverCycleEvent,loadProjectCycles} from '../src/workflow/store';
import {inspectCycleRelease} from '../src/workflow/release';
import {readBoundRecord,requireOwnerDecision} from '../src/workflow/evidence';
import {nextAction} from '../src/workflow/cycle';
const registry=openMediaCatalog(),root=process.cwd(),base='content-intelligence/cycles/cycle-11/publication',cycle=loadCycle(root,'cycle.11',registry),baseline='7f2e6126f1c07ade5791768b83c1bb6802149322';
if(cycle.stage!=='publication-review'||cycle.revision!==17||!cycle.candidate||!cycle.masterDecision||!cycle.release||cycle.publicationDecision)throw new Error('Wrong publication boundary');
const candidate=readBoundRecord(cycle.candidate) as {media:{id:string;sha256:string}},decision=requireOwnerDecision(cycle.masterDecision,cycle.id,'master-review',candidate);
if(decision.decision!=='approve'||candidate.media.sha256!=='f6d6da416f45aef07d7ac61eac232eadce5a854b9cd97094162849a70ee98df8')throw new Error('Master lock drift');
const at=new Date().toISOString(),inspection=inspectCycleRelease(readBoundRecord(cycle.release),registry,at),risks=JSON.parse(readFileSync(`${base}/risk-register-v1.json`,'utf8'));
if(sha256Json(inspection.unknowns)!==sha256Json(risks.requiredExactPresentationUnknowns)||risks.acceptedByOwner||risks.knownCollisions.length)throw new Error('Risk register drift');
const old=JSON.parse(execFileSync('git',['show',`${baseline}:artifacts/media-catalog.json`],{encoding:'utf8',maxBuffer:16*1024*1024})).artifacts as {id:string;bytes:number}[],catalog=JSON.parse(readFileSync('artifacts/media-catalog.json','utf8')).artifacts as {id:string;bytes:number}[];
for(const row of old)if(sha256Json(row)!==sha256Json(catalog.find(a=>a.id===row.id)))throw new Error('Prior catalog entry changed');
const inputs=JSON.parse(readFileSync('content-intelligence/cycles/cycle-11/revision-v2/implementation-bindings.json','utf8'));
for(const f of inputs.files)if(mediaHash(f.path)!==f.sha256)throw new Error('Approved input changed: '+f.path);
const asset=JSON.parse(readFileSync('content-intelligence/cycles/cycle-11/content-asset.ready.json','utf8'));
const copyLengths:unknown[]=[];
for(const d of inspection.release.deliveries){
 if(d.variant.relationship!=='exact-master'||sha256Json(d.variant.media)!==sha256Json(candidate.media))throw new Error('Unexpected derivative or changed approved media');
 const manifest=readBoundRecord(d.manifest) as {metadata:{path:string;sha256:string};uploadCopy:{path:string;sha256:string}},m=readBoundRecord(manifest.metadata) as {claimIds:string[];firstComment:string;description:string;publicationAuthorized:boolean;operatorSettings:{state:string};title:string|null;hashtags:string[]};
 if(m.title&&m.title.length>100||m.description.length>(d.variant.platform==='youtube'?5000:2200))throw new Error('Copy exceeds conservative review text envelope');
 const expectedProfile=JSON.parse(readFileSync(`content-intelligence/cycles/cycle-11/profiles/${d.variant.platform}.json`,'utf8'));const releaseProfile=readBoundRecord(d.variant.profile) as typeof expectedProfile;
 for(const field of ['compositionSafe','nativeExclusions','captionSafe','cropSafe'])if(sha256Json(releaseProfile[field])!==sha256Json(expectedProfile[field]))throw new Error('Inherited geometry changed');
 copyLengths.push({platform:d.variant.platform,titleCharacters:m.title?.length??0,descriptionCharacters:m.description.length});
 if(!m.firstComment||!m.description.includes('AI-generated narration')||m.publicationAuthorized||m.claimIds.some(id=>!asset.selectedClaimIds.includes(id))||m.operatorSettings.state!=='recommendations-not-applied')throw new Error('Metadata/copy/claim authority drift');
}
const tracked=execFileSync('git',['ls-tree','-r','--name-only',baseline],{encoding:'utf8'}).trim().split('\n');
const allowed=new Set(['artifacts/media-catalog.json','workflow/cycles/cycle.11/state.json','workflow/project-state.json','docs/ASSET-LICENSES.md']);
const changed=new Set(execFileSync('git',['diff','--name-only',baseline,'--'],{encoding:'utf8'}).trim().split('\n'));
const paths=tracked.filter(p=>!allowed.has(p));
for(const path of paths)if(!existsSync(path)||changed.has(path))throw new Error('Historical/source bytes changed: '+path);
const v1={path:'artifacts/masters/vermeer-forgery-cycle11-candidate-v1.mp4',sha256:'cefa95c98accb232b1fb00d3087f74687219200cbbd339275493dd27812d6ff3'};if(mediaHash(v1.path)!==v1.sha256)throw new Error('Historical V1 changed');
const restored=recoverCycleEvent(root,cycle.id,registry);if(sha256Json(restored)!==sha256Json(cycle))throw new Error('Recovery changed state');
const cycles=loadProjectCycles(root,registry),ffmpeg=createRequire(import.meta.url)('ffmpeg-static') as string;
const decoded=spawnSync(ffmpeg,['-v','error','-xerror','-err_detect','explode','-i',registry.resolveFile(candidate.media),'-map','0:v:0','-map','0:a:0','-f','null','-'],{encoding:'utf8'});if(decoded.status!==0)throw new Error(decoded.stderr);
const additions=catalog.filter(row=>!old.some(o=>o.id===row.id));
const report={checkedAt:at,passed:true,cycleId:cycle.id,revision:cycle.revision,nextAction:nextAction(cycle),release:cycle.release,reviewTargetSha256:sha256Json(inspection.release),masterApproval:cycle.masterDecision,masterUnchanged:true,fullMediaDecode:'passed',approvedSourceAndInputHashesUnchanged:true,priorCanonicalEntriesUnchanged:old.length,canonicalPayloads:catalog.length,newCanonicalPayloads:additions.length,newMediaBytes:additions.reduce((n,a)=>n+a.bytes,0),historicalFilesUnchanged:paths.length,v1Preserved:v1,workflowReplay:cycles.map(c=>({id:c.id,revision:c.revision,stage:c.stage})),recovery:'exact no-op',stateSha256:mediaHash('workflow/cycles/cycle.11/state.json'),event17Sha256:mediaHash('workflow/cycles/cycle.11/event-17.json'),copyLengths,inheritedGeometryUnchanged:true,uniqueVideoPayloads:1,derivativeVideos:0,uniqueSelectedCoverPayloads:2,newCoverPayloads:1,unknownCount:inspection.unknowns.length,knownCollisions:[],uploads:inspection.uploads,publicationAuthorized:false,externalPlatformActions:[]};
writeFileSync(`${base}/readiness-validation-v1.json`,JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,revision:cycle.revision,gate:cycle.stage,masterUnchanged:true,unknownCount:inspection.unknowns.length,newMediaBytes:report.newMediaBytes}));
