import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {readFileSync,existsSync} from 'node:fs';
import {z} from 'zod';
import {sha256Json,stableJson} from '../src/content-intelligence/run-schema';
import {knowledgePackageSchema} from '../src/knowledge/schema';
import {contentAssetSchema} from '../src/content-assets/schema';
import {creativeDirectionSchema} from '../src/content-assets/creative-direction';
import {validateCreativeDirection} from '../src/content-assets/creative-direction-integrity';
import {validateProductionPlanReferences} from '../src/production/schema';
import {validateAdaptiveCaptionPlan} from '../src/captions/adaptive-plan';
export const productionDirectory='content-intelligence/reviews/chocolate-crystal-choice-production-v1';
const base='cca828c3320a062764cf3185dd23bd05ce197404';
const read=(p:string):unknown=>JSON.parse(readFileSync(p,'utf8'));
const bytes=(p:string)=>createHash('sha256').update(readFileSync(p)).digest('hex');
const ref=(v:{id:string;revision:number})=>({id:v.id,revision:v.revision,sha256:sha256Json(v)});
const same=(a:unknown,b:unknown,message:string)=>{if(stableJson(a)!==stableJson(b))throw new Error(message);};
export const validateChocolateProduction=()=>{
 const pkg=knowledgePackageSchema.parse(read('content-intelligence/reviews/chocolate-crystal-choice-approved-v3/knowledge-package.approved.json'));
 const asset=contentAssetSchema.parse(read('content-intelligence/reviews/chocolate-crystal-choice-approved-v3/content-asset.approved.json'));
 const original=creativeDirectionSchema.parse(read('content-intelligence/creative-directions/chocolate-crystal-choice-same-recipe/direction-v1.json'));
 const decision=z.object({id:z.literal('owner-decision.chocolate-crystal-choice.production-v1'),revision:z.literal(1),owner:z.literal('Ahmet Nishefci'),decision:z.literal('approved-creative-direction-and-one-master-candidate'),enteredAt:z.iso.datetime(),ownerSuppliedReviewTimestamp:z.null(),reviewTimeBasis:z.literal('decision-entry'),approvedDirection:z.unknown(),knowledgePackage:z.unknown(),contentAsset:z.unknown(),approvedScriptSha256:z.string(),sourceCommit:z.literal(base),scope:z.array(z.string()).length(3),masterApprovalGranted:z.literal(false),platformApprovalGranted:z.literal(false),publicationApprovalGranted:z.literal(false),nextGate:z.literal('AHMET — CYCLE #3 OWNER MASTER VISUAL REVIEW'),schemaVersion:z.literal(1)}).strict().parse(read(`${productionDirectory}/owner-decision.json`));
 same(decision.approvedDirection,ref(original),'Owner approval binds wrong direction');same(decision.knowledgePackage,ref(pkg),'Owner package drift');same(decision.contentAsset,ref(asset),'Owner asset drift');
 const direction=validateCreativeDirection(read(`${productionDirectory}/direction-approved-v2.json`),pkg,asset);
 same(direction,{...original,revision:2,state:'ready-for-production-planning',ownerReview:{...original.ownerReview,decision:ref(decision)},provenance:{...original.provenance,enteredAt:decision.enteredAt,notes:'Revision 1 owner-approved without creative changes. Revision 2 records readiness and exact decision-entry binding; one candidate only, no platform/publication approval.'}},'Approved creative decisions changed');
 const plan=validateProductionPlanReferences(read('src/production/plans/chocolate.json'),pkg,asset,direction);
 const narration=z.object({cues:z.array(z.object({id:z.string(),file:z.string(),transcript:z.string(),start:z.number(),duration:z.number(),sampleRate:z.literal(24000),samples:z.number()}).passthrough()),measuredNarrationSeconds:z.number(),durationFrames:z.number(),provenance:z.object({voiceId:z.literal('af_heart'),speed:z.literal(.98),provider:z.literal('kokoro-local'),approvedScriptSha256:z.string(),cueArtifacts:z.array(z.object({id:z.string(),sha256:z.string()}))}).passthrough()}).passthrough().parse(read('src/production/narration/chocolate.json'));
 same(plan.ownerDecision,ref(decision),'Plan owner authority stale');same(plan.creativeDirection,ref(direction),'Direction binding stale');
 if(plan.status!=='rendered-candidate-visual-review-required'||plan.visualApproval||plan.beats.length!==8||asset.selectedClaimIds.length!==8||pkg.claims.filter(c=>c.verificationStatus==='verified').length!==8)throw new Error('Candidate gate/claims bypass');
 same(plan.excludedClaimIds,pkg.claims.filter(c=>!asset.selectedClaimIds.includes(c.id)).map(c=>c.id),'Reserve research promoted');
 const text=asset.script.segments.map(s=>s.text).join(' ');if(text.split(/\s+/).length!==80||narration.cues.map(c=>c.transcript).join(' ')!==text||narration.provenance.approvedScriptSha256!==sha256Json(asset.script)||decision.approvedScriptSha256!==sha256Json(asset.script))throw new Error('Exact locked narration drift');
 for(const c of narration.cues){if(bytes(`public/${c.file}`)!==narration.provenance.cueArtifacts.find(p=>p.id===c.id)?.sha256||Math.abs(c.samples/c.sampleRate-c.duration)>1e-8)throw new Error('Narration bytes/duration drift');}
 if(Math.abs(narration.cues.reduce((s,c)=>s+c.duration,0)-narration.measuredNarrationSeconds)>1e-8||Math.round(plan.format.durationSeconds*30)!==narration.durationFrames)throw new Error('Measured story duration drift');
 const model=z.object({voiceId:z.literal('af_heart'),selectedVoice:z.literal('af_heart'),speed:z.literal(.98),model:z.literal('onnx-community/Kokoro-82M-v1.0-ONNX')}).passthrough().parse(read(`${productionDirectory}/model-provenance.json`));void model;
 const captions=validateAdaptiveCaptionPlan(read('src/captions/plans/chocolate.json'),narration.cues,plan.format,direction,asset);if(captions.status!=='review-required'||plan.captions.captionPlanSha256!==sha256Json(captions))throw new Error('Caption approval/binding drift');
 const source=readFileSync('src/compositions/Chocolate.tsx','utf8');const objects=readFileSync('src/components/ChocolateMaterial.tsx','utf8');
 if(!source.includes('SIMPLIFIED EXPLANATORY MODEL')||!source.includes('Crystal arrangement')||!source.includes('Larger fat-crystal network')||!objects.includes('retained-sugar-cocoa-solids')||!source.includes('simplified-crystal-packing')||source.includes('Form V')||source.includes('Form-V'))throw new Error('Scientific comprehension/disclosure invariant missing');
 const font=z.object({license:z.literal('SIL Open Font License 1.1'),unmodified:z.literal(true),files:z.array(z.object({path:z.string(),sha256:z.string()}))}).passthrough().parse(read('public/fonts/chocolate/provenance.json'));for(const f of font.files)if(bytes(f.path)!==f.sha256)throw new Error('Font/license provenance drift');
 const sound=z.object({path:z.string(),sha256:z.string(),music:z.literal(false),microscopicSonification:z.literal(false),events:z.array(z.object({at:z.number()}).passthrough()).length(3)}).passthrough().parse(read(`${productionDirectory}/sound-provenance.json`));if(bytes(sound.path)!==sound.sha256)throw new Error('Sound provenance drift');
 const allowed=(p:string)=>p.startsWith(`${productionDirectory}/`)||p.startsWith('public/audio/chocolate/')||p.startsWith('public/fonts/chocolate/')||p.startsWith('artifacts/qa/chocolate-crystal-choice/')||[
 'public/captions/chocolate.en.vtt','src/production/narration/chocolate.json','src/production/plans/chocolate.json','src/captions/plans/chocolate.json','src/components/ChocolateMaterial.tsx','src/compositions/Chocolate.tsx','src/chocolate-index.tsx','src/content/videos/chocolate-crystal-choice.ts','scripts/generate-chocolate-narration.mjs','scripts/generate-chocolate-production.py','scripts/inspect-chocolate-audio.mjs','scripts/qa-chocolate-layout.ts','scripts/qa-chocolate-media.mjs','scripts/master-chocolate-audio.mjs','scripts/validate-chocolate-production.ts','scripts/production-video-targets.ts','scripts/validate-production.ts','scripts/validate-chocolate-direction.ts','scripts/finalize-chocolate-candidate.ts','tests/chocolate-production.test.ts','src/artifacts/registry.ts','artifacts/chocolate-crystal-choice-manifests.json','artifacts/masters/chocolate-crystal-choice-candidate-v1.mp4','docs/PROJECT-STATE.md','docs/DECISIONS.md','docs/ASSET-LICENSES.md'].includes(p);
 const changed=execFileSync('git',['diff','--name-only',base,'--'],{encoding:'utf8'}).trim().split('\n').filter(Boolean);const untracked=execFileSync('git',['ls-files','--others','--exclude-standard'],{encoding:'utf8'}).trim().split('\n').filter(Boolean);if([...changed,...untracked].some(p=>!allowed(p)))throw new Error('Production scope/history preservation violation: '+[...changed,...untracked].filter(p=>!allowed(p)).join(','));
 for(const path of ['content-intelligence/reviews/chocolate-crystal-choice-v1','content-intelligence/reviews/chocolate-crystal-choice-finalization-v2','content-intelligence/reviews/chocolate-crystal-choice-approved-v3','content-intelligence/creative-directions/chocolate-crystal-choice-same-recipe','content-intelligence/discovery/cycle-3-2026-10-01','content-intelligence/operations/longitude-clock-scheduling-v1','content-intelligence/reviews/longitude-clock-publication-v1']){const names=execFileSync('git',['ls-tree','-r','--name-only',base,'--',path],{encoding:'utf8'}).trim().split('\n').filter(Boolean);for(const name of names)if(!readFileSync(name).equals(execFileSync('git',['show',`${base}:${name}`])))throw new Error('Protected history changed: '+name);}
 const receiptPath=`${productionDirectory}/candidate-receipt.json`;
 if(!existsSync(receiptPath))throw new Error('Rendered candidate requires retained receipt and complete QA evidence');
 if(existsSync(receiptPath)){const receipt=z.object({path:z.string(),sha256:z.string(),ownerApproved:z.literal(false),locked:z.literal(false),platformApprovalGranted:z.literal(false),publicationApprovalGranted:z.literal(false),productionPlan:z.unknown(),captionPlan:z.unknown(),creativeDirection:z.unknown(),sourceFiles:z.array(z.object({path:z.string(),sha256:z.string()}))}).passthrough().parse(read(receiptPath));if(bytes(receipt.path)!==receipt.sha256)throw new Error('Candidate identity corrupt');same(receipt.productionPlan,ref(plan),'Receipt plan drift');same(receipt.captionPlan,ref(captions),'Receipt caption drift');same(receipt.creativeDirection,ref(direction),'Receipt direction drift');for(const f of receipt.sourceFiles)if(bytes(f.path)!==f.sha256)throw new Error('Rendered source binding stale: '+f.path);
 for(const file of ['report.json','typography-report.json','decode-report.json']){const report=z.object({passed:z.literal(true)}).passthrough().parse(read(`artifacts/qa/chocolate-crystal-choice/${file}`));void report;}
 const typography=z.object({observations:z.array(z.object({frame:z.number(),fontsLoaded:z.literal(true),disclosure:z.literal(true),labels:z.array(z.object({text:z.string().nullable()}).passthrough())}).passthrough())}).passthrough().parse(read('artifacts/qa/chocolate-crystal-choice/typography-report.json'));for(const c of captions.cues)if(!typography.observations.some(o=>o.frame===Math.round((c.startFrame+c.endFrame)/2)))throw new Error('Caption midpoint not inspected');if(!typography.observations.some(o=>o.labels.some(l=>l.text==='Crystal arrangement'))||!typography.observations.some(o=>o.labels.some(l=>l.text==='Larger fat-crystal network')))throw new Error('Both explanatory scales need actual rendered browser evidence');
 const audio=z.object({masterSha256:z.string(),results:z.array(z.unknown()).length(11),completeMasterRecognition:z.object({text:z.string().min(1)}).passthrough()}).passthrough().parse(read(`${productionDirectory}/narration-inspection.json`));if(audio.masterSha256!==receipt.sha256)throw new Error('Complete audio inspection binds stale master');
 const qaBindings=z.object({qaFiles:z.array(z.object({path:z.string(),sha256:z.string()}))}).passthrough().parse(read(receiptPath));for(const f of qaBindings.qaFiles)if(bytes(f.path)!==f.sha256)throw new Error('Decoded QA bytes changed');}
 return {passed:true,ownerApproval:decision.id,direction:ref(direction),productionPlan:ref(plan),captionPlan:ref(captions),verifiedClaims:8,reserveClaimsPreserved:34,narrationWords:80,narrationSeconds:narration.measuredNarrationSeconds,masterSeconds:plan.format.durationSeconds,captionCues:captions.cues.length,masterOwnerApproved:false,publicationAuthorized:false,candidateReceiptPresent:existsSync(receiptPath),nextGate:decision.nextGate};
};
if(process.argv[1]?.endsWith('validate-chocolate-production.ts'))console.log(JSON.stringify(validateChocolateProduction(),null,2));
