import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {z} from 'zod';
import {parseManifests} from '../src/artifacts/schema';
import {validateChocolateLockedMaster,chocolateFileHash as hash,chocolateMasterDecision as decision} from '../src/production/chocolate-master-integrity';
import {chocolatePlatformVariants} from '../src/platform-variants/variants/chocolate-crystal-choice';
import {coverAssetSchema,presentationOutputSchema,presentationQaSchema,presentationProfileSchema,validatePresentationRegions} from '../src/platform-variants/presentation';
import {chocolatePreparedDeliveryDependencies as dependencies} from './chocolate-prepared-delivery';
import {publicationRegistry,metricSnapshotRegistry} from '../src/operations/registry';
import {validateDeliveryPackage} from './delivery-packages';
import {sha256Json} from '../src/content-intelligence/run-schema';
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8'));
export const validateChocolatePlatform=()=>{
 const root='content-intelligence/reviews/chocolate-crystal-choice-platform-v1',qaRoot='artifacts/qa-evidence/chocolate-crystal-choice-platform-v1';const master=validateChocolateLockedMaster();const index=read(root+'/delivery-index.json');
 if(index.platformApproved||index.publicationAuthorized||index.packages.length!==4||!index.masterBytesReused)throw new Error('Invalid pending delivery scope');
 for(const entry of index.packages){const m=validateDeliveryPackage(entry.directory,dependencies);const v=dependencies.variantRegistry.get(m.source.platformVariant.id);if(m.state!=='draft-review'||m.publishEligible||v.status!=='editorial-review'||v.approval||v.previewStatus!=='ready-for-private-preview')throw new Error('Inferred platform/publication approval');if(hash(entry.directory+'/video.mp4')!==master.artifact.sha256||hash(entry.directory+'/manifest.json')!==entry.manifestFileSha256||sha256Json(m)!==entry.manifestSha256||m.deliveryId!==entry.deliveryId||sha256Json(v)!==entry.variant.sha256)throw new Error('Delivery identity drift');}
 for(const v of chocolatePlatformVariants)if(v.productionIntent.renderStrategy!=='reuse-existing-master'||v.sourceMaster?.artifact.sha256!==master.artifact.sha256||v.duration.targetSeconds!==1195/30||v.packaging.claimIds.length!==8||v.sourceMaster.productionPlan.revision!==2||v.sourceMaster.captionPlan.sha256!==decision.captionPlan.sha256)throw new Error('Master reuse/editorial binding drift');
 const qas=z.array(presentationQaSchema).parse(read(root+'/presentation-qa.json'));const outputs=z.array(presentationOutputSchema).parse(read(root+'/presentation-outputs.json'));const covers=z.array(coverAssetSchema).parse(read('artifacts/chocolate-crystal-choice-cover-assets.json'));const profiles=z.array(presentationProfileSchema).parse(read('artifacts/presentation-profiles.json'));const regions=read(root+'/critical-regions.json');
 if(qas.length!==9||outputs.length!==9||covers.length!==1)throw new Error('Missing surface evaluation');
 for(const qa of qas){if(qa.mediaSha256!==master.artifact.sha256||qa.testedAt||qa.reviewer||qa.device||qa.os||qa.appVersion||!['LOCAL_APPROXIMATION','PRIVATE_PREVIEW_PENDING'].includes(qa.state))throw new Error('Invented device evidence');for(const path of qa.evidence)readFileSync(path);const report=read(qa.evidence[0]!),profile=profiles.find(p=>p.id===qa.profileId)!;if(report.profileSha256!==sha256Json(profile)||report.platformApprovalGranted||report.publicationApprovalGranted||report.masterModified||report.derivativeCreated)throw new Error('Surface provenance drift');if(qa.state==='LOCAL_APPROXIMATION'){const replay=validatePresentationRegions(profile,regions);if(replay.violations.length||sha256Json({...replay,profileId:profile.id,insets:profile.insets,evidenceLevel:profile.evidenceLevel,lifecycle:profile.lifecycle,realDeviceReviewRequired:true})!==sha256Json(report.assessment))throw new Error('Local model assessment drift');}else if(report.assessment.state!=='UNMEASURED'||report.assessment.insets)throw new Error('Invented crop/desktop geometry');}
 for(const output of outputs)if(output.derivativeArtifactId||output.masterArtifactId!==master.masterArtifactId)throw new Error('Unnecessary derivative');
 for(const cover of covers)if(cover.status!=='review'||cover.approvalDecisionId||cover.crop||cover.sourceVideoSha256!==master.artifact.sha256||hash('artifacts/covers/chocolate-crystal-choice-instagram-cover-v1.png')!==cover.sha256)throw new Error('Cover drift/approval/crop invention');
 const provenance=read(root+'/cover-provenance.json');for(const f of provenance.sourceBindings)if(hash(f.path)!==f.sha256)throw new Error('Cover provenance drift');if(provenance.ownerApproved||provenance.externalProductionImagery||provenance.crop)throw new Error('Invalid cover rights/approval');const coverQa=read(qaRoot+'/cover-browser.json');if(!coverQa.passed||!coverQa.observation.fontsLoaded||coverQa.realDevicePasses||coverQa.ownerCoverApproved)throw new Error('Cover browser verification missing');
 const intake=read(root+'/publication-evidence-intake.json');if(intake.publicationAuthorized||intake.purpose!=='prepared-intake-not-publication-record'||intake.entries.length!==4)throw new Error('Invalid intake');for(const e of intake.entries){for(const k of ['publicUrl','platformContentId','publishedAt','publishedOn','actualUploadedVariant','actualUploadedDelivery','actualVisibility','actualSettings','ownerPresentationResult','device','os','appVersion','firstCommentId','firstCommentPostedAt','reportedBy'])if(e[k]!==null)throw new Error('Fabricated publication/presentation field: '+k);if(e.screenshots.length||e.evidence.length)throw new Error('Invented live evidence');const v=chocolatePlatformVariants.find(v=>v.platform===e.platform)!;if(sha256Json(v)!==e.intendedVariant.sha256)throw new Error('Intended intake binding drift');}
 const analytics=read(root+'/analytics-readiness.json');if(analytics.captureAt||analytics.observationWindow||analytics.metricSnapshots.length||analytics.publicationRecords.length||publicationRegistry.list().some(r=>r.id.includes('chocolate-crystal-choice'))||metricSnapshotRegistry.list().some(r=>JSON.stringify(r).includes('chocolate-crystal-choice')))throw new Error('Premature publication/analytics');
 const decode=z.object({passed:z.literal(true),fullVideoAndAudioDecode:z.literal(true),masterModified:z.literal(false),realDevicePasses:z.literal(0),mediaSha256:z.literal(master.artifact.sha256)}).passthrough().parse(read(qaRoot+'/media-decode.json'));void decode;
 const captions=read('src/captions/plans/chocolate.json'),inspection=read(qaRoot+'/caption-midpoints.json');if(!inspection.passed||inspection.realDevicePasses||inspection.mediaSha256!==master.artifact.sha256||inspection.captionPlanSha256!==decision.captionPlan.sha256||inspection.inspectedCaptionMidpoints!==28||sha256Json(inspection.sheets.flatMap((s:{observations:unknown[]})=>s.observations))!==sha256Json(captions.cues.map((c:{id:string;startFrame:number;endFrame:number;lines:string[]})=>({cueId:c.id,frame:Math.round((c.startFrame+c.endFrame)/2),lines:c.lines}))))throw new Error('Caption midpoint coverage drift');for(const s of inspection.sheets)if(hash(s.path)!==s.sha256)throw new Error('Caption sheet drift');
 const manifests=parseManifests(read('artifacts/chocolate-crystal-choice-platform-manifests.json'));for(const m of manifests){if(hash(m.localPath)!==m.identity.sha256||readFileSync(m.localPath).length!==m.identity.bytes||m.publication!=='not-authorized')throw new Error('Retained artifact drift');if(m.artifactId===master.masterArtifactId?m.approvalScope!=='owner-visual'||m.approvalDecisionId!==decision.id:m.approvalScope!=='none')throw new Error('Approval transfer');}
 const checkpoint='d317a4f5a4f7a8df57bc371855fb3a7e4b886aa5';const allowed=(p:string)=>['content-intelligence/reviews/chocolate-crystal-choice-master-lock-v1/','content-intelligence/reviews/chocolate-crystal-choice-platform-v1/','artifacts/qa-evidence/chocolate-crystal-choice-platform-v1/','artifacts/deliveries/chocolate-crystal-choice-v1/'].some(prefix=>p.startsWith(prefix))||['artifacts/chocolate-crystal-choice-platform-manifests.json','artifacts/chocolate-crystal-choice-cover-assets.json','artifacts/covers/chocolate-crystal-choice-instagram-cover-v1.png','src/chocolate-cover-index.tsx','src/platform-variants/variants/chocolate-crystal-choice.ts','src/production/chocolate-master-integrity.ts','src/artifacts/registry.ts','scripts/prepare-chocolate-master-lock.ts','scripts/prepare-chocolate-platform.ts','scripts/chocolate-prepared-delivery.ts','scripts/generate-chocolate-deliveries.ts','scripts/qa-chocolate-cover.ts','scripts/qa-chocolate-platform-media.ts','scripts/register-chocolate-platform-artifacts.ts','scripts/validate-chocolate-platform.ts','scripts/validate-chocolate-production.ts','tests/chocolate-platform.test.ts','docs/PROJECT-STATE.md','docs/DECISIONS.md','docs/ASSET-LICENSES.md'].includes(p);
 const changed=execFileSync('git',['diff','--name-only',checkpoint,'--'],{encoding:'utf8'}).trim().split('\n').filter(Boolean);const untracked=execFileSync('git',['ls-files','--others','--exclude-standard'],{encoding:'utf8'}).trim().split('\n').filter(Boolean);const excluded=[...changed,...untracked].filter(p=>!allowed(p));if(excluded.length)throw new Error('Post-master history/scope preservation violation: '+excluded.join(','));
 return {passed:true,master,variants:chocolatePlatformVariants.map(v=>({id:v.id,revision:v.revision,state:v.status})),packages:4,surfaces:9,knownInsetAssessments:4,unmeasuredSurfaceAssessments:5,realDevicePasses:0,captionMidpoints:28,retainedArtifacts:manifests.length,historyCheckpoint:checkpoint,historyScopePassed:true,publicationAuthorized:false,nextGate:'AHMET — CYCLE #3 PLATFORM DELIVERY / PUBLICATION REVIEW'};
};
if(process.argv[1]?.endsWith('validate-chocolate-platform.ts'))console.log(JSON.stringify(validateChocolatePlatform(),null,2));
