import {readFileSync,existsSync} from 'node:fs';
import baseline from '../system-audits/adaptive-creative-direction-v1/historical-baseline.json';
import {validateAdaptiveHistoricalBytes} from './adaptive-historical-integrity';
import {knowledgePackageRegistry} from '../src/knowledge/registry';
import {contentAssetRegistry} from '../src/content-assets/registry';
import {validateWoodFrogProductionPlan} from '../src/production/integrity';
import {validatePhantomTrafficLockedMaster} from '../src/production/phantom-traffic-master-integrity';
import {contentIntelligencePromptRegistry} from '../src/content-intelligence/prompts';
const historicalStates=baseline.files.map(file=>validateAdaptiveHistoricalBytes(file,readFileSync(file.path)));
const guide=readFileSync('AGENTS.md','utf8');
for(const route of guide.matchAll(/`((?:docs|recovery-audit)\/[^`]+\.md)`/g)) if(!existsSync(route[1]!)) throw new Error(`Missing canonical route: ${route[1]}`);
if(!guide.includes('docs/CREATIVE-DIRECTION.md')) throw new Error('Missing adaptive authority route');
const authority=readFileSync('docs/CREATIVE-DIRECTION.md','utf8');
for(const principle of ['brand, not a video template','Discover first. Classify second.','convergence','Long-form','real-device','approved','rationale']) if(!authority.toLowerCase().includes(principle.toLowerCase())) throw new Error(`Missing documented authority: ${principle}`);
validateWoodFrogProductionPlan();const master=validatePhantomTrafficLockedMaster();
console.log(JSON.stringify({passed:true,historicalFilesUnchanged:historicalStates.filter(state=>state==='original-baseline').length,exactClosureCheckpoints:historicalStates.filter(state=>state==='exact-cycle-1-closure').length,knowledgePackages:knowledgePackageRegistry.list().length,contentAssets:contentAssetRegistry.list().length,creativeWorkflow:contentIntelligencePromptRegistry.get('workflow.creative-direction').id,woodFrogUnchanged:true,phantomTraffic:master.artifact,platformRecordsUnchanged:true,newProductionStarted:false},null,2));
