import {execFileSync} from 'node:child_process';
import {existsSync,readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {loadMediaRegistry,mediaHash} from '../src/artifacts/media';
import {sha256Json} from '../src/artifacts/json-identity';
import {assertMediaProductionEligible} from '../src/artifacts/retention';
import {loadProjectCycles,recoverCycleEvent} from '../src/workflow/store';
import {validateCanonicalMediaDurability,validateArchitectureScope} from './artifact-v2-integrity';
const sourceRoot=process.cwd(),root=process.argv[2]?resolve(process.argv[2]):sourceRoot,base='content-intelligence/cycles/cycle-8/retention-repair-v1';
const bindings=JSON.parse(readFileSync(resolve(root,`${base}/preservation-bindings.json`),'utf8')) as {files:{path:string;sha256:string}[]};
const oldPath='artifacts/masters/oklo-cycle8-candidate-v2.mp4',replacement='artifacts/masters/oklo-cycle8-candidate-v3.mp4';
const wasAbsent=!existsSync(resolve(root,oldPath));
const tracked=execFileSync('git',['ls-files','-z'],{cwd:sourceRoot,encoding:'utf8'}).split('\0').filter(Boolean);
const durability=validateCanonicalMediaDurability(root,tracked),registry=loadMediaRegistry(root);
for(const file of bindings.files)if(mediaHash(resolve(root,file.path))!==file.sha256)throw new Error('Preserved identity changed: '+file.path);
const cycles=loadProjectCycles(root,registry),cycle=cycles.find(c=>c.id==='cycle.8')!,historical=cycles.find(c=>c.id==='cycle.7')!;
if(cycle.stage!=='master-review'||cycle.revision!==11||cycle.masterDecision||cycle.release||cycle.publicationDecision||existsSync(resolve(root,'workflow/cycles/cycle.9')))throw new Error('Wrong Cycle8 boundary');
const candidate=JSON.parse(readFileSync(resolve(root,cycle.candidate!.path),'utf8'));
if(registry.get(candidate.media).canonicalPath!==replacement||historical.revision!==25||historical.stage!=='authorized')throw new Error('Current/historical candidate changed');
const original=registry.byHash('174246ddb71176af3c23d2372ed2cc0019fd386421cb7e0c15fff2ee091cf29d')!;
let rejected=false;try{assertMediaProductionEligible({id:original.id,sha256:original.sha256},root);}catch{rejected=true;}if(!rejected)throw new Error('Retained V2 became eligible');
const recovered=recoverCycleEvent(root,cycle.id,registry);if(sha256Json(recovered)!==sha256Json(cycle))throw new Error('Recovery changed state');
const prior='2c14498ae6e04333869e44affacc86cc11e77156';
const paths=execFileSync('git',['ls-tree','-r','--name-only',prior],{cwd:sourceRoot,encoding:'utf8'}).trim().split('\n').filter(p=>/cycle-7|cycle\.7|interaction-free|ifm|sealed-scroll|QuantumPossibilities/.test(p));
for(const path of paths)if(!readFileSync(resolve(root,path)).equals(execFileSync('git',['show',`${prior}:${path}`],{cwd:sourceRoot,maxBuffer:128*1024*1024})))throw new Error('Historical bytes changed: '+path);
const result={checkedAt:new Date().toISOString(),scope:root===sourceRoot?'current-workspace':'isolated-index-checkout',restoredFromArchive:wasAbsent,sourceMediaCachesUsed:false,durability,workflowReplay:cycles.map(c=>({id:c.id,revision:c.revision,stage:c.stage})),recovery:'exact no-op; no pending event',preservationBindings:'all exact',historicalFilesCompared:paths.length,cycle8:{revision:cycle.revision,stage:cycle.stage,stateSha256:mediaHash(resolve(root,'workflow/cycles/cycle.8/state.json')),candidate:cycle.candidate,media:candidate.media},v2:{bytes:original.bytes,sha256:original.sha256,productionEligible:false,materializationPresent:existsSync(resolve(root,oldPath))},v3:{bytes:registry.get(candidate.media).bytes,sha256:candidate.media.sha256,unchanged:true},architecture:root===sourceRoot?validateArchitectureScope():null,masterApproved:false,releasePrepared:false,externalPlatformActions:[]};
const name=root===sourceRoot?'scope-verification.json':'clean-checkout-verification.json';writeFileSync(resolve(sourceRoot,`${base}/${name}`),JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(result,null,2));
