import {execFileSync} from 'node:child_process';
import {existsSync,readFileSync,writeFileSync} from 'node:fs';
import {loadMediaRegistry,mediaHash} from '../src/artifacts/media';
import {sha256Json} from '../src/artifacts/json-identity';
import {assertMediaProductionEligible} from '../src/artifacts/retention';
import {loadProjectCycles,recoverCycleEvent} from '../src/workflow/store';
import {validateCanonicalMediaDurability,validateArchitectureScope} from './artifact-v2-integrity';
const root=process.cwd(),base='content-intelligence/cycles/cycle-8/editorial-revision-v4',final=`${base}/compression-pass-2/visual-pass-3`;
const bindings=JSON.parse(readFileSync(`${base}/preservation-bindings.json`,'utf8')) as {files:{path:string;sha256:string}[]};
for(const file of bindings.files){const path=file.path==='workflow/cycles/cycle.8/state.json'?`${base}/preserved-master-review-state.bytes.json`:file.path;if(mediaHash(path)!==file.sha256)throw new Error('Preserved identity changed: '+file.path);}
const tracked=execFileSync('git',['ls-files','-z'],{encoding:'utf8'}).split('\0').filter(Boolean);
const durability=validateCanonicalMediaDurability(root,tracked),registry=loadMediaRegistry(root),cycles=loadProjectCycles(root,registry),cycle=cycles.find(c=>c.id==='cycle.8')!;
if(cycle.stage!=='master-review'||cycle.revision!==23||cycle.masterDecision||cycle.release||cycle.publicationDecision||existsSync('workflow/cycles/cycle.9'))throw new Error('Wrong Cycle8 boundary');
const candidate=JSON.parse(readFileSync(cycle.candidate!.path,'utf8')),media=registry.get(candidate.media);
if(media.canonicalPath!=='artifacts/masters/oklo-cycle8-candidate-v5.mp4')throw new Error('Wrong candidate');
const original=registry.byHash('174246ddb71176af3c23d2372ed2cc0019fd386421cb7e0c15fff2ee091cf29d')!;
let rejected=false;try{assertMediaProductionEligible({id:original.id,sha256:original.sha256},root);}catch{rejected=true;}if(!rejected)throw new Error('Retained V2 became eligible');
assertMediaProductionEligible(candidate.media,root);
const recovered=recoverCycleEvent(root,cycle.id,registry);if(sha256Json(recovered)!==sha256Json(cycle))throw new Error('Recovery changed state');
const prior='2c14498ae6e04333869e44affacc86cc11e77156';
const paths=execFileSync('git',['ls-tree','-r','--name-only',prior],{encoding:'utf8'}).trim().split('\n').filter(p=>/cycle-7|cycle\.7|interaction-free|ifm|sealed-scroll|QuantumPossibilities/.test(p));
for(const path of paths)if(!readFileSync(path).equals(execFileSync('git',['show',`${prior}:${path}`],{maxBuffer:128*1024*1024})))throw new Error('Historical bytes changed: '+path);
const originalCatalog=JSON.parse(execFileSync('git',['show','f090f76:artifacts/media-catalog.json'],{encoding:'utf8',maxBuffer:16*1024*1024}));
const currentCatalog=JSON.parse(readFileSync('artifacts/media-catalog.json','utf8'));
const oldRows=Array.isArray(originalCatalog)?originalCatalog:originalCatalog.artifacts??originalCatalog.media;
const newRows=Array.isArray(currentCatalog)?currentCatalog:currentCatalog.artifacts??currentCatalog.media;
if(!Array.isArray(oldRows)||!Array.isArray(newRows))throw new Error('Catalog shape');
for(const row of oldRows)if(JSON.stringify(row)!==JSON.stringify(newRows.find(r=>r.id===row.id)))throw new Error('Historical catalog row changed: '+row.id);
const result={checkedAt:new Date().toISOString(),durability,preservationBindings:{files:bindings.files.length,passed:true},historicalFilesCompared:paths.length,historicalCatalogRowsUnchanged:oldRows.length,workflowReplay:cycles.map(c=>({id:c.id,revision:c.revision,stage:c.stage})),recovery:'exact no-op; no pending event',cycle8:{revision:cycle.revision,stage:cycle.stage,stateSha256:mediaHash('workflow/cycles/cycle.8/state.json'),normalizedStateSha256:sha256Json(cycle),eventSha256:mediaHash('workflow/cycles/cycle.8/event-23.json'),candidate:cycle.candidate,media:candidate.media,bytes:media.bytes},v2:{bytes:original.bytes,sha256:original.sha256,productionEligible:false,preserved:true},v3:{bytes:98563307,sha256:mediaHash('artifacts/masters/oklo-cycle8-candidate-v3.mp4'),unchanged:true},v4:{sha256:mediaHash('artifacts/masters/oklo-cycle8-candidate-v4.mp4'),preservedUnsubmittedIntermediate:true},architecture:validateArchitectureScope(),masterApproved:false,releasePrepared:false,externalPlatformActions:[]};
writeFileSync(`${final}/scope-verification.json`,JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(result,null,2));
